### PR TITLE
Unreachable code warnings #3927 - fix

### PR DESCRIPTION
**Pull request by tulls5o7**
Removed unnecessary break statements per issue #3927

### CODE REVIEW

**Comment by maggiepint** [comment]
So, this is on the moment built file. I now understand why you are trying to make this change - sorry I didn't dig deeper on that issue, but you would have to find the individual files in the /src directory to actually make it.

**Comment by ichernev** [comment]
@maggiepint so jslint decided to be more pedantic and now we have to accept individual fixes for individual files ... that is so wrong :)

**Comment by ichernev** [comment]
@tulls5o7 @maggiepint can someone explain why every other person is changing switch statements in PRs?

**Comment by marwahaha** [comment]
I'm going to close this. If you'd like to make another try, make sure to edit files in the `src/` directory.

Please reach out if you need help or have questions.

**Pull request closed without merging**
