### PR TITLE
Fix russian locale for calendar next week

### PR DESCRIPTION
**Pull request by vsn4ik**
Reproduce issue:
1. Open http://momentjs.com/
2. Set `Russian` locale.
3. Execute in console (wrong)
```js
moment().subtract(3, 'days').calendar() == moment().add(4, 'days').calendar()
```

### CODE REVIEW

**Comment by vsn4ik** [comment]
Update js code
```js
var w1 = moment().startOf('week');
var w2 = moment(w1).add(1, 'w');
var equal = 0;

for (var i = 0; i < 7; i++) {
  var cond1 = moment(w1).add({d: i}).calendar();
  var cond2 = moment(w2).add({d: i}).calendar();

  if (cond1 == cond2) {
    equal++;
  }
}
equal == 4;
```

**Comment by ichernev** [comment]
@Viktorminator can you comment on that, please?

**Comment by vsn4ik** [comment]
This bug (for `ru` locale) reproduced only If the current day of the week is thursday, friday, saturday or sunday.

Final reproduce:
1. Open http://momentjs.com/
2. Execute in console:
```js
var locales = $('[data-locale]').map(function(index, item) {
  return item.dataset.locale;
}).toArray();

locales.forEach(function(locale) {
  moment.locale(locale);

  var w1 = moment().startOf('week');
  var w2 = moment(w1).add(1, 'w');
  var equal = 0;

  for (var i = 0; i < 7; i++) {
    var cond1 = moment(w1).add({d: i}).calendar();
    var cond2 = moment(w2).add({d: i}).calendar();

    if (cond1 == cond2) {
      equal++;
    }
  }

  if (equal != 0) {
    console.log(locale, equal);
  }
});
```

**Comment by Oire** [comment]
Seems quite good.

**Comment by ichernev** [comment]
@Oire so the fix is good?
@vsn4ik can you please change the tests so they don't copy paste the code from the locale file. Tests should be easier to read. You can add less-than-all of the cases, but put them explicitly, without functions / indirections.

**Comment by ichernev** [comment]
Merged in 1f6310e337492cfb8b023d121ec7f806a4d57300

**Pull request closed without merging**
