### PR TITLE
Same length for weekdaysMin parts (Italian)

### PR DESCRIPTION
**Pull request by massic80**
I'm making timetables with weekdaysMin particles, but they look weird, since not all the days are same-sized.
I'm making all of them two-chars long.

### CODE REVIEW

**Comment by ichernev** [comment]
@nostalgiaz is this acceptable?
@massic80 can you please rebase to latest develop?

**Comment by massic80** [comment]
@ichernev I'm not very familiar with GitHub and its naming conventions: I suppose "rebase" means "restart the pull request", and I'm asking whether to do it when discussion ends ;)

**Comment by nostalgiaz** [comment]
@ichernev yes, it is.

**Comment by ichernev** [comment]
@massic80 we changed heavily the directory structure, you can redo the changes in src/locale/it.js and also modify the tests in `src/test/locale/it.js`.

**Comment by mj1856** [comment]
@massic80 - Please update.  Tests need to pass and modifications need to be made per @ichernev's comment above.

For details on rebasing, read https://help.github.com/articles/about-git-rebase/

Thanks.

(Will close if no response.)

**Comment by massic80** [comment]
Sorry, I couldn't find time to re-check it all, and moreover I'm not Polish, thus mine was just a proposal ;)

**Comment by mj1856** [comment]
@massic80 - you mean Italian, right?  :wink: 

Thanks anyway.

**Comment by massic80** [comment]
Yes, I am :) I'd prefer some Polish to tell me whether the modification is appropriate or not

**Comment by massic80** [comment]
Whooops, this was for Italian :O
l did the same for Polish, I didn't remember this... Sorry, I can really rebase it :)

**Pull request closed without merging**
