### PR TITLE
[locale] bs hr me sl sr sr-cyrl: Change 'DD. MM. YYYY' to 'DD.MM.YYYY' in L

### PR DESCRIPTION
**Pull request by shaishavgandhi05**
First time making a PR for moment and I tried to follow the contributing guidelines as much as possible. Since #3329 changed format, the PR failed those tests. Is there a need to rewrite those tests so that the new convention is followed? Thanks

Signed-off-by: shaishavgandhi05 <shaishgandhi@gmail.com>

### CODE REVIEW

**Comment by mj1856** [comment]
Yes, you should include changes to the tests in this same PR, such that the automatic checks by Travis CI pass.

**Comment by shaishavgandhi05** [comment]
Added changes to tests and resubmitted.

**Comment by ichernev** [comment]
@frontyard any commens on this?

**Comment by ichernev** [comment]
I'm sorry, its already CLDR approved @frontyard -- ignore my post.

**Comment by ichernev** [comment]
Merged in cbc3621cd99ff5e016041c9c8f544e8df90836c1

**Comment by loudandwicked** [comment]
This change is wrong for sl locale. Correct format is the old 'DD. MM. YYYY' one, and even more correct would be 'D. M. YYYY'. Details (in Slovenian): [http://www.leemeta.si/blog/slovenski-pravopis/kako-pravilno-zapisemo-datum-v-slovenscini](http://www.leemeta.si/blog/slovenski-pravopis/kako-pravilno-zapisemo-datum-v-slovenscini)

**Comment by frontyard** [comment]
You could change just the sl locale. I belive bs, hr, me and sr shouldn't have spaces. 





On Wed, Sep 28, 2016 at 12:33 PM +0100, "loudandwicked" <notifications@github.com> wrote:












This change is wrong for sl locale. Correct format is the old 'DD. MM. YYYY' one, and even more correct would be 'D. M. YYYY'. Details (in Slovenian): http://www.leemeta.si/blog/slovenski-pravopis/kako-pravilno-zapisemo-datum-v-slovenscini

**Comment by loudandwicked** [comment]
I can't tell about other languages from former Yugoslavia since I'm only native in Slovene, but it seems at least Croatian language has the same rules for dates as Slovene. [http://www.lingua-soft.hr/blog/kako-pravilno-napisati-datum-na-razlicitim-jezicima](http://www.lingua-soft.hr/blog/kako-pravilno-napisati-datum-na-razlicitim-jezicima)

**Pull request closed without merging**
