### PR TITLE
[locale] de, de-at, de-ch: add german translation for week

### PR DESCRIPTION
**Pull request by carlmrichter**
Issue: when adjusting thresholds for humanize, Moment.js displays english version for 'week' only

For example:
```
moment.locale('de');
moment.duration(604800000).humanize({ h: 24, d: 7, w: 4 });  // 604800000 = 7 days 
```
results to:
```
'a week'
```
instead of
```
'eine Woche'
```
This works for days, hours, etc. but not for weeks.
This PR adds translation for 'week' in german locales for relative time formats to address this issue.

Original author of languages: @lluchs

### CODE REVIEW

**Comment by marwahaha** [comment]
@carlmrichter  - thank you for this PR. Could you also add some tests?

@Oire can you review this?

**Comment by marwahaha** [comment]
or @sschueller can you review?

**Comment by carlmrichter** [comment]
> @carlmrichter - thank you for this PR. Could you also add some tests?

@marwahaha I hope the last commit is what you're looking for. I found no tests for duration.humanize's thresholds at all, even in `en` locale ...

**Comment by marwahaha** [comment]
This is great!

**Pull request merged**
