### PR TITLE
[new locale] kab: Kabyle language

### PR DESCRIPTION
**Pull request by belkacem77**
Manage months and days names, long and short format, time format.... for the Kabyle locale.

### CODE REVIEW

**Comment by ichernev** [comment]
https://github.com/moment/moment/blob/develop/CONTRIBUTING.md#code-organization

**Comment by marwahaha** [comment]
@belkacem77 - Thank you for your contribution. 

Please do the following:
* copy this file to src/locale/kab.js
* Copy the file src/test/locale/en-gb.js into a new file src/test/locale/kab.js. Translate everything into Kabyle.

Let me know how you're doing. You can send me an email at marwahaha@berkeley.edu if you're having trouble.

**Comment by marwahaha** [comment]
@belkacem77 - are you still working on this ?

**Comment by belkacem77** [comment]
@marwahaha 
Sorry for being off. I was busy.
I updated this file and sent the /src/locale/kab.js . Please refer to PR  #4688

**Comment by marwahaha** [comment]
Closing as duplicate of #4688

**Pull request closed without merging**
