### PR TITLE
[locale] (br) Breton move from 12-hour to 24-hour notation

### PR DESCRIPTION
**Pull request by jbleduigou**
Implementing https://github.com/moment/moment/issues/4974

### CODE REVIEW

**Comment by kylekatarnls** [comment]
No doubt this is more correct than current translation, since there is no reason for "e" after hour and ":" after minute in "h[e]mm:ss A".

And it seems logical to use French format for Breton dialect. We should fix it in https://github.com/briannesbitt/Carbon too.

**Comment by jbleduigou** [comment]
Any updates on this pull request?

**Comment by jbleduigou** [comment]
@marwahaha is this pull request ready for merging?

**Comment by jbleduigou** [comment]
Hi @marwahaha is any work required to make this pull request ready for merging?

**Comment by jbleduigou** [comment]
Hi @ichernev is any work required to make this pull request ready for merging?

**Comment by marwahaha** [comment]
Thanks for the change and your persistence. When I have some time to make a release this will be available.

**Comment by jbleduigou** [comment]
Thanks a lot!

**Pull request merged**
