### PR TITLE
[locale] en-au: Sunday is changed as  first day of week

### PR DESCRIPTION
**Pull request by vigneshwar33**
[bugfix]-locale en-au: Sunday is changed as  first day of week Issue #4349

### CODE REVIEW

**Comment by ichernev** [comment]
@jarcoal what do you think?
@vigneshwar33  can you proof that this change is indeed correct (official source of first-day-of-week)?

**Comment by marwahaha** [comment]
See https://github.com/moment/moment/issues/4349

**Comment by marwahaha** [comment]
https://github.com/unicode-cldr/cldr-core/blob/36.0.0/supplemental/weekData.json#L72

**Comment by jmattsson** [comment]
As an Aussie, this change completely threw me (and the system relying on this package). I am not aware of any business which considers Sunday to be the start of the week down here.

**Comment by jmattsson** [comment]
Also, I believe "AS ISO 8601-2007" specifies that Monday is officially the start of the week down here. See e.g. https://www.standards.org.au/standards-catalogue/sa-snz/communication/it-027/as--iso--8601-2007

**Pull request merged**
