### PR TITLE
[locale] bg: Improve cardinal nouns

### PR DESCRIPTION
**Pull request by StoyanDimitrov**
Fixed cardinal noun. Sigh…

### CODE REVIEW

**Comment by StoyanDimitrov** [comment]
@ichernev, will you take a look at this change please?

**Comment by StoyanDimitrov** [comment]
Well, I managed to make pretty nice little mess here. @kraz, can you fix some of it for me please?

**Comment by ichernev** [comment]
Looks good, just remove the `locale/bg.js` from this change (it is autogenerated).

**Comment by ichernev** [comment]
Merged in 01e59f213b1c82d274f40ba10cb01274795d6183

**Pull request closed without merging**
