### PR TITLE
[new locale] gu: Added Gujarati Locale

### PR DESCRIPTION
**Pull request by Kaushik1987**
Added Gujarati Locale for Indian language "Gujarati".

### CODE REVIEW

**Comment by narainsagar** [comment]
@Kaushik1987 FYI: You do not need to commit `min/` dir. 
Please read the contributing guidelines carefully.

**Comment by Kaushik1987** [comment]
@narainsagar thx for your comment, Actually this is my first time i m pushing to some git repo. Could u guide me further for adding my changes properly.

**Comment by narainsagar** [comment]
@Kaushik1987 You can look into my PR here: https://github.com/moment/moment/pull/3659

FYI. For your PR to be published. You have to follow this rules:
- Create locale source file under `src/locale/`
- write unit tests for your locale under `src/test/locale/` (make sure you keep the names same on both sides)
- run the unit tests and make sure all unit tests passes..
- just push your code (only those files under `src/locale/`) 

For more read this contributing guidelines from here: https://github.com/moment/moment/blob/develop/CONTRIBUTING.md

**Comment by marwahaha** [comment]
@Kaushik1987 If you need help with this, please feel free to message me.

**Comment by Kaushik1987** [comment]
@marwahaha I have created new locale file for Gujarati and it;s working fine for me. But I not sure how to deal with test cases and pass unit test.

**Comment by ichernev** [comment]
@Kaushik1987 just copy a test from src/test/locale and translate it. Then run grunt to make sure it passes.

**Comment by marwahaha** [comment]
@Kaushik1987 You're on the right track.

* Copy the file `src/locale/en-gb.js` into a new file `src/locale/gu.js`. Translate everything into Gujarati.
* Copy the file `src/test/locale/en-gb.js` into a new file `src/test/locale/gu.js`. Translate everything into Gujarati. 
* Go to the command line, navigate to this project, and run `grunt`. All the tests should pass.

Let me know how you're doing. You can send me an email at `marwahaha@berkeley.edu` if you're having trouble.

**Comment by marwahaha** [comment]
@Kaushik1987 how's it going?

**Comment by Kaushik1987** [comment]
@marwahaha TBH after getting lots of error on other test cases (from other files, including me ) I left the hope.

**Comment by marwahaha** [comment]
@Kaushik1987 if you'd like, we can chat online or do a videocall to help you get this done. I think this is an important contribution for MomentJS.

**Comment by Kaushik1987** [comment]
@marwahaha that's really awesome mate, I will contact you so that we can finalize some time to get it done. really appreciate your help.

**Comment by Kaushik1987** [comment]
@marwahaha Finally I am done with implementation for Gujarati locale, Now I have small issue if you can help me in it.   [https://stackoverflow.com/q/44451004/3264939 ](https://stackoverflow.com/q/44451004/3264939)

**Comment by marwahaha** [comment]
@Kaushik1987  - It would be great to add this, but please follow the steps I have mentioned.

**Comment by Kaushik1987** [comment]
@marwahaha can u explain what I need to do. A personal chat or email is preferable.

**Comment by marwahaha** [comment]
@Kaushik1987 - if you are still having trouble, you can email me at marwahaha@berkeley.edu

**Comment by Kaushik1987** [comment]
Sure, But nowaday loaded with lot's of work. However Thanks for asking,

**Comment by Kaushik1987** [comment]
@marwahaha can we connect this weekend to fix any issue in Gujarati locale ?

**Comment by kumarharsh** [comment]
@marwahaha this PR can be closed - Gujarati is already [there](https://github.com/moment/moment/blob/develop/locale/gu.js), and this PR itself doesn't change any source files.

**Comment by marwahaha** [comment]
Sounds good, thanks @kumarharsh

**Pull request closed without merging**
