### PR TITLE
Mongolian locale for momentJS

### PR DESCRIPTION
**Pull request by Zorig**

### CODE REVIEW

**Comment by skfd** [comment]
To add new locale you need to put them into `/src/locale/` and tests into `/src/test/locale`. Check other languages for examples.

It's not obvious, but `/locale` folder is for build files not source files.

**Comment by ichernev** [comment]
@Zorig any progress on this?

**Comment by Zorig** [comment]
@ichernev yes, lately been very busy gonna do it

**Comment by maggiepint** [comment]
Closing. Feel free to re-open if tests pass.

**Pull request closed without merging**
