### PR TITLE
Feature - Round to a unit by a given offset

### PR DESCRIPTION
**Pull request by triqi**
Round up, down or to the nearest unit.

Usage: moment.roundTo(units, [offset, midpoint])

m.roundTo('minute', 15); // Round the moment to the nearest 15 minutes.
m.roundTo('minute', 15, 'up'); // Round the moment up to the nearest 15 minutes.
m.roundTo('minute', 15, 'down'); // Round the moment down to the nearest 15 minutes.

### CODE REVIEW

**Comment by nrvs** [comment]
:+1: for this, let me know if I can be of any help :smile:

**Comment by tannerlinsley** [comment]
:+1: , Need this!!! :)

**Comment by ichernev** [comment]
I'll look into this, but for sure:
* `roundTo(value, unit, 'up' | 'down')` (reorder first two args)
* zero out smaller units
* if your round up across higher boundary -- make it 0 (like `5:55` minutes, `roundTo(7, 'minutes', 'up')` should give `6:00`). If we do 6:03 (63 minutes after 5), then another `roundTo` with the same arguments would change it further (as if it wasn't rounded the first time).
* if you round with big values (like 90 minutes), round to higher unit (like hour in this case). There are too many interpretations and cases for this to work well otherwise.

**Comment by vitrilo** [comment]
+1

**Comment by andrewboni** [comment]
+1

**Comment by iwatakeshi** [comment]
Instead of naming it `roundTo`, why not name it `ceil` and `floor`. I would understand it better that way especially because it's in terms of moment (data/time).

**Comment by wackawacka** [comment]
could easily just have helper functions, so you'd have the main roundTo
function which takes in "ceil" or "floor" and then the ceil function just
calls roundTo with "ceil" and floor calls it with "floor"

**Comment by alfg** [comment]
+1

**Comment by pascalgross** [comment]
+1

**Comment by gerritvanaaken** [comment]
+1

**Comment by matiaslarsson** [comment]
+1

**Comment by stereonom** [comment]
+1

**Comment by joe-schorn** [comment]
+1

**Comment by rlweb** [comment]
+1

**Comment by Quji** [comment]
+1

**Comment by YPCrumble** [comment]
:+1:

**Comment by samcic** [comment]
+1

**Comment by bzifkin** [comment]
+1

**Comment by itrethan** [comment]
+1

**Comment by WebDevTmas** [comment]
I just made a plugin for this at https://github.com/WebDevTmas/moment-round
I'll adjust it to be native to momentjs sometime this week, Matt pointed out to ma this feature had been requested before.

My api is as follow

```
moment().round(5, 'minutes');
moment().ceil(3, 'hours');
moment().floor(15, 'seconds');
```

Rounding is only possible to hours, minutes and seconds.
Later I would work on 'day', but I'm not sure to what day, day of year? day of month? day of week?
Is all needed?

**Comment by jgrigg** [comment]
+1

**Comment by bensinclair** [comment]
+1

**Comment by niemyjski** [comment]
+1

**Comment by bensinclair** [comment]
@WebDevTmas I'd love to round to the start of a month

**Comment by WebDevTmas** [comment]
@bensinclair That's already possible with startOf('month')

**Comment by rfink** [comment]
So much +1

**Comment by Zugwalt** [comment]
+1

**Comment by kichooo** [comment]
+1

**Comment by mj1856** [comment]
This PR needs to be revised to match the current ES6 module-based design.

**Comment by acrolink** [comment]
+1

**Comment by davidpatters0n** [comment]
+1

**Comment by bhsnll** [comment]
+1

**Comment by bbtb1982** [comment]
+1

**Comment by nodesocket** [comment]
:+1:

**Comment by leonn** [comment]
+1

**Comment by samcc1** [comment]
+1

**Comment by barcelona23** [comment]
+1

**Comment by xpepermint** [comment]
+1

**Comment by andyyou** [comment]
+1

**Comment by niemyjski** [comment]
Will this ever get merged in?

**Comment by icambron** [comment]
Closing for age/lack of action. If someone wants to rebase this, fix whatever's left to do, and resubmit, that's cool.

**Comment by heruan** [comment]
This issue was a little dispersive… has Moment the ability to round a unit to a given value (e.g. minutes to 15, 30 or 45) which is not possible with `startOf`?

**Comment by butterflyhug** [comment]
@heruan Not currently.  If someone decided to revive this idea in a new PR, that should address your use case.

**Comment by tecnocat** [comment]
+1

**Comment by julestruong** [comment]
+1

**Comment by wolfgang42** [comment]
@triqi I'm trying to update your code so it works with the latest version of moment. (Once I do this a PR will be forthcoming.) However I'm having some trouble with the unit tests not passing:

```
Testing round_to.jsF
>> roundTo - round to nearest unit
>> Message: millisecond should round up to 12
>> Error: 10 == 12
>> at Object.exports.roundTo.round to nearest unit (test\moment\round_to.js:17:14)
>> at Object.exports.roundTo.setUp (test\moment\round_to.js:8:9)

>> roundTo - round to nearest unit
>> Message: day should round up to 10
>> Error: 5 == 10
>> at Object.exports.roundTo.round to nearest unit (test\moment\round_to.js:33:14)
>> at Object.exports.roundTo.setUp (test\moment\round_to.js:8:9)

>> roundTo - round to nearest unit
>> Message: day should round down to 6
>> Error: 0 == 6
>> at Object.exports.roundTo.round to nearest unit (test\moment\round_to.js:34:14)
>> at Object.exports.roundTo.setUp (test\moment\round_to.js:8:9)
```

What am I missing here? The values it's outputting seem more correct than the unit test.

**Comment by triqi** [comment]
@wolfgang42, this PR has been closed and is no longer active. Alternatively, there is a [plugin here](https://github.com/moment/momentjs.com/issues/211) or a new [PR here](https://github.com/moment/moment/pull/2848) that's trying to do the same thing.

**Comment by Mohammed-El-Nabulsi** [comment]
Just in case someone needs this, here's a small solution that should fit most needs and could just simply be included in ones own project:

```javascript
roundDate: function(date, type, offset) {   
   let val = date[type]();  
   let roundedVal = Math.ceil((val+1)/offset)*offset;  
   return date[type](roundedVal);  
}
```

**Comment by padsbanger** [comment]
+1

**Comment by michplunkett** [comment]
+1

**Comment by kevlarr** [comment]
+1 for this, given that every time someone posts a "solution" (in this and other PRs/issues) they are generally wrong

@Mohammed-El-Nabulsi 's rounds up only - with a minute of 34, it should round *down* to nearest 15, not up.

**Comment by sandorvasas** [comment]
+1

**Comment by 1x0** [comment]
+1

**Comment by refineddigital** [comment]
maybe this may help someone
https://momentjs.com/docs/#/plugins/round/

**Comment by cmawhorter** [comment]
^== the round plugin refineddigital links is abandoned

**Comment by piotrpasich** [comment]
+1

**Comment by ux-engineer** [comment]
+1

**Comment by ux-engineer** [comment]
`const nextFirstDayOfMonth = moment(myDate, 'DD.MM.YYYY').startOf('month').format('DD-MM-YYYY');`

**Pull request closed without merging**
