### PR TITLE
Fix PL locale months parsing

### PR DESCRIPTION
**Pull request by szwacz**
Fix for https://github.com/moment/moment/issues/2275
Is a little hacky, but this is still the sanest way of solving this issue I have found.

### CODE REVIEW

**Comment by szwacz** [comment]
Are you interested in merging my PR? Should I make it compatible with new version of moment?

**Comment by ichernev** [comment]
Sure, I'll merge this in if you port it to ES6. Sorry for the inconvenience.

@evoL what do you think?

**Comment by evoL** [comment]
Sure, I agree that both forms should be parsable. :+1: 
Thanks for this PR!

**Comment by szwacz** [comment]
Done! Ready to merge.

**Comment by ichernev** [comment]
Merged in e9807f551587e6d0829af24cf171734c5cf8f69b

**Pull request closed without merging**
