### PR TITLE
[locale] (sk) Fix preposition issue (fixes #5408)

### LINKED ISSUE #5408: `sk.js`: Fix l10n issues (czechisms)
**Describe the bug**

The preposition `za` in the sense of `in` in `in a minute` is a czechism (a word or usage borrowed from the Czech language), therefore the `moment`’s `za pár sekúnd` is correct in Czech, and incorrect in Slovak. In Slovak, the correct preposition is `o` in the phrase.

**Expected behavior**

For example: use `o pár second` instead of `za pár sekúnd` (meaning: `in a few seconds`).

---

~~**Update:** Another issue is the `pred 3 dny` which should be `pred 3 dňami`.~~ Not an issue of `moment`, but of `dayjs`, my bad.

### PR DESCRIPTION
**Pull request by tukusejssirs**
- Replace `za` preposition with `o` in `src/locale/sk.js` and `src/test/locale/sk.js`.

### CODE REVIEW

**Comment by tukusejssirs** [comment]
I have already signed the CLA, but the `licence/cla` does not recognise it for some reason.

**Comment by tukusejssirs** [comment]
The first four of six Travis build tests pass.

The [4700.5](https://travis-ci.org/github/moment/moment/jobs/661629839?utm_medium=notification&utm_source=github_status) test fails in `npm install`.

The [4700.6](https://travis-ci.org/github/moment/moment/jobs/661629840?utm_medium=notification&utm_source=github_status) test fails in `grunt build:travis`.

I cannot fix neither of the above issues.

When this PR is merged, the iamkun/dayjs#833 could be merged, and consequently romcal/romcal#186 will be fixed.

**Comment by ichernev** [comment]
@k2s @petrbela any comments on this?
@tukusejssirs can you provide some proof that this change is indeed correct?

**Comment by k2s** [comment]
@ichernev It depends, but this pull request is breaking change.

Booth is correct:
* I will write this answer in 5 minutes = o 5 minút
* I wrote it in 5 minutes = za 5 minút

If it is possible in `moment` to provide context, then the translation should support booth prepositions, otherwise `za` needs to be replaced in the result with `o` by programmer. Existing code will break code that already does this.

authoritative reference for Slovak language that booth is correct based on context:

* https://jazykovaporadna.sme.sk/q/1183/
* https://jazykovaporadna.sme.sk/q/9030/

**Comment by tukusejssirs** [comment]
@k2s is right, I’ve missed the _done in n minutes_ case.

Just in case someone who does not understand/speak Slovak reads this, [this link](https://jazykovaporadna.sme.sk/q/1183/) (first link from the [comment](https://github.com/moment/moment/pull/5409#issuecomment-618482801) by @k2s) says that:
- `za` is used when we talk about a _period_ during which something is done (like _He cooked it in an hour._);
- `o` is used when we talk about a _point in time_ (like _She’s back in a minute._).

**Comment by ichernev** [comment]
@tukusejssirs just do updateLocale in your own project, and you should be good to go: https://momentjs.com/docs/#/customization/relative-time/

@k2s thank you!

**Comment by dakujem** [comment]
Any way to solve this if I wish to use `o` in reference to future time? Call me a nazi, though it simply is incorrect and I wish to display a correct string.

**Comment by k2s** [comment]
> Any way to solve this if I wish to use `o` in reference to future time? Call me a nazi, though it simply is incorrect and I wish to display a correct string.

`.replace('za', 'o')`
I am not aware about any exception where this would not work.

**Comment by dakujem** [comment]
Buy a red car then have it painted blue.  🙄

**Pull request closed without merging**
