### PR TITLE
Fixed Latvian locale - 'After 211 years'

### PR DESCRIPTION
**Pull request by Knagis**

### CODE REVIEW

**Comment by ichernev** [comment]
@skakri @JanisE what do you think?

**Comment by JanisE** [comment]
The fix looks correct. Related test cases should probably be added.

**Comment by Oire** [comment]
@Knagis, please add some tests and this will go to the next release.

**Comment by Knagis** [comment]
I added few test cases however the CI build seems to be failing due to its own issues, not the changes.

**Comment by ichernev** [comment]
Merged in 4f347ef47c35a11d502c73d46ea34433f18a674e

**Pull request closed without merging**
