### PR TITLE
Add Mongolian language locale to moment.js

### PR DESCRIPTION
**Pull request by digz6666**

### CODE REVIEW

**Comment by ichernev** [comment]
Please follow https://github.com/moment/moment/blob/develop/CONTRIBUTING.md
Add `src/locale/mn.js` and `src/test/locale/mn.js` (you forgot the tests altogether).

**Comment by digz6666** [comment]
@ichernev ok, I will add tests :)

**Comment by ichernev** [comment]
@digz6666 any progress?

**Comment by ichernev** [comment]
@digz6666 you need add modify `src/locale/mn.js` and add `src/test/locale/mn.js`, note that the format has changed a bit.

Closing for inactivity, feel free to reopen with new changes.

**Pull request closed without merging**
