### PR TITLE
Update th.js

### PR DESCRIPTION
**Pull request by elfet**
In Thai people use 24 hour time format. Not `H hours m minutes s seconds`.

### CODE REVIEW

**Comment by mj1856** [comment]
Thanks, but please read the [contributing guidelines](https://github.com/moment/moment/blob/develop/CONTRIBUTING.md), then edit the `src/locale/th.js` and `src/test/locale/th.js` files instead.

@sirn - please confirm the change is appropriate for Thai.  thanks.

**Comment by mj1856** [comment]
Also, is `H:m:s` correct, or should there be leading zeros? `HH:mm:ss` or `H:mm:ss`, etc.

**Comment by sirn** [comment]
Yup, the change looks good to me. Although I think it needs to be `H:mm` and `H:mm:ss` because I have never seen anyone wrote `7:1` (vs `7:01`)

**Comment by elfet** [comment]
Done.

**Comment by mj1856** [comment]
@elfet - Thanks, but the changes need to be made in `src/locale/th.js`, not `locale/th.js`.   The `locale/th.js` is auto-generated during the build process.

When done, please rebase to squash all changes into one commit.  Thanks.

**Comment by Oire** [comment]
@elfet, any progress on this? And btw, now the tests are failing. Please correct and rebase. Thanks!

**Comment by elfet** [comment]
Done. Why not add `locale` dir to .gitignore? Is it needed only in npm?

**Comment by Oire** [comment]
@elfet, the tests are still failing because you haven't corrected everything yet: please see this part starting with `test('calendar day', function (assert)`

**Comment by maggiepint** [comment]
@elfet we are closing this pull request as it has been sitting for quite a while. If you make the changes we requested, we are more than happy to re-open it. Thanks for contributing.

**Pull request closed without merging**
