### PR TITLE
[new locale] gom-deva: Add Konkani Devanagari script

### PR DESCRIPTION
**Pull request by WikiDiscoverer**
Add source and test files for a new locale gom-deva

### CODE REVIEW

**Comment by WikiDiscoverer** [comment]
@marwahaha , please could you merge this? Thanks.

**Comment by WikiDiscoverer** [comment]
@marwahaha , please could you merge this? Thanks.

**Comment by ichernev** [comment]
@WikiDiscoverer I'm sorry, this locale doesn't use words, only numbers? And month names are empty?

**Comment by ichernev** [comment]
Merged in 849f5c01c594cfba5c11e12f18874e9872268393

**Comment by ichernev** [comment]
I get it, my browser doesn't support fancy characters, at least my editor shows squares :)

Thank you @WikiDiscoverer

**Pull request closed without merging**
