### PR TITLE
[bugfix] Fixes #3805, fix locale month getters for standalone/format cases

### LINKED ISSUE #3805: localeData().months() or weekdays() throws exception or undefined in 14 locales
Previously reported [in this issue](https://github.com/moment/moment/issues/3629#issuecomment-280753639) but they're two separate issues.

`localeData().monthsShort()` appears to be broken for:

- `es`
- `es-do`
- `nl` 
- `nl-be`
- `fy`

Both `m` and `format` are undefined when getting the locale data:

```
    monthsShort : function (m, format) {
        if (/-MMM-/.test(format)) {
            return monthsShort[m.month()];
        } else {
            return monthsShortDot[m.month()];
        }
    }
```

### PR DESCRIPTION
**Pull request by timfish**
Should fix issue #3805

https://runkit.com/581ddb1783dafc001466d8e6/58bac4ef6fc4fc0014cc5b30/branches/master

### CODE REVIEW

**Comment by icambron** [comment]
This makes sense to me. Sounds like we should add a test that checks that each locale returns an array for `monthsShort`

**Comment by timfish** [comment]
I'm adding the following test to all 113 locales:
```
test('valid localeData', function (assert) {
    assert.equal(moment().localeData().months().length, 12, 'months should return 12 months');
    assert.equal(moment().localeData().monthsShort().length, 12, 'monthsShort should return 12 months');
    assert.equal(moment().localeData().weekdays().length, 7, 'weekdays should return 7 days');
    assert.equal(moment().localeData().weekdaysShort().length, 7, 'weekdaysShort should return 7 days');
    assert.equal(moment().localeData().weekdaysMin().length, 7, 'monthsShort should return 7 days');
});
```

Even after my fixes to `es` `es-do` `nl` `nl-be` `fy` there are 15 failing tests.
Have I opened a can of worms? 

```
Module: locale:be Test: valid localeData
months should return 12 months
Actual value:undefined
Expected value:12

Module: locale:be Test: valid localeData
weekdays should return 7 days
Actual value:undefined
Expected value:7

Module: locale:el Test: valid localeData
Died on test #1     at global.test.QUnit.test 
TypeError: Cannot read property 'substring' of undefined
    at Locale.months (C:\Users\tim\Documents\GitHub\moment\build\umd\locale\el.js:21:28)
    at Object.<anonymous> 

Module: locale:hr Test: valid localeData
months should return 12 months
Actual value:undefined
Expected value:12

Module: locale:hy-am Test: valid localeData
months should return 12 months
Actual value:undefined
Expected value:12

Module: locale:ka Test: valid localeData
months should return 12 months
Actual value:undefined
Expected value:12

Module: locale:ka Test: valid localeData
weekdays should return 7 days
Actual value:undefined
Expected value:7

Module: locale:lt Test: valid localeData
months should return 12 months
Actual value:undefined
Expected value:12

Module: locale:lt Test: valid localeData
weekdays should return 7 days
Actual value:undefined
Expected value:7

Module: locale:pl Test: valid localeData
Died on test #1     at global.test.QUnit.test (C:\Users\tim\Documents\GitHub\moment\node_modules\qunit\lib\child.js:146:21)
...    at tryModuleLoad (module.js:446:12): Cannot read property 'month' of undefined
TypeError: Cannot read property 'month' of undefined

Module: locale:ru Test: valid localeData
months should return 12 months
Actual value:undefined
Expected value:12

Module: locale:ru Test: valid localeData
monthsShort should return 12 months
Actual value:undefined
Expected value:12

Module: locale:ru Test: valid localeData
weekdays should return 7 days
Actual value:undefined
Expected value:7

Module: locale:uk Test: valid localeData
months should return 12 months
Actual value:undefined
Expected value:12

Module: locale:uk Test: valid localeData
Died on test #3     at global.test.QUnit.test (C:\Users\tim\Documents\GitHub\moment\node_modules\qunit\lib\child.js:146:21)
...    at tryModuleLoad (module.js:446:12): Cannot read property 'day' of undefined
```

**Comment by timfish** [comment]
`localeData` should be querying the locales via an extra layer rather than having to include the logic in the individual locales.

**Comment by timfish** [comment]
I've got all the tests passing but it might not be the ideal long term solution. At least now all locales return months and days.

All the changed locales will need checking to ensure I've returned the correct tenses/cases for the months/days.

`month.js` already contained:
```
export function localeMonths (m, format) {
    if (!m) {
        return this._months;
    }
    return isArray(this._months) ? this._months[m.month()] :
        this._months[(this._months.isFormat || MONTHS_IN_FORMAT).test(format) ? 'format' : 'standalone'][m.month()];
}

export function localeMonthsShort (m, format) {
    if (!m) {
        return this._monthsShort;
    }
    return isArray(this._monthsShort) ? this._monthsShort[m.month()] :
        this._monthsShort[MONTHS_IN_FORMAT.test(format) ? 'format' : 'standalone'][m.month()];
}
```

So if we could get the `localeData` loading through those it would have worked without changing the locales. It's certainly in need of some refactoring.

**Comment by ichernev** [comment]
@timfish wait a sec. First -- why don't you just fix the generic function, not rewrite standalone/format the primitive way. `src/lib/unit/month.js` : `localeMonths`, `localeMonthsShort`, `src/lib/unit/day-of-week.js` : `localeWeekdays`, `localeWeekdaysShort`, `localeWeekdaysMin`.

Second -- if you need to do something on all locales, use `src/test/helpers/common-locale.js`.

**Comment by timfish** [comment]
Easy when you know how!

**Comment by ichernev** [comment]
@timfish thank you, looks great!

**Comment by ichernev** [comment]
Merged in 1d70961e1045b9cbf7ef83f0e403091bf14b7ff1

**Pull request closed without merging**
