### PR TITLE
Russian locale: capitalized first cahracters in names, fix #2569

### LINKED ISSUE #2569: Russian locale: capitalized first cahracters in names
Why month and weekday names are in lower case in `ru` locale, not with capitalized first character (like in other locales and anoter datepickers, Windows calendar etc)?
For example, `Январь`, `Понедельник` and `Пн` is more habitual for calendar than `январь`, `понедельник` and `пн`.
First of all, question is for @Viktorminator, author of locale file.
Can I make a PR to fix this?

### PR DESCRIPTION
**Pull request by RomeroMsk**
Russian locale: capitalized first cahracters in names

fixes: #2569

### CODE REVIEW

**Comment by ichernev** [comment]
@Oire what do you think?

**Comment by ichernev** [comment]
Link to document with proof: http://lh.2xlibre.net/locale/ru_RU/

**Comment by ichernev** [comment]
Merged in 7592c8d046c3e9703444d193482b547e63b3661a

**Comment by RomeroMsk** [comment]
Thanks!

**Pull request closed without merging**
