### PR TITLE
fixing day sequence to match the real day

### PR DESCRIPTION
**Pull request by kifcaliph**
changed from src
we need to fix the day sequence to match the real day and not just visually. the problem is the calendar appears to be like 
August 2016
Fr    Sa    Su    Mo    Tu    We    Th
31    1     2       3      4      5      6

Friday is supposed to be the 5th of the month

### CODE REVIEW

**Comment by butterflyhug** [comment]
Looks good, thanks!  Could you also fix the tests?

**Comment by ichernev** [comment]
@butterflyhug @kifcaliph wait a sec.

dow means which day of the week is first. If Friday is the beginning of the week, it should be 5.
doy is another beast:
```javascript
    var // first-week day -- which january is always in the first week (4 for iso, 1 for other)
        fwd = 7 + dow - doy,
```

Which gives `doy = 7 + dow - fwd`, so fwd is normally 1, except ISO, where it is 4. So it becomes `doy = 6 + dow`. So if doy is 5 then doy needs to be 11.

**Comment by ichernev** [comment]
@kifcaliph @butterflyhug any thoughts on this?

**Comment by butterflyhug** [comment]
@ichernev So, `dow=5` and `doy=11`?  Yeah, I think that sounds right.  I confess I always find that `doy` setting messes with my head a bit.

**Comment by ichernev** [comment]
@butterflyhug yes, it shuld be `dow/doy = 5/11`.

**Comment by ichernev** [comment]
But is the start of week Friday or Sunday?

**Comment by ichernev** [comment]
Close in favor of #3543

**Pull request closed without merging**
