### PR TITLE
add maori (mi-nz)

### PR DESCRIPTION
**Pull request by johnideal**

### CODE REVIEW

**Comment by maggiepint** [comment]
Generally this is fine, but the comments need to have your name in them as the author. In the future, if people wish to make changes to this locale, we will ping you on github to approve those changes, as we don't speak this language. See the other locale files for the expected format. We do use a script to automatically parse locale information, so please keep the spacing/punctuation the same.

**Comment by johnideal** [comment]
Thanks @maggiepint I'll make the change and push it up.

**Comment by mj1856** [comment]
@johnideal - Please make the minor change to add your info in the comments.  See the other locale files for examples.  Thanks.

**Comment by johnideal** [comment]
Sorry for the delay, added contact info.

**Comment by ichernev** [comment]
Merged in ae03e51

**Pull request closed without merging**
