### PR TITLE
[misc] Add module in addition to jsnext:main in package.json

### PR DESCRIPTION
**Pull request by howel52**
maybe wee don't need jsnext:main any more
see [discussion](https://www.reddit.com/r/javascript/comments/5jwg9c/confused_about_fields_module_and_jsnextmain_in/)

### CODE REVIEW

**Comment by howel52** [comment]
cc @marwahaha

**Comment by ichernev** [comment]
@howel52 just don't touch the changelog. You cant retroactively change an old changelog ... it is generated on release.

**Comment by ichernev** [comment]
Merged in 0d0eabd9a50c2ccb3e0818798abcab3ae86339e9

**Comment by ichernev** [comment]
I didn't remove the jsnext:main property. It will certainly break somebody's workflow.

**Pull request closed without merging**
