### PR TITLE
[locale] br: Add meridiem translation and correct quotemark

### PR DESCRIPTION
**Pull request by o-Chamie-o**
eur e brezhoneg Lizherennañ

Mat eo g.m. evit PM (goude merenn) ha a.m. evit AM (a-raok merenn).

--
Should be g.m. for PM, stand for goude merenn and a.m. for AM stand for a-raok Merenn

Here some sources :
http://www.brezhoneg.bzh/177-divizou-hag-erbedadennou-ar-chuzul-skiantel.htm
https://www.unicode.org/cldr/charts/latest/summary/br.html

### CODE REVIEW

**Comment by jbleduigou** [comment]
Hi,

Thanks for contributing!

We actually moved away from the 12 hour notation.
See this PR: https://github.com/moment/moment/pull/4975

I don't know if it has been actually released?

**Comment by o-Chamie-o** [comment]
> it would help if you speak english :)

All translated on my comment. :) @ichernev 

Hum strange choice, @jbleduigou as I mentioned, the Unicode recommandation and the one from the OPAB ar 12 based.

I can double check this maybe ? :thinking:

**Comment by jbleduigou** [comment]
> Hum strange choice, @jbleduigou as I mentioned, the Unicode recommandation and the one from the OPAB are 12 based.
> 
> I can double check this maybe ? 🤔

I actually don't have strong opinions on this one.
It might make more sense to use 12 hours.

**Comment by ichernev** [comment]
@o-Chamie-o about the other changes -- they mostly revolve around this quote. Do people use these special characters when they type? If not then parsing will be completely broken (for reading in dates from user input).

**Comment by o-Chamie-o** [comment]
I true that, the parsing will be broken. :( As on the keyboard the single quote is used instead of the apostrophe.

Can we add option in the parser ? For both single quote and apostrophe maybe ?

**Comment by o-Chamie-o** [comment]
This should do the trick right ? @ichernev 
```
var monthsParse = [/^genver/i, /^c[ʼ\']hwevrer/i, /^meurzh/i, /^ebrel/i, /^mae/i, /^mezheven\/i, /^gouere/i, /^eost/i, /^gwengolo/i, /^here/i, /^du/i, /^kerzu/i];
var monthsShortParse = [/^gen/i, /^c[ʼ\']hwe/i, /^meu/i, /^ebr/i, /^mae/i, /^eve\/i, /^gou/i, /^eos/i, /^gwe/i, /^her/i, /^du/i, /^ker/i];
var weekdaysParse = [/^sul/i, /^lun/i, /^meurzh/i, /^merc[ʼ\']her/i, /^yaou/i, /^gwener\/i, /^sadorn/i,];
...
monthsParse : monthsParse,
monthsShortParse : monthsShortParse,
weekdaysParse  : weekdaysParse ,

```
Other advantage, we now support case incensitive case. ;)

**Comment by ichernev** [comment]
@o-Chamie-o well, yes. If we don't want to break existing code the parsing regexes should be more lenient.

**Comment by jbleduigou** [comment]
Hi,
Sorry for the delay, I have been fairly busy lately and didn't get a chance to review this PR.
I went through the links you provided.

Using a.m. and p.m. was definitely wrong.
Switching to 24 hours notation was an okay workaround.
But ultimately I believe that your suggestion with a.m and g.m. is better.

Thanks for contributing!

**Comment by o-Chamie-o** [comment]
No worries @jbleduigou :)

Thanks to you for the BR locale supporte in the first place. :)

**Comment by marwahaha** [comment]
@o-Chamie-o glad to hear you have approval from the locale author.
Could you please update with the latest code on `develop` branch and resolve conflicts?
If you need help with this let me know.
Then we can merge it!

**Comment by o-Chamie-o** [comment]
Arf some issues with the month parsing. :(

**Comment by marwahaha** [comment]
Oh no :( hope you can get it fixed!

**Comment by o-Chamie-o** [comment]
:pray: Thanks a bunch @marwahaha 
Mersi bras dit. :)

**Pull request merged**
