### PR TITLE
Changed September Abbreviation to "Sept" in locale-specific english files and default locale file

### LINKED ISSUE #2728: September should be abbreviated as Sept.
Currently `moment` uses Sep for the September abbreviation, but per the OED it should be Sept.

http://public.oed.com/how-to-use-the-oed/abbreviations/#s

### PR DESCRIPTION
**Pull request by mbad0la**
I hope this fixes #2728

### CODE REVIEW

**Comment by mj1856** [comment]
Please update tests to match.  Thanks.

**Comment by mbad0la** [comment]
@mj1856 Thanks for helping me out, this is my first pull request on Github so i'm kind of nervous and a bit clueless on the whole process. Please bear with me.
Thanks

**Comment by MartynDavis** [comment]
With this change what is the output of `moment("Sep 4 2010", "MMM D YYYY")`?  With and without strict mode.

**Comment by ichernev** [comment]
@MartynDavis we have to hack in `parseMonth`, `parseShortMonth` and `parseLongMonth` to work around that.
@mbad0la can you please take inspiration from `src/locale/ru.js` about the specialized parsing methods to allow both Sept and Sep as a representation when parsing.

**Comment by mbad0la** [comment]
@ichernev i'll give it look and try to do it.

**Comment by mbad0la** [comment]
@ichernev i'm failing strict parsing tests -
capital long-month + MMM
capital short-month + MMMM
lower long-month + MMM
lower-short month + MMMM
Is it because of the fact that all short month abbreviations have a fixed length of 3 whereas September can have either 3 or 4 letters in its abbreviation. Please help out.

**Comment by MartynDavis** [comment]
Personally, if I format my dates as "DD-MMM-YYYY" I want September to be "Sep" and not "Sept".

The world of computing has survived both http://public.oed.com/how-to-use-the-oed/abbreviations/#s and http://www.unicode.org/reports/tr35/tr35-31/tr35-dates.html#Date_Format_Patterns (which lists Sept as the abbreviation example, yet fails to provide a definitive list of month abbreviations).

strftime(), Java's SimpleDateFormat class, countless others, even Excel, all format abbreviated months as 3 letters for all months, for English.

There is a lot of precedence to have "September", when formatted as "MMM", return "Sep".

**Comment by ichernev** [comment]
@mbad0la the short and long should be more strict. The short should have `/^Sept?$/`, and long should be `/^September$/`, so that nothing can slip through. Also you need to add special tests to make sure that `Sep` will work no worse than `Sept` when it comes to (strict) parsing.

**Comment by mbad0la** [comment]
@ichernev where can i find all the possible formats and the function definition of strict parsing tests?

**Comment by ichernev** [comment]
Merged in 9ea2d6b1a86d59b36bce792771cffc3f85b382b0

**Comment by ljharb** [comment]
This seems like a breaking change, and not a minor one :-/

**Pull request closed without merging**
