### PR TITLE
Croatian months (hr) - corrected typo - months: sječanj to siječanj, and...

### PR DESCRIPTION
**Pull request by trebor74hr**
... vel. to velj. (lj can not be splitted). Reference https://hr.wikipedia.org/wiki/Kategorija:Mjeseci_u_godini

### CODE REVIEW

**Comment by ichernev** [comment]
Why are there so many ways to say January in this language ... In CLDR it is `sječanj`, but if I google it it converts it to the other one.

**Comment by trebor74hr** [comment]
Then it is wrong in CLDR, Croatian is my native language.

**Comment by bmarkovic** [comment]
Sorry I wasn't active on GH for awhile, will correct tests.

**Comment by ichernev** [comment]
This is already merged in develop

**Pull request closed without merging**
