### PR TITLE
Kyrgyz_kg locale support

### PR DESCRIPTION
**Pull request by Chyngyz**
Added Kyrgyz language support

### CODE REVIEW

**Comment by Oire** [comment]
@Chyngyz, thanks a lot! To me it seems perfect! I was surprised though that Kyrgyz month names are the same as Russian ones :).

**Comment by Chyngyz** [comment]
@Oire hey, thanks for accepting this, actually we have Kyrgyz translations for the month names, but people just don't use it (month names are long, they are two word names), especially on the web :)

**Comment by ichernev** [comment]
@Chyngyz thank you for contributing. According to the wiki page about Kyrgyz https://en.wikipedia.org/wiki/Kyrgyz_language the locale code is `ky` not `kg`. Can you please update the filename and locale abbreviation to match?

**Comment by Chyngyz** [comment]
@ichernev Sorry thanks for pointing this, changed to `ky`.

**Comment by ichernev** [comment]
Merged in ba6f5f3e6075d437256ee8ce0ad8d026c2b31a12

**Pull request closed without merging**
