### PR TITLE
[new locale] (oc-lnc) Occitan

### PR DESCRIPTION
**Pull request by marwahaha**
@Quenty31 can you review this? I made some changes because the test and source files did not match.

### CODE REVIEW

**Comment by Quenty31** [comment]
Looks okay to me :) Many thanks for the time you took to review this!

**Comment by Quenty31** [comment]
Hello @marwahaha ! When will this be shipped to a new version of moment? :)

**Comment by marwahaha** [comment]
Hi @Quenty31  , unfortunately I'm busy this week. But I can try to get to it next week.

**Comment by Mejans** [comment]
@marwahaha Hello! Any news about the integration of this locale?

**Pull request merged**
