### PR TITLE
[locale] zh: align relativeTime.future to CLDR 33

### PR DESCRIPTION
**Pull request by JLHwung**
see `future-other` section of https://www.unicode.org/cldr/charts/33/by_type/date_&_time.fields.html

### CODE REVIEW

**Comment by JLHwung** [comment]
@marwahaha Sorry for the long delay. Added test and ready for review.

**Comment by ichernev** [comment]
@suupic @zenozeng @ben-lin @hehachris @skfd @anthonylau @le0tan any notes on this? It looks like CLDR compliant, but still.

**Comment by le0tan** [comment]
They basically mean the same thing in Chinese. 

The slight difference is: previous one means something happens **within** a certain duration of time. The changed one means it happens **after** a certain duration of time. I personally think the purposed change better reflects the meaning of “future”. 

If it’s specified in CLDR then I think this change is fine. @ichernev

**Comment by anthonylau** [comment]
> They basically mean the same thing in Chinese.
> 
> The slight difference is: previous one means something happens **within** a certain duration of time. The changed one means it happens **after** a certain duration of time. I personally think the purposed change better reflects the meaning of “future”.
> 
> If it’s specified in CLDR then I think this change is fine. @ichernev

It makes sense to me.

**Comment by hehachris** [comment]
Agreed

**Comment by ichernev** [comment]
Merged in c5225f813f475547dfa0fa0776a94994f9cdc281

**Pull request closed without merging**
