### PR TITLE
[new locale] sd: Sindhi locale

### PR DESCRIPTION
**Pull request by narainsagar**
Hi, I have added support for [Sindhi](https://en.wikipedia.org/wiki/Sindhi_language) language translation, It is very basic module and For most cases, I think these changes should suffice.

Unit tests are included as well.

Thanks for the great library! 👍 

Cheers,

```
Global summary:
┌───────┬───────┬────────────┬────────┬────────┬─────────┐
│ Files │ Tests │ Assertions │ Failed │ Passed │ Runtime │
├───────┼───────┼────────────┼────────┼────────┼─────────┤
│ 1     │ 2892  │ 119091     │ 0      │ 119091 │ 10429   │
└───────┴───────┴────────────┴────────┴────────┴─────────┘

Running "exec:typescript-test" (exec) task

Done, without errors.
```

### CODE REVIEW

**Comment by narainsagar** [comment]
@maggiepint @Oire Any update on this when you'll merge this? Thanks

**Comment by Oire** [comment]
@maggiepint, should I ask someone for a review? It seems, several people have reacted with a thumbs-up...

**Comment by maggiepint** [comment]
This is fine. We will ship when we get around to next release.

**Comment by ichernev** [comment]
Merged in ef0f54895157d494d5a5e5fbf3f264928170bffd

**Pull request closed without merging**
