### PR TITLE
[new locale] yo: Yoruba (Nigeria) locale

### PR DESCRIPTION
**Pull request by andela-batolagbe**

### CODE REVIEW

**Comment by andela-batolagbe** [comment]
@mj1856 Changes rebased into one single commit, thanks.

**Comment by mj1856** [comment]
Thanks.  For future reference, you could have just rebased the existing branch and pushed, and it would have updated the original PR (#3424) instead of closing and creating a new one.  But this is fine.

**Comment by andela-batolagbe** [comment]
Oh, noted. Thanks.

**Comment by maggiepint** [comment]
Heads up. Because we came under JS Foundation management, we need a CLA signed for this to be merged. Should be just a couple clicks.

**Comment by andela-batolagbe** [comment]
@maggiepint, CLA agreement signed. I noticed there have been no updates on the checks though.

**Comment by JSFOwner** [comment]
The author information in the commit is invalid. The commit must contain your username and email to pass the CLA signature check. Please update the commit with correct author information.

**Comment by andela-batolagbe** [comment]
@ichernev commit updated with author information.

**Comment by ichernev** [comment]
Merged in fae800443e37152f4137961b5308a243a4f87b0b

**Pull request closed without merging**
