### PR TITLE
Standard nomenclature (pt, pt-br, es)

### PR DESCRIPTION
**Pull request by raphamorim**
I realized in pt and pt-br have some different things than others. In english and some other languages, the first of the characters is in uppercase. So why is different in pt and pt-br?

I started to implement the change, missing the tests yet and adjust in locale/pt. But I wonder if I can adjust.

**Note: DON'T merge this PR yet. Tests Failing.**

### CODE REVIEW

**Comment by ichernev** [comment]
@caio-ribeiro-pereira what do you think.
@raphamorim you will need to fix the tests

**Comment by raphamorim** [comment]
Yeah @ichernev, I talked about it.

I'll finish the code, if makes sense apply this changes :)

**Comment by caio-ribeiro-pereira** [comment]
For me it's okay!

**Comment by caio-ribeiro-pereira** [comment]
but one simple question, why all nomenclature are strings to be splited instead a simple array?

**Comment by raphamorim** [comment]
Good question @caio-ribeiro-pereira.

I'll finish the changes and update this PR at the morning (I'm out of my macbook now).

**Comment by raphamorim** [comment]
Oh! I realized this happens in others locales. So I adjust pt and en too. :octocat:

**Comment by ichernev** [comment]
Simple array is more characters. Compare

```javascript
["a", "b", "c", "d", "e", "f"]
"a b c d e f".split(" ")
```

Well, its kind of a hack, but we use it for all locales, so its not a big problem.

I'll merge this in next release.

**Comment by caio-ribeiro-pereira** [comment]
Well I didn't know about this hack, but in my opinion it's not necessary
worry about hacks when you are building javascript client-side libs because
when you minify it, a lot of js hacks are applied to make the code smaller
and faster.

Att,
Caio Ribeiro Pereira
Software Engineer
http://crpwebdev.com

**Comment by ichernev** [comment]
Merged in 0843b0e5944639038975611f46dda45243c88234

**Pull request closed without merging**
