### PR TITLE
[new locale] uz-latn: Uzbek latin locale

### PR DESCRIPTION
**Pull request by Rasulbeeek**

### CODE REVIEW

**Comment by ichernev** [comment]
@muminoff any comments on this one?

**Comment by ichernev** [comment]
@Rasulbeeek can you please only keep the changes in `src/locale/uz-latn.js` and `src/test/locale/uz-latn.js`.

**Comment by muminoff** [comment]
Well, Uzbek language is written in various alphabets: Arabic, Cyrillic and Latin. Despite of uzbeks in Afghanistan use Arabic alphabet, in the country Cyrillic and Latin alphabets are in official use. I think, it would be not bad to accept this PR as many uzbek people (especially young generation) prefer it, while the Government itself has been using Cyrillic alphabet during decades. I admit that Latin alphabet is the official one, but I am afraid government could make any changes soon.

**Comment by ichernev** [comment]
Merged in c2ea3cb42be827c2eb0da768f397f5e4cb395055

**Pull request closed without merging**
