### PR TITLE
[new locale] gom-latn: Konkani latin locale

### PR DESCRIPTION
**Pull request by WikiDiscoverer**
Add a new locale for Konkani in the Latin script (gom-latn)

### CODE REVIEW

**Comment by WikiDiscoverer** [comment]
@ichernev , what do you think about this?

**Comment by ichernev** [comment]
@WikiDiscoverer please rebase into one commit, and will merge.

**Comment by WikiDiscoverer** [comment]
Done, @ichernev .

**Comment by ichernev** [comment]
Merged in 2d7fea5532061504c4188d9daa9dfc47a5f30dc0

**Pull request closed without merging**
