### PR TITLE
Add day marker character for Japanese.(update)

### PR DESCRIPTION
**Pull request by XueWei**
Move changing to src/locale/ja.js.

### CODE REVIEW

**Comment by icambron** [comment]
Looks like you need to update the test too (OK to just add new commits to this PR)

**Comment by XueWei** [comment]
Update test. https://github.com/XueWei/moment/commit/e37b622aa805c9526b307c20be40bcd46d4e1144

**Comment by icambron** [comment]
Here's the output from the test:

```
Module: locale:ja Test: format
dddd, MMMM Do YYYY, a h:mm:ss ---> 日曜日, 2月 14 2010, 午後 3:25:50
    at Object.<anonymous> (/home/travis/build/moment/moment/build/umd/test/locale/ja.js:103:20)
Actual value:
日曜日, 2月 14日 2010, 午後 3:25:50
Expected value:
日曜日, 2月 14 2010, 午後 3:25:50
Module: locale:ja Test: format
d do dddd ddd dd ---> 0 0 日曜日 日 日
    at Object.<anonymous> (/home/travis/build/moment/moment/build/umd/test/locale/ja.js:103:20)
Actual value:
0 0日 日曜日 日 日
Expected value:
0 0 日曜日 日 日
Module: locale:ja Test: format
[the] DDDo [day of the year] ---> the 45 day of the year
    at Object.<anonymous> (/home/travis/build/moment/moment/build/umd/test/locale/ja.js:103:20)
Actual value:
the 45日 day of the year
Expected value:
the 45 day of the year
```

You can run them with `grunt test`

**Comment by XueWei** [comment]
update test again.

**Comment by icambron** [comment]
@ichernev this is ready to be merged. I suspect you don't want me to do drive-by merges though.

**Comment by XueWei** [comment]
You are welcome. btw, could you please let me know when it could be merged
into master branch ?

2015年12月23日星期三，Isaac Cambron <notifications@github.com> 写道：

**Comment by mj1856** [comment]
Sorry this has been sitting for awhile.  Could you please rebase against the current develop branch, and squash/fixup to a single commit?  Then we can stage it for the next release.  Thanks.

See: https://help.github.com/articles/about-git-rebase/

**Comment by ichernev** [comment]
Merged in 5083c7c117f9b5727e12736ef38942269e27321d

**Pull request closed without merging**
