### PR TITLE
Default to strict parsing (v3)

### PR DESCRIPTION
**Pull request by ichernev**
This was listed in https://github.com/moment/moment/issues/3775 as v3.

There are a few things to consider:
* **biggest issue** : a lot of locale tests fail, I'm not even sure how much strictness can we expect from them and how much work is required to fix locale definitions and tests for this to fly
* meridiem might be missing, should we handle that in strict #297 
* array of formats has a bunch of logic that does not require strict to work, should we just force strict on it too, or have some leeway
* `X` also parses `X.S`, `X.SS` and `X.SSS` so the latter fail in strict mode
* `str Z` (note the space) does not count as ISO, so it won't pass in strict (non-strict is going to the Date constructor IMHO)

### CODE REVIEW

**Comment by agvald** [comment]
We(me and my development team) would love to use moment in the strict mode by default, because we have had multiple bugs we would have noticed in strict mode which we haven't noticed before rolling out in production.

We have noticed it will be the default in version 3 but unfortunately it's not released. We looked for an early opt-in to use it before but we did not find it. We can submit a PR implementing an early opt-in, would that be accepted?
I don't have an overview over how far away v3 is, maybe it is a waste of time to implement it now?

**Comment by marwahaha** [comment]
What's early opt-in?

I'm not sure when v3 will come out.

**Comment by agvald** [comment]
I don't know, sorry for that, opt-in is what i meant. Don't know why early appeared in there. 🤦‍♂️

**Comment by agvald** [comment]
@marwahaha
Would it be interesting with an MR implementing an opt-in? No need for us to dive into the moment code if it won't be accepted anyways...

**Comment by marwahaha** [comment]
See https://momentjs.com/docs/#/-project-status/

**Pull request closed without merging**
