### PR TITLE
[locale] hu: Change week year start to ISO

### PR DESCRIPTION
**Pull request by judikdavid**
Change the first day of the year and related tests to
match the right Hungarian week of the year calculation.

### CODE REVIEW

**Comment by mj1856** [comment]
@adambrunner please verify.  Thanks.

**Comment by ichernev** [comment]
@judikdavid can you have a look at https://github.com/moment/moment/pull/3352#issuecomment-239362653

So you're saying you adopt ISO year beginning?

**Comment by judikdavid** [comment]
@ichernev not necessarily, ISO year beginning is the same for every country, but also every country has it's own definition how it calculates week numbers.
ISO definition: "The ISO 8601 definition for week 01 is the week with the year's first Thursday in it"
Hungary (and other countries)'s definition: "The week which includes January 4"

**Comment by ichernev** [comment]
@judikdavid can you please sign the CLA. I can not merge otherwise.

**Comment by ichernev** [comment]
@judikdavid FYI 4th of jan and first Thursday are equivalent definitions https://en.wikipedia.org/wiki/ISO_week_date#First_week

**Comment by judikdavid** [comment]
@ichernev thanks for the clarification 👍 I've also signed the CLA

**Comment by ichernev** [comment]
Merged in 0e001fe8a681e9d36be01e175888cf50dd0dae16

**Pull request closed without merging**
