### PR TITLE
[feature] Added relativeTimeThreshold() support for weeks re: #4514 

### PR DESCRIPTION
**Pull request by dmckenna24**
Added the following re: issue #4514 :

- Weeks as a threshold option
- Default thresholds: d = 6, w = 4
- Changed thresholds from days to months, to days to weeks
- Added threshold from weeks to months
- Updated tests to reflect these additions 
- Updates to documentation in a [separate pull request](https://github.com/moment/momentjs.com/pull/507).

### CODE REVIEW

**Comment by icambron** [comment]
I have no opinion on the PR itself, but can you rebase it?

**Comment by lad475** [comment]
@icambron Done :)

**Comment by icambron** [comment]
The code looks good to me, @marwahaha

**Comment by marijnz0r** [comment]
@icambron Can this be merged?

**Comment by icambron** [comment]
tagging in @marwahaha

**Comment by ichernev** [comment]
Support for relative weeks was merged in #5461 (commit 7165c2d3). Also the version merged doesn't enable it by default, because it is not something that everybody might want.

**Pull request closed without merging**
