### PR TITLE
[pkg] exports: use module.require for nodejs

### PR DESCRIPTION
**Pull request by yiminghe**
incase some web package tools inconvenience.

http://stackoverflow.com/questions/25384360/how-to-prevent-moment-js-from-loading-locales-with-webpack/25426019#25426019

https://github.com/webpack/webpack/issues/198

https://nodejs.org/dist/latest-v4.x/docs/api/modules.html#modules_module_require_id

@ichernev

### CODE REVIEW

**Comment by ichernev** [comment]
Ok the change looks good. Wow, we are causing a lot of trouble for webpack :)

**Comment by afc163** [comment]
:+1:

**Comment by ichernev** [comment]
Merged in bb6a30e3e9a1b2022b68794b30dd68ed561aa847

**Comment by ljharb** [comment]
um, this will break lots of tools - `require` is not the same as `module.require`.

**Comment by ljharb** [comment]
Indeed, this PR caused a breaking change in a minor version (see #3431). Please revert it ASAP.

**Comment by yiminghe** [comment]
if use require, webpack will load all locale data into browser(which is fine for nodejs but too much for web app).

This is a breaking change, but any serious web app should not depend on it.

**Comment by ljharb** [comment]
If webpack breaks on the standard and normal `require`, that's a webpack bug, not one individual packages should solve.

**Comment by ljharb** [comment]
Also, if it's a breaking change, it should be reverted for a v2.15.1, and published as v3.0.0 (at which point, Airbnb will no longer be able to use moment.js, so hopefully that doesn't happen)

**Comment by ichernev** [comment]
@yiminghe can you give more details about your environment so we can work out a fix that works on both phantomjs/karma and your env (webpack?).

**Comment by yiminghe** [comment]
@ichernev you can check the links in my pr. using require will cause browser to load all locales(too much for client) for webpack.

the idea usage(load on demand):

```
import 'moment/locale/zh-cn'; // import specified locale module
moment.locale('zh-cn');
```

**Comment by ichernev** [comment]
@yiminghe should I flip the checks order? Can you suggest something that works for the existing use case? So 'require' works for webpack but requires all of it, and if you use module.require it doesn't?

**Comment by ichernev** [comment]
The whole idea of this code is to ONLY work on node.js. In other envs it's intended to be used by first requiring only the locales you want (in code) and then switching the locale -- the snippet you provided.

**Comment by ipa1981** [comment]
Ok guys now it's reverted, so what's the plan now?

I use
```
import 'moment/locale/hr' # or require('moment/locale/hr'); the result is the same
moment.locale('hr')
```
and on version 2.15.1 it makes 150Kb heavier file (uglified) than on 2.5.0. So I had to revert to 2.5.0. 150K of dead weight is significant for web.

**Comment by ljharb** [comment]
150k is a small-to-medium sized image.

It's definitely something that can be improved, but it sounds like a webpack bug. When I install moment locally and browserify a file that requires `moment/locale/hr`, the resulting file is 143K *total* with 2.15.1, and the identical 143K total with 2.15.0.

**Comment by ipa1981** [comment]
@ljharb agree, 150KB could not be a problem in many site, but in high performance ones you fight for every KB. And there is additional 150KB of code browser needs to parse as well.

When it's considered as a webpack bug is it known for them?

**Comment by schmod** [comment]
This isn't a bug in Webpack.  Webpack's noticing that Moment (potentially) depends on all of the locales, and bundles them.  This is the correct and expected behavior, albeit an undesirable one for most Webpack users.  

I'd propose queuing this change back up for the next release that will include breaking changes.  It's a breaking change, but a sensible one.

**Comment by ljharb** [comment]
In what way is it sensible? It breaks `require` for every tool that's not Webpack.

**Comment by ichernev** [comment]
@schmod Wasn't there a way to tell webpack to bundle only manually specified files? I'm pretty sure a solution floated around.

If there is a way to trigger that behavior from whithin moment, that is great, or at least we can document it on momentjs.com.

**Comment by ichernev** [comment]
Lets see : https://github.com/webpack/webpack/issues/3128

**Pull request closed without merging**
