### PR TITLE
Fix errors reported by jscs

### PR DESCRIPTION
**Pull request by monoblaine**
This pull request fixes the code-style errors reported by "jscs:all" grunt task.

### CODE REVIEW

**Comment by maggiepint** [comment]
I don't think this is the error that's breaking the build. I was looking at the same issue, and I actually get entirely different errors from the linter, once I change the JSCS configuration that they have a deprecation on. Ultimately, we have to change the following error message, or peg the dependency back:

```
Running "jscs:all" (jscs) task
Warning: Config values to remove in 3.0:
The `esnext` option is enabled by default. Use --force to continue.
```

**Comment by maggiepint** [comment]
I'm going to make a pull to just push the dependency back right now since I have it done locally.

**Comment by monoblaine** [comment]
Oh, I haven't run `npm install` for months, that's probably why I got different errors. I did now, and now I get this instead:

```
[DEPRECATION NOTICE] Esperanto is no longer under active development. To convert an ES6 module to another format, consider using Babel (https://babeljs.io)
Warning: Task "jscs-all" not found. Use --force to continue.
```

**Comment by maggiepint** [comment]
Closing this pull as it doesn't fix the issue at hand. If you want to get everything working with the latest JSCS version, we certainly wouldn't say no to that.

**Pull request closed without merging**
