### PR TITLE
[locale] pl: Update weekday short strings

### PR DESCRIPTION
**Pull request by eximius313**
fixed typos

### CODE REVIEW

**Comment by ichernev** [comment]
@eximius313 ok you changed tests and now they dont pass. Change the locale file in src/locale and ping the author of the locale file.

**Comment by eximius313** [comment]
I already did: https://github.com/moment/moment/pull/3340

**Comment by mj1856** [comment]
@eximius313 - you need to submit the code change and the test change in the same PR.  Please update one of these and close the other.  Thanks.

**Comment by ichernev** [comment]
I'll manually merge it properly if its not ready.

**Comment by eximius313** [comment]
done

**Comment by ichernev** [comment]
Merged in 1a8243ff1f99d40fc717fd619ffb343373010c23

**Pull request closed without merging**
