### PR TITLE
[locale] Capitalization of pt month names

### PR DESCRIPTION
**Pull request by cassianomon**

### CODE REVIEW

**Comment by cassianomon** [comment]
@marwahaha How do I check what is failing?

**Comment by mercutiodesign** [comment]
You can either run the tests locally using `grunt test` or look at the [travis log](https://travis-ci.org/moment/moment/jobs/366093497#L559). So in your case it seems to be `Test: format`.

**Comment by cassianomon** [comment]
I had made multiple pull requests about the same subject by mistake, so I corrected this one for PT language only, the other one is for PT-BR (https://github.com/moment/moment/pull/4558), and 3 duplicates are closed (https://github.com/moment/moment/pull/4556, https://github.com/moment/moment/pull/4555 and 
 https://github.com/moment/moment/pull/4554), I am sorry.

**Comment by marwahaha** [comment]
@caio-ribeiro-pereira thoughts ?

**Comment by caio-ribeiro-pereira** [comment]
@marwahaha everything is okay for me :)

**Comment by cassianomon** [comment]
@marwahaha when this is gonna be released?

**Pull request merged**
