### PR TITLE
Improve Catalan localization

### PR DESCRIPTION
**Pull request by pereorga**
Fixes common mistake described in http://esadir.cat/entrades/fitxa/id/1496

Also added new newline character at the end of file.

### CODE REVIEW

**Comment by maggiepint** [comment]
@juanghurtado what do you think?

**Comment by juanghurtado** [comment]
👍

**Comment by ichernev** [comment]
@pereorga can you please update `src/locale/ca.js` and `src/test/locale/ca.js`. The other files are autogenerated.

You'd also need to sign the CLA (a new thing).

**Comment by mj1856** [comment]
@pereorga - in the future, you can just push updates the existing branch and it will update the original PR.  Creating a new PR isn't necessary.  But thanks.

**Comment by pereorga** [comment]
@mj1856 sure, but isn't better to merge only the right commits?

**Comment by juanghurtado** [comment]
Yep, that's why you can amend your commits and push them again

**Comment by mj1856** [comment]
Exactly.  That's what rebasing is all about.

**Comment by pereorga** [comment]
> Yep, that's why you can amend your commits and push them again

You mean rewriting git history and pushing? If that works, how can these older (wrong) commits be still referenced in the same PR?

> Exactly. That's what rebasing is all about.

I was using new git branches and PR because I understood they were cheap, if not free. I'm not sure I'm following you in that this is about rebasing, please could you elaborate?

**Pull request closed without merging**
