### PR TITLE
[new locale] es-mx: add Spanish (Mexico)

### PR DESCRIPTION
**Pull request by jcfranco**
This is based off of the default Spanish locale (`src/locale/es.js`) with the exception of first day of the week ([set to Sunday](https://github.com/unicode-cldr/cldr-core/blob/2c2d91fa0c581b7f3a35fc748a1ce88e070ac550/supplemental/weekData.json#L160)).

### CODE REVIEW

**Comment by jcfranco** [comment]
Did a little digging and the failing test is related to the latest rollup versions. The last one that worked was 2.23.1. 

cc @marwahaha

**Comment by marwahaha** [comment]
@jcfranco  - it looks like your tests are failing

**Comment by jcfranco** [comment]
Thanks for taking a look! I'll get the tests fixed, sorry about that. 😅

**Comment by jcfranco** [comment]
@marwahaha Tests fixed! 🔨

**Comment by marwahaha** [comment]
Great!

**Pull request merged**
