### PR TITLE
Code cleanup and speedup

### PR DESCRIPTION
**Pull request by Gobie**
Code cleanup
- remove unused code
- use undefined consistently, short-circuiting, existing functionality, computed values, ...
- clean structure of some conditions

Code speedup
- optimize zeroFill by ~20%, benchmark added

### CODE REVIEW

**Comment by ichernev** [comment]
Looks good. We're in the middle of a big refactoring now, so you'll have to rebase this patch onto the new code once it is merged.

**Comment by Gobie** [comment]
Rebased on top of current develop. @ichernev

**Comment by ichernev** [comment]
@Gobie, thank you! Will merge in next release.

**Comment by ichernev** [comment]
Merged in 49f88864ff411003bfe0550c36defcc75f30d93e

**Pull request closed without merging**
