### PR TITLE
Doing a first aim at getting midnight after adding 1 day. If that tim…

### PR DESCRIPTION
**Pull request by keithwillcode**
…e is not midnight, doing a second aim at midnight.

Worked on this with @kevPo.

### CODE REVIEW

**Comment by keithwillcode** [comment]
Closes #3132

**Comment by keithwillcode** [comment]
@ichernev Both grunt and the transpile commands are completing successfully on my machine. Thoughts on why they would fail on Travis CI?

**Comment by keithwillcode** [comment]
@mj1856 ^^

**Comment by ichernev** [comment]
@keithwillcode relax, software is sometimes (sigh) buggy.
About the code itself -- I didn't quite get that.

* shouldn't we be careful with this logic for units smaller than a day?
* doing another startOf might not be great, if you're off because of DST hole then you should try to find which way to go (fw or bw) depending on which one is closer (now you go only back)
* also you're trying to force `America/Sao_Paulo` in your tests, but that only works in moment-timezone, so you can not use this. You should introduce a DST hole with a function, so its always reproducible and doesn't needs dependencies -- https://github.com/moment/moment/blob/develop/src/test/moment/zones.js#L299

I hope the second aim will do it right ;-)

**Comment by maggiepint** [comment]
closing due to lack of response. Feel free to reopen if concerns are addressed.

**Pull request closed without merging**
