### PR TITLE
[bugfix] Add duration fields in month, day, time order, fixes #3997

### LINKED ISSUE #3997: .add() edge case failure
**Description of the Issue and Steps to Reproduce:**

Adding something just less than a month produces unexpected results:

var start = moment('2017-03-01');
var dur = moment.duration(1, 'month').subtract(1, 'second');
start.add(dur).toDate();
>> Tue Mar 28 2017 23:59:59 GMT+0200 (W. Europe Daylight Time)

Expected:
>> Fri Mar 31 2017 23:59:59 GMT+0200 (W. Europe Daylight Time)

Cause: moment apparently subtracts milliseconds first, then presumably uses daysInMonth() on the intermediate object to subtract 28 days for February. Rather, it should use daysInMonth() on the original object.

---
Reporting system info (probably completely irrelevant):

console.log( (new Date()).toString())
>> Wed Jun 07 2017 14:16:24 GMT+0200 (W. Europe Daylight Time)
console.log((new Date()).toLocaleString())
>> 6/7/2017, 2:16:47 PM
console.log( (new Date()).getTimezoneOffset())
>> -120
console.log( navigator.userAgent)
>> Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.98 Safari/537.36
console.log(moment.version)
>> 2.18.1

### PR DESCRIPTION
**Pull request by ashsearle**
Fixes #3997

### CODE REVIEW

**Comment by maggiepint** [comment]
close/open restarts the build!

**Comment by ichernev** [comment]
That is the proper change. It is already done in the 3.0 branch. I was just afraid of breaking compatibility for 2.x. @icambron @mj1856 what do you think.

**Comment by icambron** [comment]
I say just do it.

**Comment by icambron** [comment]
I'm going to mark this for release.

**Pull request merged**
