### PR TITLE
[bugfix] fixed Invalid Date issue with isValid method (closes #5011)

### LINKED ISSUE #5011: TypeError: config._d.getTime is not a function. (In 'config._d.getTime()', 'config._d.getTime' is undefined)
**Describe the bug**

This error pops up : `TypeError: config._d.getTime is not a function. (In 'config._d.getTime()', 'config._d.getTime' is undefined)`

- node_modules/moment/moment.js:238:47 in Moment
- node_modules/moment/moment.js:3202:26 in clone
- node_modules/moment/moment.js:3332:22 in toISOString

**To Reproduce**
no idea yet how to reproduce ...

**Expected behavior**
It should work as previously with version 2.23.0

**Screenshots**
img_0580

**Smartphone (please complete the following information):**
 - Device: iPhone5S
 - OS: ios 11.4.1

**Moment-specific environment**

"moment": "2.24.0" within expo sdk22 app

**Additional context**
`
TypeError: config._d.getTime is not a function. (In 'config._d.getTime()', 'config._d.getTime' is undefined)

This error is located at:
    in FameMore (at connectAlert.js:11)
    in ConnectedAlert (at withNavigation.js:17)
    in withNavigation(ConnectedAlert) (created by Connect(withNavigation(ConnectedAlert)))
    in Connect(withNavigation(ConnectedAlert)) (at FameTop.js:122)
    in RCTView (at View.js:44)
    in FameTop (at withNavigation.js:17)
    in withNavigation(FameTop) (at connectAlert.js:11)
    in ConnectedAlert (created by Connect(ConnectedAlert))
    in Connect(ConnectedAlert) (at FamePensees.js:41)
    in RCTView (at View.js:44)
    in FamePensees (created by Connect(FamePensees))
    in Connect(FamePensees) (at FameHomeView.js:309)
    in RCTView (at View.js:44)
    in CellRenderer (at VirtualizedList.js:687)
    in RCTScrollContentView (at ScrollView.js:852)
    in RCTScrollView (at ScrollView.js:977)
    in ScrollView (at VirtualizedList.js:1062)
    in VirtualizedList (at FlatList.js:662)
    in FlatList (at FameHomeView.js:475)
    in RCTView (at View.js:44)
    in FameHomeView (at connectAlert.js:11)
    in ConnectedAlert (created by Connect(ConnectedAlert))
    in Connect(ConnectedAlert) (at ReactMeteorData.js:88)
    in ReactMeteorDataComponent (at Home.js:339)
    in RCTView (at View.js:44)
    in KeyboardAvoidingView (at Home.js:333)
    in RCTView (at View.js:44)
    in Container (at Home.js:330)
    in Home (at connectAlert.js:11)
    in ConnectedAlert (at withNavigation.js:17)
    in withNavigation(ConnectedAlert) (created by Connect(withNavigation(ConnectedAlert)))
    in Connect(withNavigation(ConnectedAlert)) (at SceneView.js:17)
    in SceneView (at CardStack.js:466)
    in RCTView (at View.js:44)
    in AnimatedComponent (at Card.js:12)
    in Card (at PointerEventsContainer.js:39)
    in Container (at CardStack.js:498)
    in RCTView (at View.js:44)
    in RCTView (at View.js:44)
    in CardStack (at CardStackTransitioner.js:67)
    in RCTView (at View.js:44)
    in Transitioner (at CardStackTransitioner.js:19)
    in CardStackTransitioner (at StackNavigator.js:41)
    in Unknown (at createNavigator.js:13)
    in Navigator (at createNavigationContainer.js:226)
    in NavigationContainer (at AppWithNavigationState.js:66)
    in App (created by Connect(App))
    in Connect(App) (at app/index.js:242)
    in RCTView (at View.js:44)
    in AlertProvider (at app/index.js:241)
    in Provider (at app/index.js:240)
    in AppContainer (at ReactMeteorData.js:88)
    in ReactMeteorDataComponent (at withExpoRoot.js:22)
    in RootErrorBoundary (at withExpoRoot.js:21)
    in ExpoRootComponent (at renderApplication.js:34)
    in RCTView (at View.js:44)
    in RCTView (at View.js:44)
    in AppContainer (at renderApplication.js:33)

Moment
    moment.js:238:47
clone
    moment.js:3202:26
toISOString
    moment.js:3332:22
send
    socket.js:15:38
<unknown>
    ddp.js:44:25
process
    queue.js:21:32
push
    queue.js:16:4
method
    ddp.js:108:27
_default
    Call.js:9:29
componentDidMount
    FameMore.js:37:18
commitLifeCycles
    ReactNativeRenderer-dev.js:12144:10
commitAllLifeCycles
    ReactNativeRenderer-dev.js:13496:8
invokeGuardedCallbackImpl
    ReactNativeRenderer-dev.js:92:15
invokeGuardedCallback
    ReactNativeRenderer-dev.js:306:36
commitRoot
    ReactNativeRenderer-dev.js:13702:8
completeRoot
    ReactNativeRenderer-dev.js:15269:13
performWorkOnRoot
    ReactNativeRenderer-dev.js:15197:21
performWork
    ReactNativeRenderer-dev.js:15090:24
performSyncWork
    ReactNativeRenderer-dev.js:15047:14
batchedUpdates$1
    ReactNativeRenderer-dev.js:15315:21
batchedUpdates
    ReactNativeRenderer-dev.js:2616:31
_receiveRootNodeIDEvent
    ReactNativeRenderer-dev.js:2711:17
receiveTouches
    ReactNativeRenderer-dev.js:2787:28
__callFunction
    MessageQueue.js:349:47
<unknown>
    MessageQueue.js:106:26
__guard
    MessageQueue.js:297:10
callFunctionReturnFlushedQueue
    MessageQueue.js:105:17
`

### PR DESCRIPTION
**Pull request by niftylettuce**

### CODE REVIEW

**Comment by niftylettuce** [comment]
I've fixed the title of the commit.

**Comment by niftylettuce** [comment]
Please merge!

**Comment by ichernev** [comment]
@niftylettuce what are you actually fixing?

Problem, tests, discussions, environment?

**Comment by niftylettuce** [comment]
It's a bug, if you looked at the issue #5011

**Comment by ichernev** [comment]
@niftylettuce in this case it would be nice to provide a test case to prevent regressions. Also I'd put the code inside the big if -- after all _isValid should only be computed once.

**Comment by niftylettuce** [comment]
Sorry I don't use moment much anymore. This bug went unnoticed for a long time so I published `@ladjs/moment` which I've used and is backwards compatible (no regressions using this bug fix) for a long time in production.

I would merge bugfix and version bump.

On April 24, 2020 8:17:59 PM UTC, Iskren Ivov Chernev <notifications@github.com> wrote:
>@niftylettuce in this case it would be nice to provide a test case to
>prevent regressions. Also I'd put the code inside the big if -- after
>all _isValid should only be computed once.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/moment/moment/pull/5145#issuecomment-619220220

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ichernev** [comment]
@niftylettuce I want a test, because I still can't figure out what the problem is (how do you reproduce it). Moment is (unfortunately) pretty complicated and a problem can be fixed in a number of ways and I want to pick the right fix. But I need an actual problem to think upon :)

**Comment by marwahaha** [comment]
I feel like the linked issue #5011  needs a test to better show when exactly this bug occurs. 
After then, we can add the test to this PR.

**Comment by marwahaha** [comment]
I don't have any test cases to work with. So I will close this PR. Thanks for the tip if we ever need to merge something like this.

**Pull request closed without merging**
