### PR TITLE
[locale] cs: Fix incorrect inflections

### PR DESCRIPTION
**Pull request by indexxd**
The problem was created in this [PR](https://github.com/moment/moment/pull/5749) and this PR fixes it.

### CODE REVIEW

**Review by petrbela — APPROVED** [review]

**Review by AlesJiranek — APPROVED** [review]

**Comment by idoodler** [comment]
How can I help to merge this?

**Review by anandfresh — APPROVED** [review]

**Comment by idoodler** [comment]
Can someone fix this, how can I verify the checks?

**Comment by idoodler** [comment]
Whats the Status here?

**Comment by ichernev** [comment]
@indexxd  @idoodler already merged via https://github.com/moment/moment/pull/6191

**Pull request closed without merging**
