### PR TITLE
Fix negative 0 in certain diff cases

### LINKED ISSUE #3227: diff function returns negative zero (-0)
in theoretical math you can have negative zero while representing movement around zero. In computer science you can also have negative zeros when negative quantity [underflows to zero](http://www.johndcook.com/blog/2010/06/15/why-computers-have-signed-zero/)

Should diff function return integer w/o negative zero?

code:

```
    let days_left = moment(this.props.task.get('due_date')).diff(moment(), 'days');
    console.log('days_left: ', this.props.task.get('due_date'), days_left, moment().toDate().toISOString());
```

console output:

```
days_left:  2016-06-08T21:00:00.000Z -1 2016-06-10T08:12:06.820Z
days_left:  2016-06-09T21:00:00.000Z -0 2016-06-10T08:12:06.845Z
days_left:  2016-06-10T21:00:00.000Z 0 2016-06-10T08:12:06.869Z
```

to have better visual, screenshot of console:
image

### PR DESCRIPTION
**Pull request by ichernev**
Fixes #3227

### CODE REVIEW

**Comment by maggiepint** [comment]
LGTM. Glad I could write all that test scaffolding for you :-)

**Comment by ichernev** [comment]
@maggiepint not only that, but the `|| 0` hack from tim ;-)

**Comment by maggiepint** [comment]
I felt so stupid when he pointed that out 😃. One of those moments where you wonder if you're in the right profession.

**Comment by ichernev** [comment]
@maggiepint heh, nobody is stupid because they didn't think of a hack. This is not a google interview ...

**Comment by ichernev** [comment]
Merged in f01ca7a1767a5bc65097cf66ec6d630c05124d64

**Pull request closed without merging**
