### PR TITLE
RFC2822 Parsing implementation - Near-candidate solution

### PR DESCRIPTION
**Pull request by TracyGJG**
**Work in Progress - DO NOT MERGE**

Remaining issues:
1. I am still unable to get the tsc task to complete and have to force the release. I have tried various environment paths and even tried installing typescript as a global module without joy.
2. For RFC2822 to be valid and given day-of-week has to be consistent with the day-by-date. I have a negative test case and appropriate code (both disabled) but the latter depends on instantiating a moment object that I am unable to do. 

Any advice on the above would be gratefully received.

### CODE REVIEW

**Comment by TracyGJG** [comment]
It appears that the template literal used in one of my test cases is not compatible with Travis CI task 2.

**Comment by TracyGJG** [comment]
Related to Issue #2530.

**Comment by maggiepint** [comment]
I'm happy to have this pull re-opened if the tests pass, but I'm going to close for now as it has been sitting for so long.

**Comment by TracyGJG** [comment]
New PR #3708

**Pull request closed without merging**
