### PR TITLE
Typos at months

### PR DESCRIPTION
**Pull request by shabanovd**
source of currect names for months is http://www.localeplanet.com/icu/uz/

### CODE REVIEW

**Comment by ichernev** [comment]
@muminoff what do you think?

**Comment by muminoff** [comment]
Since my mother tongue is Uzbek language and I myself being a native Uzbek speaker, I took responsibility to make Uzbek locale for this awesome project. Uzbek language has two alphabets; Latin and Cyrillic. Cyrillic alphabet is being still used everywhere and many people in internet prefer it, so do I. In Cyrillic alphabet month names have ending soft signs. It was derived from Russian language from Soviet Union period. Although this question is very controversial even among Uzbek linguistics, as many online resources, printed magazines, media, TV still use soft sign in month names when they write in Cyrillic alphabet. If you accept this PR, someday other Uzbek native speaker sends you PR with adding soft sign in month names. Cheers!

**Comment by shabanovd** [comment]
Uzbek language did not have soft sign, only hard sign https://en.wikipedia.org/wiki/Uzbek_alphabet . Please, do not mix it with Russian one by confusion.

**Comment by shabanovd** [comment]
I, personally, think that change must have a prove, so here another one http://www.unicode.org/cldr/charts/latest/summary/uz.html ;)

**Comment by muminoff** [comment]
@shabanovd, yes, Uzbek language does not have soft sign, but the Cyrillic alphabet does. Soft sign has been used for international or localized words which came from other languages. 

And I am not mixing it up with Russian language. I am talking about Cyrillic alphabet, not about the language itself. You, do not mix it with Latin alphabet!

Look at these words: __фильм__, __октябрь__, __сентябрь__, __мультфильм__. 

If you are familiar with Uzbek language, what do you think about those words? Have you ever seen that __мультфильм__ written as __мултфилм__?

**Comment by shabanovd** [comment]
@muminoff Dialects are different from "academic" language (always). Uzbek cyrillic alphabet did not have soft sign https://en.wikipedia.org/wiki/Cyrillic_alphabets#Uzbek

Words will be written as филм, октябр, сентябр, мултфилм. More to that if you ask person that speak only Uzbek to say "мультфильм" you hear "мултфилм" and it going to be hard time to make "л" sound soft.

But here we discuss different thing: moment.js locale different from specification(s) and it up to moment.js, I just make a proposal to fix it.

**Comment by muminoff** [comment]
@shabanovd your explanation does not mean that __мултфилм__ is a correct written form. Soft sign IS still in a use. I don't care who edited the wiki page. But I am really sure that Uzbek Cyrillic alphabet has soft sign. Ask any Uzbek language specialist if you want clearness. I spent my whole 11 years in school using this soft sign. Don't try rewrite the history.

**Comment by muminoff** [comment]
> Words will be written as филм, октябр, сентябр, мултфилм. 

No, they cannot be.

>if you ask person that speak only Uzbek to say "мультфильм" you hear "мултфилм" 

We were discussing writing, not speaking/listening.

**Comment by shabanovd** [comment]
@muminoff good to know that the Unicode Consortium rewrite history, they so powerful now for me -)

Your argument `spent my whole 11 years in school` protect your life experience only, that nothing to do with language itself.

That just my 2 cents, you may do not spend time to response and close this PR.

**Comment by muminoff** [comment]
@shabanovd, closing or accepting the PR is up to authors. Your 2 cents might help you to improve your English grammar. Bye bye.

**Comment by ichernev** [comment]
@muminoff @shabanovd Thank you for commenting on this. After reviewing the evidence I'll go with the removal of the soft sign, because CLDR/ICU is one of the few "authorities" that can be trusted, and we at moment.js have personally used them before to resolve conflicts.

I'll merge it in next release.

**Comment by ichernev** [comment]
Merged in cd4553ce49fc5cf9e913559377997546841387eb

**Pull request closed without merging**
