### PR TITLE
Add method 'isSameOrBetween'

### PR DESCRIPTION
**Pull request by dbkirk4211**
Allows user to determine if Moment is between or equal to a set of Moments (From, To)

### CODE REVIEW

**Comment by dbkirk4211** [comment]
Mimics 2.10.7's implementation of isSameOrBefore and isSameOrAfter.

I know there is a pull request for something more complicated that allows for an 'options' object to determine (), [), [], or (].

I propose isSameOrBetween as an elegant solution that falls inline with Moment as is.

Thanks!

**Comment by mj1856** [comment]
The problem is that it only covers one additional use case (fully-inclusive).  It then opens the door for two additional methods for the half-open interval options.  Also the naming is off, because it's only "same" for one point within the range (a range can't be the same as a point).  And since the other PR is near completion, I'll pass on this one.

Thanks for the effort though.  It is appreciated.

**Comment by dbkirk4211** [comment]
No problem. Thank you.

**Comment by dbkirk4211** [comment]
I attached a PR to dardrone's isBetween()

https://github.com/dardrone/moment/pull/1

I think it is something more inline with the way Moment is currently
implemented.

w/r
Dave

**Comment by dardrone** [comment]
@dbkirk4211 https://github.com/moment/moment/pull/2943 covers both options object and argument list. The tests demonstrate this. See `test('is between, options as arguments')`.

**Comment by dbkirk4211** [comment]
I looked over the tests and the code changes. It looks great. I just think
it could be simple and clean without including the 'options' object. I put
a comment on your PR about this suggestion.

My motivation is that it isn't inline with Moment's other methods.

Thank you.

w/r

Dave

**Pull request closed without merging**
