### PR TITLE
[bugfix] Fix warnings flagged by closure compiler

### LINKED ISSUE #4347: Closure compiler warnings
Recent version of google closure compiler issues warnings:

```
ERROR: /home/davido/projects/gerrit2/polygerrit-ui/app/BUILD:9:1: Compiling 822 JavaScript files to polygerrit-ui/app/polygerrit_ui_closure_bin.js failed (Exit 1)
bazel-out/k8-fastbuild/bin/polygerrit-ui/app/gr-app.js:24671: ERROR - Parse error. Unnecessary escape: '\.' is equivalent to just '.'
                this._fullWeekdaysParse[i] = new RegExp('^' + this.weekdays(mom, '').replace('.', '\.?') + '$', 'i');
                                                                                                     ^
  ProTip: "JSC_UNNECESSARY_ESCAPE" or "unnecessaryEscape" can be added to the `suppress` attribute of:
  //polygerrit-ui/app:polygerrit_ui_closure_lib
```

To reproduce, clone [gerrit code review](https://gerrit.googlesource.com/gerrit), apply [this series](https://gerrit-review.googlesource.com/#/c/gerrit/+/147234/) and run:

```
  $ bazel build :polygerrit
```

### PR DESCRIPTION
**Pull request by davido**
Closes #4347.

### CODE REVIEW

**Comment by butterflyhug** [comment]
I expect this was a bug and we actually intended to escape the period within the RegExp.  In that case, the correct fix should be to double the backslashes rather than removing them.

**Comment by davido** [comment]
> I expect this was a bug and we actually intended the RegExp to search for a literal period. In that case, the correct fix should be to double the backslashes rather than removing them.

Done.

**Comment by marwahaha** [comment]
Can we add a couple tests around this? If the tests pass both ways, then it's not clear what the intended behavior is.

**Comment by marwahaha** [comment]
closing in favor of #4453

**Pull request closed without merging**
