### PR TITLE
Improved Finnish translations

### PR DESCRIPTION
**Pull request by crisu83**
Modified the translation originally made by @bleadof to be more similar to the other translations.

### CODE REVIEW

**Comment by mj1856** [comment]
Thanks.  Would you please also update [the unit tests](https://github.com/moment/moment/blob/develop/src/test/locale/fi.js) to match?

**Comment by crisu83** [comment]
@mj1856 sure, I'll do it as soon as I have time.

**Comment by mj1856** [comment]
Sure.  Just push to this same branch when you're ready.  (The PR will update automatically.)

**Comment by crisu83** [comment]
Yeah I know, thanks. :)

**Comment by ichernev** [comment]
@bleadof what do you think?

@crisu83 we can only merge after tests are added, just a heads up :)

**Comment by crisu83** [comment]
I will update the tests as soon as I have time to set up the test suite (hopefully today).

Sorry about the delay but I've been extremely busy the last two weeks.

**Comment by ichernev** [comment]
This needs to be rebased on top of the latest code (es6) and it needs tests.

**Comment by ichernev** [comment]
Closing for now. Feel free to reopen if you address the issues above.

**Comment by crisu83** [comment]
Fair enough, I don't have any spare time for this right now.

**Comment by bleadof** [comment]
Sorry! I've totally missed this. I'm currently ill, so I'll check it later this week.

**Pull request closed without merging**
