### PR TITLE
[locale] tl-ph: Update calendar strings

### PR DESCRIPTION
**Pull request by RIanDeLaCruz**
Changed the sentence construction for calendar time translation

@hagmandan please verify, Thanks

### CODE REVIEW

**Comment by johncrisostomo** [comment]
This seems good. I was about to PR changes related to this hehe.

**Comment by ichernev** [comment]
@RIanDeLaCruz looks good. Can you also please sign the CLA?

**Comment by RIanDeLaCruz** [comment]
@ichernev I've signed the CLA. :)

**Comment by ichernev** [comment]
Merged in 39026d230a7ef15efc66b3230b696f456e1a5b99

**Pull request closed without merging**
