### PR TITLE
The first week of the year, always contains 4 January.

### PR DESCRIPTION
**Pull request by lgabster**
https://en.wikipedia.org/wiki/ISO_week_date

### CODE REVIEW

**Comment by maggiepint** [comment]
The link you are referencing is to the ISO Calendar standard. This is not the same thing as what people in Hungary might consider the first week of the year. That is a culture specific thing.

@adambrunner, do you think this change should be there?

**Comment by lgabster** [comment]
In all hungarian calendar what I see, this (12.sept. - 18.sept.) week is the 37th of the year.
But unfortunately I don't find official documentation from this

**Comment by ichernev** [comment]
@mj1856 do you know where is this in CLDR? I couldn't find the key.

**Comment by ichernev** [comment]
Closing this in favor of #3429.

**Pull request closed without merging**
