### PR TITLE
Using 1000 * 60 * 60 instead of 36e5 to avoid floating point rounding errors

### LINKED ISSUE #2978: 2.3 hour duration gives 2h 17m (should be 2h 18m)
``` js
//moment.js 2.11.2
moment.duration(0.3, 'h').minutes()
//18, as expected
moment.duration(2.3, 'h').minutes()
//17
//?!?
```

I understand that it's floating point problem, but can we work around this somehow, by not converting everything to milliseconds for instance?

### PR DESCRIPTION
**Pull request by afanasy**
Fixes #2978

### CODE REVIEW

**Comment by mj1856** [comment]
Thanks!  Could you also include a unit test so we can be sure this doesn't revert with some future change?  The example code from the original issue should do fine.

Also, Were you able to find any other cases of this besides just the one reported?  Thanks.

**Comment by afanasy** [comment]
I think there are lots of cases, but I don't know how to summarise the problem in a more analytical way. This is another one I've found by picking numbers manually:
```js
//moment.js 2.11.2
moment.duration(0.1, 'h').minutes()
//6, as expected
moment.duration(4.1, 'h').minutes()
//5
//?!?
```
but this PR fixes it

**Comment by mj1856** [comment]
Thanks.  We'll merge this in the next release.  I suppose we'll have to tackle this one report at a time.

**Comment by ichernev** [comment]
Merged in 544a059c337c0347d7567dceb95137cf46f7acb5

**Pull request closed without merging**
