### PR TITLE
Remove caps in spanish month and days

### PR DESCRIPTION
**Pull request by clairecoloma**
There is no caps in spanish date as you can see: 
https://es.wikipedia.org/wiki/Mes
https://es.wikipedia.org/wiki/D%C3%ADa
http://www.spanish.cl/Vocabulary/Notes/Dias_Meses.htm
http://www.rae.es/consultas/mayuscula-o-minuscula-en-los-meses-los-dias-de-la-semana-y-las-estaciones-del-ano
http://www.wikilengua.org/index.php/Fecha

Tests are already in lower case expect abbreviation

@julionc are you agree ? :)

### CODE REVIEW

**Comment by julionc** [comment]
Thanks @clairecoloma :+1: 
Just a quick note, `locale/*.js` files are updated only on release. See [CONTRIBUTING.md](https://github.com/moment/moment/blob/develop/CONTRIBUTING.md#code-organization)

**Comment by clairecoloma** [comment]
Oh sorry, I missed that part. I revert the file

**Comment by julionc** [comment]
Awesome! don't forget to squash too ;)
@ichernev Is OK now. Could you please push this PR?

**Comment by ichernev** [comment]
Merged in a7c225b1c858938cd68afc5ca4410f3bba0f72c4

**Pull request closed without merging**
