### PR TITLE
Resolve issue #3014 inconsistent relativeTime locale in zh-tw

### PR DESCRIPTION
**Pull request by gaplo917**
fix the locale file and make it work as expected

### CODE REVIEW

**Comment by Oire** [comment]
@ben-lin, your thoughts, please? It seems logical but I don't speak Chinese, unfortunately.

**Comment by mj1856** [comment]
@gaplo917  - Please only modify the files in the `/src` directory.  The other is auto-generated at build time.  Thanks.

**Comment by ben-lin** [comment]
Yes this makes sense.

**Comment by Oire** [comment]
@gaplo917 @ben-lin, thanks! Staging for the next release.

**Comment by mj1856** [comment]
@gaplo917 - could you please rebase to remove the change to `/locale/zh-tw.js`.  Thanks.

**Comment by gaplo917** [comment]
@mj1856 sure, thanks

**Comment by mj1856** [comment]
:+1:

**Comment by ichernev** [comment]
Merged in 339b0a2aca499948f879347104c8545100363492

**Pull request closed without merging**
