### PR TITLE
[locale] Fix wrong calendar() output in 'be' localisation

### PR DESCRIPTION
**Pull request by SobakaSlava**
fixes https://github.com/moment/moment/issues/4502
@demidov91, there was wrong regexp (I assume `be` localisation was copied from `ru` and `Вв` was not changed by `Уу`) and that caused wrong output of calendar() function (Неправильно брались падежи)

### CODE REVIEW

**Comment by marwahaha** [comment]
@Oire any thoughts ?

**Comment by DmitryScaletta** [comment]
As a native speaker, I can confirm that's correct.

**Comment by SobakaSlava** [comment]
@DmitryScaletta is there any cases of using `ў`? If yes, then i will add it.

**Comment by marwahaha** [comment]
@DmitryScaletta @SobakaSlava shall I merge this?

**Comment by SobakaSlava** [comment]
@marwahaha Yes, sure

**Comment by marwahaha** [comment]
Ok, I tried pushing to your branch but I didn't have access.

If you add the following to src/test/locale/be.js:
```

**Comment by SobakaSlava** [comment]
@marwahaha sorry for a long wait. I've added the test.

**Pull request merged**
