### PR TITLE
Add filipino (fil) locale

### PR DESCRIPTION
**Pull request by gzurbach**
This PR adds support for Filipino (Tagalog) locale.

All tests should be passing.

### CODE REVIEW

**Comment by gzurbach** [comment]
Is there anything in particular I need to do to get this merged?

**Comment by icambron** [comment]
No, we're just slow :(

@ichernev this looks ok to me and I confirmed that the locale code is right.

**Comment by gzurbach** [comment]
I just realized there is a `tl-ph` locale for Tagalog Philippines. Looks like my PR is useless... feel free to close it.

**Comment by gzurbach** [comment]
Note that technically the official language of the country is now Filipino (fil) and not Tagalog (tl). They are pretty much identical but maybe the file should be renamed?

Source: http://tagaloglang.com/The-Philippines/Language/filipino-tagalog-pilipino.html

**Comment by icambron** [comment]
Yes, I do think we should get the name right. I agree it should be `fil`

**Comment by Oire** [comment]
@ichernev, @mj1856, may I close this one? And what about renaming the Tagalog file?

**Comment by maggiepint** [comment]
Closing. #3054 tracks the issue with Filipino.

**Pull request closed without merging**
