### PR TITLE
[locale] pt, pt-br: all weekdays min values with 2 characters.

### PR DESCRIPTION
**Pull request by prodis**
@jalex79 
@caio-ribeiro-pereira

### CODE REVIEW

**Comment by caio-ribeiro-pereira** [comment]
@prodis it's ok :)

**Comment by prodis** [comment]
@maggiepint

**Comment by ichernev** [comment]
@prodis this will be released in next minor.

**Comment by ichernev** [comment]
Merged in a52400ec443c942a71584f3bdafddd2847423862

**Pull request closed without merging**
