### PR TITLE
Change format of japanese minutes to `mm`

### PR DESCRIPTION
**Pull request by hermanjunge**
Change format of japanese minutes to `mm`

### CODE REVIEW

**Comment by ichernev** [comment]
@hermanjunge can you also fix the tests?

**Comment by hermanjunge** [comment]
Tests fixed.

**Comment by baryon** [comment]
In fact, In Japanese, we don't speak "午前3時00分".
 "午前3時0分" is OK.
if you want display "午前3時00分", moment().format("Ah時mm分"); maybe a right way.

> Well, I think it should be either more human format (like now), or more technical (like Ah:mm) but not mixed.

> @baryon what do you think?

**Comment by ichernev** [comment]
I don't think the change is necessary, closing.

**Pull request closed without merging**
