### PR TITLE
[locale] tr: update translation of Monday and Saturday

### LINKED ISSUE #5753: Wrong short date tranlation for locale tr
**Describe the bug**
According to Turkish Language Association.
Translations are wrong for short versions of Monday and Saturday in Turkish.

Case -> Pts and Cts.

**Expected behavior**
Monday : Pzt instead of Pts
Saturday: Cmt instead of Cts

**Screenshots**
image

### PR DESCRIPTION
**Pull request by DiegoBousfield**
fixes #5753

### CODE REVIEW

**Comment by marwahaha** [comment]
@BYK approval?

**Comment by DiegoBousfield** [comment]
Hey, could you mark the repository as hacktoberfest valid, or at least this PR, please?

**Comment by marwahaha** [comment]
@erhangundogan approval?

**Comment by erhangundogan** [comment]
@marwahaha LGTM. I can help you if you add me as a reviewer.

**Review by erhangundogan — APPROVED** [review]

**Review by ashman56 — COMMENTED** [review]
No

**Pull request merged**
