### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by sm2017**
%d is correct, not d%

### CODE REVIEW

**Comment by sm2017** [comment]
@marwahaha , @ichernev , @coveralls can you please accept PR and release a version?

**Comment by marwahaha** [comment]
@sm2017  - 
Thanks for opening this request. 

Please revert this change and edit `src/locale/fa.js` and at `src/test/locale/fa.js`.

**Comment by sm2017** [comment]
Revert?? Why revert?

**Comment by marwahaha** [comment]
Hi @sm2017 ,

The file you edited is a generated file. It should not be edited by anyone manually.

**Comment by sm2017** [comment]
@marwahaha I send https://github.com/moment/moment/pull/5013

**Pull request closed without merging**
