### PR TITLE
[locale] id: Fix short name for august in id locale

### PR DESCRIPTION
**Pull request by duxinxiao**
I saw all the other use Agt for august short name. ( like Android iPhone )

### CODE REVIEW

**Comment by ichernev** [comment]
Change only `src/locale/it.js` and `src/test/locale/it.js`.

**Comment by duxinxiao** [comment]
Sorry, I just changed it

**Comment by ichernev** [comment]
@tyok any comment on that?

**Comment by tyok** [comment]
I've just checked that android and iphone indeed use "agt".

I find it surprising. As a native Indonesian speaker, I've always thought that "ags" or "agu" is the more commonly used abbreviation. Even the wikipedia page on https://id.m.wikipedia.org/wiki/Bulan_(penanggalan) lists "agu" and "ags", but not "agt".

I'm not strong on language and  literature, though, and I've got no other reference.

**Comment by tyok** [comment]
Yeah, it's a strong argument to follow the version used in most devices. This change is okay, then.

**Pull request merged**
