### PR TITLE
[locale] de, de-at, de-ch: Improve month abbreviations, fixes #3803, #3838

### LINKED ISSUE #3803: German short months do not follow CLDR
Looking at https://github.com/moment/moment/blob/develop/locale/de.js it has
`monthsShort : 'Jan.Febr._Mrz._Apr._Mai_Jun._Jul._Aug._Sept._Okt._Nov._Dez.'.split(''),`

Not exactly the same as spec'ed in CLDR
CLDR:
`<monthWidth type="abbreviated">`
`<month type="1">Jan.</month>`
`<month type="2">Feb.</month>`
`<month type="3">März</month>`
`<month type="4">Apr.</month>`
`<month type="5">Mai</month>`
`<month type="6">Juni</month>`
`<month type="7">Juli</month>`
`<month type="8">Aug.</month>`
`<month type="9">Sep.</month>`
`<month type="10">Okt.</month>`
`<month type="11">Nov.</month>`
`<month type="12">Dez.</month>`
`</monthWidth>`
Isn't moment suppose to follow the CLDR?

### PR DESCRIPTION
**Pull request by Seldaek**

### CODE REVIEW

**Comment by marwahaha** [comment]
fixes #3803 
fixes #3838

**Comment by neroux** [comment]
Good catch, though at least for de-at.js all months should be abbreviated, with March differently though, and the trailing full stops removed.

```js
monthsShort : 'Jän_Feb_Mär_Apr_Mai_Jun_Jul_Aug_Sep_Okt_Nov_Dez'.split('_'),
```

http://www.localeplanet.com/java/de-AT/ has more on that

**Comment by Seldaek** [comment]
@neroux it really depends on which locale DB you look at, there doesn't seem to be an absolute truth there. I used stuff from the CLDR which are referenced in #3803

**Comment by Seldaek** [comment]
@marwahaha @maggiepint I'm glad you closed related issues but how about merging the fix? :)

**Comment by neroux** [comment]
@Seldaek An absolute truth would often make things a lot easier :)

common/main/de_AT.xml in [cldr-common-31.0.1.zip](http://www.unicode.org/Public/cldr/31.0.1/cldr-common-31.0.1.zip) appears to list both types. The "Mär/Jun/Jul" full-stop-less version on line 76 as month context "stand-alone" and the longer counterpart with full stops on line 46 as month context "format".

Windows seems to have gone for the stand-alone version

image

**Comment by mj1856** [comment]
Ping current de* authors:

@Oire
@MadMG
@mik01aj
@sschueller 
@lluchs

Please review and comment.  Thanks.

**Comment by sschueller** [comment]
According to official Swiss "Schreibweisungen" (https://www.bk.admin.ch/dokumentation/sprachen/04915/05016/index.html?lang=de#) this commit is wrong. They specifically name "Feb." as being incorrect and that it should be Febr.

>Schreibweise in verknapptem Text
In verknapptem Text → 104 werden die längeren
Monatsnamen – also Januar, Februar, August,
September, Oktober, November und Dezember –
abgekürzt.
 Jan., Febr. [falsch: Feb.], März, April, Mai, Juni,
Juli, Aug., Sept., Okt., Nov., Dez.
am 1. Jan. 1999

**Comment by neroux** [comment]
@sschueller You were referring specifically to de-ch here, right?

@MadMG Apart from the CLDR, is there a similar (Austrian) specification for de-at, as there is for de-ch? Windows at least uses the three-letter abbreviations only.

**Comment by sschueller** [comment]
@neroux Yes

However, I have discussed this internally and we have no objection to this change.

**Comment by MadMG** [comment]
@neroux I discussed this issue with my colleagues and we have no objection too.

**Comment by neroux** [comment]
@MadMG Were you referring only to the commits here or also to the issue I mentioned?

In the latter case monthsShort in de-at.js should be further changed to
```js
monthsShort : 'Jän_Feb_Mär_Apr_Mai_Jun_Jul_Aug_Sep_Okt_Nov_Dez'.split('_'),
```

**Comment by MadMG** [comment]
@neroux I'm sorry, I don't know if ther is an Austrian  spcification for that. Your suggested chante to `monthsShort` will be OK for us

**Comment by kearnmachine** [comment]
As of moment 2.18.1:
```
moment.locale('de')
moment.invalid().format()
```
> "Ungültiges Datum"
```
moment.locale('de-at')
moment.invalid().format()
```
> "Invalid date"

should also be "Ungültiges Datum"

**Comment by ichernev** [comment]
Merged in 759b4a4108a6519ed4411d6d670367b4aa156c75

**Pull request closed without merging**
