### PR TITLE
added Montenegrin locale (me.js)

### PR DESCRIPTION
**Pull request by miodragnikac**
Added missing locale for Montenegrin language (**me.js**)

### CODE REVIEW

**Comment by miodragnikac** [comment]
Wikipedia article
http://en.wikipedia.org/wiki/ISO_3166-2:ME

**Comment by ichernev** [comment]
@miodragnikac can you also add tests? You can take the `test/locale/en.js` and modify it for Montenegrin.

**Comment by miodragnikac** [comment]
@ichernev Added test file (test/locale/me.js) and all test passed.
Ready for production!
:-)

**Comment by ichernev** [comment]
Haha, it is. I'm going to merge this in next release.

**Comment by ichernev** [comment]
Merged in a2efa84

**Pull request closed without merging**
