### PR TITLE
[locale] ar, ar-dz, ar-kw, ar-ly, ar-ma, ar-sa: Fix typo in Monday

### PR DESCRIPTION
**Pull request by atefBB**
@ichernev @noureddineme DONE !

### CODE REVIEW

**Comment by ichernev** [comment]
@abdelsaid @xsoh @ElFadiliY @kikoanis @nusretparlak @noureddineme Does this look ok?

**Comment by ichernev** [comment]
@atefBB you need to fix the corresponding test files, as you can see the build is failing.

**Comment by xsoh** [comment]
@ichernev  Yes 👍

**Comment by atefBB** [comment]
Hey @ichernev how to fix `the corresponding test files`?

**Comment by xsoh** [comment]
I'll explain it in Arabic.
@atefBB 
يجب تعديل الملفات داخل هذا [الرابط](https://github.com/moment/moment/tree/develop/src/test/locale) 
لتتناسب مع الحالة الصحيحة تقوم بتشغيل
 `npm test` الـ
لتتأكد من أن العملية تمت بنجاح ثم ترفع ملفات 
ثم ترفعها هنا

**Comment by atefBB** [comment]
@ichernev DONE !

**Comment by marwahaha** [comment]
@atefBB  - you're failing some of the tests. Can you investigate and fix ?

**Comment by atefBB** [comment]
@marwahaha I'll check when I have time!

**Comment by marwahaha** [comment]
@atefBB - any updates?

**Comment by marwahaha** [comment]
This has been sitting for a long time, so I will close it.

Thanks for opening this request.
Please re-open if you still would like to contribute and get the tests to pass.
You are welcome to join on as a locale author.

**Comment by atefBB** [comment]
Hey. I don't know why tests fails! Any indication to solve it?

**Comment by marwahaha** [comment]
You can see the results here:
https://travis-ci.org/moment/moment/jobs/366601636

You can also run `grunt test` to run the tests on your computer.

**Pull request closed without merging**
