### PR TITLE
 Same length for weekdaysMin parts (Italian) ES6

### PR DESCRIPTION
**Pull request by massic80**
Rebasing, as discussed here https://github.com/moment/moment/pull/2237

### CODE REVIEW

**Comment by ichernev** [comment]
Ah that's better. You still need to fix the tests (should be a few lines).

**Comment by massic80** [comment]
Is this OK? I've been fighting GIT all day :)
https://github.com/moment/moment/pull/2638

**Comment by jisaacks** [comment]
@massic80 it appears that your __patch-5__ #2638 only adds the tests but does not have the updated code from __patch-4__.

Can you create a PR with both? You should be able to just create a new branch and cherry-pick each commit I believe.

**Comment by jisaacks** [comment]
If you are having git issues @massic80 let me know if I can help.

**Comment by jisaacks** [comment]
closing this in favor of #2639

**Pull request closed without merging**
