### PR TITLE
Fix locale for Khmer - Miss spelling of March

### PR DESCRIPTION
**Pull request by sereysethy**
Hi,

The translation of March in Khmer should be written as `មីនា` not `មិនា`.

### CODE REVIEW

**Comment by Oire** [comment]
@kruyvanna, your thoughts please? 
@sereysethy, if the change is approved, please fix the tests and rebase so the PR would consist of one single commit.

**Comment by mj1856** [comment]
CLDR seems to agree: http://www.unicode.org/cldr/charts/28/summary/km.html#1546

**Comment by sereysethy** [comment]
Hello, I already did rebase to my repository. And fix the tests as you advised. What's next?

I am a bit confused with rebase...

**Comment by mj1856** [comment]
Woah, take a look at your rebase.  I think you need to try again.  ;)

Be sure to catch up to current first.

```
git fetch upstream
git checkout develop
git merge upstream/develop
git checkout your-branch-with-the-change
git rebase develop
git push
```

**Comment by sereysethy** [comment]
Hi,

I think I have messed up with my repository. When I did git merge
upstream/develop there are a lot of files which contains some conflicts.

What should I do? Should I delete this repository and fork a new one?

Sethy

**Comment by sereysethy** [comment]
I should have sync my fork first before I made anything!

Pls help...

**Comment by mj1856** [comment]
Try:

```
git fetch upstream
git rebase upstream/develop
git push
```

**Comment by sereysethy** [comment]
Thank you. It seems to have solved my problem.

Another question that I wanna ask. What is a good practice that I should follow so that I should not be in this kind of situation again?

Should I sync my repo with upstream before any local commits? or Should I create a separate branch from develop?

**Comment by mj1856** [comment]
Well there are lots of opinions on this.  I'd recommend keeping your `develop` branch in sync with moment's `develop` branch so you can [fast forward](https://help.github.com/articles/syncing-a-fork/) it easily.  For any work of your own, create a new branch and do the work there.  It makes things a lot easier if you need to [rebase](https://help.github.com/articles/about-git-rebase/) or make other changes.  It also helps when you are working on multiple different things at the same time.

There are some resources listed here that might help:  https://help.github.com/articles/good-resources-for-learning-git-and-github/

**Comment by mj1856** [comment]
So now that I can see your change more clearly, you need to make one additional change.

Only the files in `/src` should be modified.  Undo the change in `/locale/km.js`.  That file is generated automatically at build time.

So undo that change, rebase to a single commit (using interactive rebase) and push.  It will update the PR automatically.

Thanks!

**Comment by sereysethy** [comment]
I undo the change already. Pls check.

Thanks, Sethy

**Comment by mj1856** [comment]
Ok, the PR looks good now.  Thanks!

Would be good to hear from @kruyvanna on the actual change, but since CLDR agrees I'll go ahead and mark it for next release.

**Comment by kruyvanna** [comment]
Sorry . I hope I am not too late. the PR looks good. Great job @sereysethy

**Comment by ichernev** [comment]
Merged in d1332bceb6af92c9f2042abbf16289a017844b03

**Pull request closed without merging**
