### PR TITLE
[locale] punjabi correction

### PR DESCRIPTION
**Pull request by adsingh14**
Corrected Punjabi mistakes.

_Avoid mis-typed commit name._ :sweat_smile:

### CODE REVIEW

**Comment by adsingh14** [comment]
@marwahaha 
Here are the final errors. 
I think it targets to the main **locale** folder.
image

**Comment by marwahaha** [comment]
@adsingh14 - please make the following corrections. I tried to do it but I don't have access to your repository (I think you can say "allow maintainers to make edits")

```
kmarwaha-m01:moment kmarwaha$ git diff
diff --git a/src/locale/pa-in.js b/src/locale/pa-in.js
index c19a5f90..f7fc8bec 100644
--- a/src/locale/pa-in.js
+++ b/src/locale/pa-in.js
@@ -1,6 +1,7 @@
 //! moment.js locale configuration
 //! locale : Punjabi (India) [pa-in]
-//! author : Harpreet Singh : https://github.com/harpreetkhalsagtbit | Amandeep Singh : https://github.com/adsingh14
+//! author : Harpreet Singh : https://github.com/harpreetkhalsagtbit
+//! author : Amandeep Singh : https://github.com/adsingh14
 
 import moment from '../moment';
 
@@ -113,4 +114,3 @@ export default moment.defineLocale('pa-in', {
         doy : 6  // The week that contains Jan 1st is the first week of the year.
     }
 });
-
diff --git a/src/test/locale/pa-in.js b/src/test/locale/pa-in.js
index a6c74e51..f9c6c3ef 100644
--- a/src/test/locale/pa-in.js
+++ b/src/test/locale/pa-in.js
@@ -138,11 +138,11 @@ test('from', function (assert) {
 
 test('suffix', function (assert) {
     assert.equal(moment(30000).from(0), 'ਕੁੱਝ ਸਕਿੰਟ ਵਿੱਚ',  'prefix');
-    assert.equal(moment(0).from(30000), 'ਕੁੱਝ ਸਕਿੰਟ ਪਹਿਲਾਂ', 'suffix');
+    assert.equal(moment(0).from(30000), 'ਕੁੱਝ ਸਕਿੰਟ ਪਿਛਲੇ', 'suffix');
 });
 
 test('now from now', function (assert) {
-    assert.equal(moment().fromNow(), 'ਕੁੱਝ ਸਕਿੰਟ ਪਹਿਲਾਂ',  'now from now should display as in the past');
+    assert.equal(moment().fromNow(), 'ਕੁੱਝ ਸਕਿੰਟ ਪਿਛਲੇ',  'now from now should display as in the past');
 });
 
 test('fromNow', function (assert) {
```

**Comment by adsingh14** [comment]
@marwahaha  Done!
But that words can change the real sense of telling time in Punjabi language.

_FYKI, I have already checked 'allow maintainers to make edits' while PR._ :)

**Comment by marwahaha** [comment]
@adsingh14 - do you want this change or not?

**Comment by adsingh14** [comment]
@marwahaha no changes for now. 

I've added an issue which I wanted to fix in next PR.

**Comment by adsingh14** [comment]
@marwahaha no changes for now, you can merge it anytime. :)

**Comment by marwahaha** [comment]
I think we have a commit in that does something similar: https://github.com/moment/moment/commit/ad49bd6666de707939e29e6ab4501555b2faaa09

If there are other changes, please re-open.

**Pull request closed without merging**
