### PR TITLE
Adding age calculation function

### PR DESCRIPTION
**Pull request by mj1856**
To help with issues like #2331 and #2661 - adding a common function to calculate a person's exact age - or other whole-year differences between two given calendar dates.

Example Usage:
```javascript
moment('1976-08-27').age() // 39
```

Note that I changed the function slightly from the example in #2331, such that Feb 29th birthdays will fall on Feb 28th in years without leap years.  There's a test for that included.

### CODE REVIEW

**Comment by jisaacks** [comment]
This looks great. :+1:

**Comment by mattgrande** [comment]
This looks good, but should we include culture-specific age calgulations, eg [East Asian age reckoning](https://en.wikipedia.org/wiki/East_Asian_age_reckoning)?

**Comment by mj1856** [comment]
@mattgrande - Good point, but Moment currently supports only the Gregorian calendar, and thus I think it's fair to only support age calculation based on the notion of whole elapsed Gregorian calendar years.

Supporting East Asian age of reckoning would be a good use case for a third-party plugin.  Note that it would need an algorithm to calculate the exact date for Lichun, and would need to take the other culture variations into account mentioned in the Wikipedia article.

Also, one might not always be talking about a person's birth age, but could also use this for other work or life anniversaries (hire dates, etc.). 

Also, the function accepts an optional parameter for the "now" date/time.  It is primarily for unit tests, but could also be used to calculate the calendar-year difference between any two moments - which is slightly different than using the `diff` function.

**Comment by mattgrande** [comment]
> Also, one might not always be talking about a person's birth age, but could also use this for other work or life anniversaries (hire dates, etc.).

That's a really good point that I didn't think about and, honestly, this would probably be used for things like that more than anything. You wouldn't want to use the other methods of calculating for a work anniversary, certainly!

**Comment by jisaacks** [comment]
I wonder if it would make since to have a way of specifying the unit, obviously years would be the default but it might be beneficial to know months, weeks or days since a given date as well.

**Comment by mj1856** [comment]
The more I think about this, I wonder if there's really any difference between this and just using the `diff` function...  I need to give it some more thought.

```javascript
var age = moment().diff(dateOfBirth, 'years');  // seems to work fine
```

**Comment by jisaacks** [comment]
> The more I think about this, I wonder if there's really any difference between this and just using the diff function... I need to give it some more thought.

I was actually starting to think the same thing. Was going to mention diff in my last comment but for some reason I was thinking `diff` gave a string like "1 year ago". I think I was internally confusing it with `moment#from` but yeah I think diff already solves this problem.

**Pull request closed without merging**
