### PR TITLE
Locale hr: Month name fix

### PR DESCRIPTION
**Pull request by tomhorvat**

### CODE REVIEW

**Comment by mattgrande** [comment]
Note: This is similar to #2048, although this one has tests. In that issue, it was noted that CLDR had it as "sječanj," however CLDR has since updated it to "siječanj." The abbreviation is also shown as "sij."

**Comment by tomhorvat** [comment]
This is pretty much duplicate of #2048 but I added tests.

**Comment by ichernev** [comment]
Looks good.

@tomhorvat can you please rebase to latest develop. Check https://github.com/moment/moment/blob/develop/CONTRIBUTING.md for more info.

**Comment by ichernev** [comment]
Merged in f2ee575

**Pull request closed without merging**
