### PR TITLE
[locale] es: Update month parsing to be dot lenient, fixes #3629

### LINKED ISSUE #3629: Locale short month: dots should not be required for parsing (error in monthsShort function call)
**Description of the Issue and Steps to Reproduce:**
In the Spanish locale, the `if (/-MMM-/.test(format)) {` test for `D-MMM-YYYY` format is **not** working for parsing, and therefore dates like `8-Dic-2016` result in `Invalid date`.  The format should be accepted.  `8-Dic.-2016` is parsed correctly, but is not the proper way of expressing a date in this format and the dot should not be required.

I've lived in Nicaragua for 16 years and the format `8-Dic-2016` is clearly the most common way of writing a shorthand date.  It's also highly preferred to use this type of format because in a mixed national/expat community using numbers-only dates is too confusing.

It appears that the problem is related to the fact that in line 19 of **es.js**, the test `if (/-MMM-/.test(format)) {` always comes up with an empty value for `format` when parsing.  Therefore, the use of `monthsShortDot` is always used and `monthsShort` is never used.  This is what is breaking the algorithm.  If format was passed correctly, it would select `monthsShort` and work properly.

**Environment:**
Chrome 54 on Windows 10

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
console.log( (new Date()).toString())
console.log((new Date()).toLocaleString())
console.log( (new Date()).getTimezoneOffset())
console.log( navigator.userAgent)
console.log(moment.version)

Console Log Output:
Tue Nov 29 2016 10:35:21 GMT-0600 (Central America Standard Time)
11/29/2016, 10:35:21 AM
360
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36
2.15.1

```

### PR DESCRIPTION
**Pull request by kkopanidis**
Fixed #3629 

Quoting the original author of the locale: @julionc 

The same changes should be made to the es-do locale, since to my understanding they are 90% identical.

### CODE REVIEW

**Comment by maggiepint** [comment]
Is there any way we can rebase this and reduce some of the whitespace changes? It's hard to tell what actually changed.

**Comment by kkopanidis** [comment]
Should be fine now

**Comment by ichernev** [comment]
@julionc can you please comment on that?

**Comment by ichernev** [comment]
The fact that our parser makes us do that is horrible... Is there a better way to parse dates? Maybe a new definition of strict?

**Comment by ichernev** [comment]
Merged in e068fde4a9f421814c84c4aacdb82d32ed5451e7

**Comment by gmanriqueUy** [comment]
Hi. When is this going to be released?

**Pull request closed without merging**
