### PR TITLE
4024 modify leap year to non

### PR DESCRIPTION
**Pull request by andy-shi88**
#4024 Fix

## Breakdowns:
- [x] check for month and date for leap year
- [x] set date to either 28 or 29 depending on isLeapYear of year value passed.

note: since the issue is caused by Date(), the approach I took is to check for the value passed to year() function.

### CODE REVIEW

**Comment by ichernev** [comment]
@andy-shi88 you need to modify files under `src/*` everything else is autogenerated.

**Comment by ichernev** [comment]
Also this is not the right location for the fix. All units can have a separate setter (month has one). You need to define a special setter for year that does this. Also include tests as appropriate.

**Comment by andy-shi88** [comment]
ok, will do that @ichernev

**Comment by marwahaha** [comment]
Thanks for your contribution. I think this issue was fixed with this patch: https://github.com/moment/moment/pull/4199

I will close. Let me know if you have thoughts about this.

**Pull request closed without merging**
