### PR TITLE
[new locale] (kab)

### PR DESCRIPTION
**Pull request by MohammedBelkacem**
create /src/locale/kab.js

### CODE REVIEW

**Comment by belkacem77** [comment]
Please see also PR #3784

**Comment by BoFFire** [comment]
Hi,
Any update ?

**Comment by marwahaha** [comment]
Please also copy the file src/test/locale/en-gb.js into a new file src/test/locale/kab.js. Translate everything into Kabyle.

**Comment by marwahaha** [comment]
@mozillakab or @BoFFire - could you make a test file?

**Comment by marwahaha** [comment]
Any update @mozillakab  or @BoFFire ?

**Comment by mozillakab** [comment]
@marwahaha Sorry. Was being because of COVID. I'll Check this weekend

**Comment by ichernev** [comment]
Closing this for inactivity. Reopen with added tests.

**Pull request closed without merging**
