### PR TITLE
Create nds-nl.js

### PR DESCRIPTION
**Pull request by Servien**
Translation for the nds-nl-wiki.

### CODE REVIEW

**Comment by robin0van0der0v** [comment]
Looks good as far as I can tell.
You only forgot to add yourself as author and you also forgot the test locale. :wink:
(I just saw your ticket on CLDR for Dutch Low Saxon as well. :laughing:)

**Comment by ichernev** [comment]
Can you please rebase to latest develop. Use https://github.com/moment/moment/blob/develop/CONTRIBUTING.md for more info.

**Comment by mj1856** [comment]
Closing due to no response from author.  If this is still important to you, please adjust the code and rebase.  Thanks.

**Comment by Servien** [comment]
Hi there. It's not quite clear to me what I should change. Is there a standard English file from which I could translate?

**Pull request closed without merging**
