### PR TITLE
[misc] Add 'ss' relative time key to typescript definition

### PR DESCRIPTION
**Pull request by xkxx**
Hi there,

This patch adds 'ss' to RelativeTimeKey to make the typescript definition more complete, and updates the typing tests to match.

First patch to moment.js, so please let me know if there's anything I'm missing or if you have any suggestions for improvements!

### CODE REVIEW

**Comment by ichernev** [comment]
This is the same as #4138 but slightly better, maybe :)

**Comment by xkxx** [comment]
Hi ichernev!

Is there anything that I need to address in the PR for it to be accepted?

Thanks,

Kexiang

**Comment by ichernev** [comment]
@xkxx don't you also need https://github.com/moment/moment/pull/4138/files#diff-3dd6cebe542b0e207494192c4bbf4a22R217

**Comment by xkxx** [comment]
Hi @ichernev,

How's the PR looking now? (Please ignore the git author screwup earlier :/)

**Comment by xkxx** [comment]
Hello @ichernev again,

Could you take a look at this PR and see if there's anything else for it to be merged?

Thanks,

xkxx

**Comment by xkxx** [comment]
Hello, just a friendly ping if anyone would like to take another look at the PR :)

**Comment by butterflyhug** [comment]
I think this looks good -- tagging for inclusion in the next release.

**Pull request merged**
