### PR TITLE
[pkg] npm: Ignore all non-source files

### PR DESCRIPTION
**Pull request by KELiON**
In this PR I'm adding some directories and files that are not used by npm package into `.npmignore` file. It reduces size of installed package and size of `tgz` file that is downloaded during moment installation.

Also something related to this PR: `min` directory contains two versions of each files (i.e. `locales.js` and `locales.min.js`). Does it makes sense to do it?  Ignoring `min/locales.js` and `min/moment-with-locales.js` and publishing only `min/locales.min.js` and `min/moment-with-locales.min.js` can significantly reduce size of the package.

Another proposal to reduce package size: currently it contains both ES6 and old-js versions in one package. It can be splitted to 2 packages (like `lodash` and `lodash-es`), so developer can choose what they want to use, instead of always downloading both versions.

### CODE REVIEW

**Comment by maggiepint** [comment]
Close/open to rerun build

**Comment by maggiepint** [comment]
On the note of your contribution - this change looks right to me. There's no reason to ship anything other than code that is used.

Agree on principal about splitting the ESNext and the old stuff apart. What are the implications for existing users that would have to change packages?

**Comment by KELiON** [comment]
@maggiepint releasing major version + detailed explanation of migration process in changelog can solve this problem

**Comment by ichernev** [comment]
@KELiON is there a document about what is supposed to be in an NPM package? Only the code? 

Skipping gruntfile and tasks might prevent you from rebuilding something quickly, but is not a hard requirement (for example).

About the min vs non-min versions -- we need more than moment and moment-es, we need like 5 versions, including no locales, different locale files, single locale file, all files... There will be unhappy users, I just don't know where to drow the line with this one.

**Comment by marwahaha** [comment]
Close-reopen to rerun build

**Comment by marwahaha** [comment]
I think right now, we ship:
### Required
* CHANGELOG.md (reqd)
* README.md (reqd)
* LICENSE (reqd)
* package.json (reqd)
### External libraries
* moment.d.ts (important, unless we switch to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped))
* package.js (from Dojo - do we need this? https://dojotoolkit.org/documentation/tutorials/1.10/build/)
* ender.js ( from Ender -- I think we need to keep this ? https://github.com/rvagg/archived-ender-tutorial-guts)
### Code
* moment.js (moment in a module) and min/moment.min.js (uglify'd)
* min/locales.js (all locales in module) and min/locales.min.js (uglify'd)
* min/moment-with-locales.js (moment and all locales in module) and min/moment-with-locales.min.js (uglify'd)
* locale/  (each locale file in a module)
* src/locale/ (source of locales)
* src/lib/ (source of moment)

What should we ship in the node module? You can use a bundler to pick and choose which files you include in your application, but perhaps we do not need to ship everything.

**Comment by joh-klein** [comment]
Maybe this is not the best way, commenting on an old issue (it's the most recent I could find) – but I just checked, and this is from the most recent version 2.29.1
Is it really necessary to include this many (and if I see it correctly) often duplicate files?
I know, normally I would not care this much since everything runs through webpack or similar. But for a project of mine I am using AWS Lambda and I have to include the whole node_modules folder – and right now moment is 70% of the whole folder …


Don't get me wrong – i REALLY love moment.js. It's one my top js packages!

```
.
├── [800K]  dist
│   ├── [648K]  locale
│   │   ├── [2.1K]  af.js
│   │   ├── …
│   │   └── [2.9K]  zh-tw.js
│   └── [150K]  moment.js
├── [736K]  locale
│   ├── [2.7K]  af.js
│   ├── …
│   └── [3.6K]  zh-tw.js
├── [2.2M]  min
│   ├── [434K]  locales.js
│   ├── [303K]  locales.min.js
│   ├── [137K]  locales.min.js.map
│   ├── [603K]  moment-with-locales.js
│   ├── [361K]  moment-with-locales.min.js
│   ├── [225K]  moment-with-locales.min.js.map
│   ├── [ 57K]  moment.min.js
│   └── [ 85K]  moment.min.js.map
├── [1.1M]  src
│   ├── [492K]  lib
│   │   ├── [ …]  create
│   │   │   ├── [1.5K]  check-overflow.js
│   │   │   ├── [1.1K]  date-from-array.js
│   │   │   ├── [3.3K]  from-anything.js
│   │   │   ├── [5.5K]  from-array.js
│   │   │   ├── [ 549]  from-object.js
│   │   │   ├── [1.9K]  from-string-and-array.js
│   │   │   ├── [4.0K]  from-string-and-format.js
│   │   │   ├── [7.7K]  from-string.js
│   │   │   ├── [ 183]  local.js
│   │   │   ├── [ 644]  parsing-flags.js
│   │   │   ├── [ 186]  utc.js
│   │   │   └── [1.5K]  valid.js
│   │   ├── [ …]  duration
│   │   │   ├── [ 484]  abs.js
│   │   │   ├── [ 644]  add-subtract.js
│   │   │   ├── [2.3K]  as.js
│   │   │   ├── [1.7K]  bubble.js
│   │   │   ├── [ 105]  clone.js
│   │   │   ├── [1.6K]  constructor.js
│   │   │   ├── [4.2K]  create.js
│   │   │   ├── [ 342]  duration.js
│   │   │   ├── [ 728]  get.js
│   │   │   ├── [3.4K]  humanize.js
│   │   │   ├── [2.0K]  iso-string.js
│   │   │   ├── [1.7K]  prototype.js
│   │   │   └── [1.1K]  valid.js
│   │   ├── [  …]  format
│   │   │   └── [2.8K]  format.js
│   │   ├── [ …]  locale
│   │   │   ├── [1.2K]  base-config.js
│   │   │   ├── [ 442]  calendar.js
│   │   │   ├── [  93]  constructor.js
│   │   │   ├── [ 989]  en.js
│   │   │   ├── [ 876]  formats.js
│   │   │   ├── [ 113]  invalid.js
│   │   │   ├── [2.1K]  lists.js
│   │   │   ├── [ 829]  locale.js
│   │   │   ├── [7.4K]  locales.js
│   │   │   ├── [ 218]  ordinal.js
│   │   │   ├── [  66]  pre-post-format.js
│   │   │   ├── [2.2K]  prototype.js
│   │   │   ├── [ 842]  relative.js
│   │   │   └── [1.8K]  set.js
│   │   ├── [ …]  moment
│   │   │   ├── [1.8K]  add-subtract.js
│   │   │   ├── [1.7K]  calendar.js
│   │   │   ├── [  98]  clone.js
│   │   │   ├── [2.3K]  compare.js
│   │   │   ├── [2.0K]  constructor.js
│   │   │   ├── [ 192]  creation-data.js
│   │   │   ├── [2.3K]  diff.js
│   │   │   ├── [2.3K]  format.js
│   │   │   ├── [ 609]  from.js
│   │   │   ├── [1.9K]  get-set.js
│   │   │   ├── [ 946]  locale.js
│   │   │   ├── [1.9K]  min-max.js
│   │   │   ├── [ 609]  moment.js
│   │   │   ├── [  82]  now.js
│   │   │   ├── [5.4K]  prototype.js
│   │   │   ├── [4.7K]  start-end-of.js
│   │   │   ├── [ 834]  to-type.js
│   │   │   ├── [ 603]  to.js
│   │   │   └── [ 364]  valid.js
│   │   ├── [ …]  parse
│   │   │   ├── [2.5K]  regex.js
│   │   │   └── [ 915]  token.js
│   │   ├── [ …]  units
│   │   │   ├── [ 809]  aliases.js
│   │   │   ├── [ 148]  constants.js
│   │   │   ├── [1.0K]  day-of-month.js
│   │   │   ├── [ 13K]  day-of-week.js
│   │   │   ├── [ 920]  day-of-year.js
│   │   │   ├── [7.8K]  era.js
│   │   │   ├── [4.4K]  hour.js
│   │   │   ├── [1.8K]  millisecond.js
│   │   │   ├── [ 679]  minute.js
│   │   │   ├── [9.8K]  month.js
│   │   │   ├── [6.9K]  offset.js
│   │   │   ├── [ 480]  priorities.js
│   │   │   ├── [ 780]  quarter.js
│   │   │   ├── [ 679]  second.js
│   │   │   ├── [ 590]  timestamp.js
│   │   │   ├── [ 325]  timezone.js
│   │   │   ├── [ 404]  units.js
│   │   │   ├── [2.1K]  week-calendar-utils.js
│   │   │   ├── [3.4K]  week-year.js
│   │   │   ├── [1.6K]  week.js
│   │   │   └── [2.0K]  year.js
│   │   └── [ …]  utils
│   │       ├── [ 154]  abs-ceil.js
│   │       ├── [ 179]  abs-floor.js
│   │       ├── [ 166]  abs-round.js
│   │       ├── [ 553]  compare-arrays.js
│   │       ├── [ 203]  defaults.js
│   │       ├── [1.9K]  deprecate.js
│   │       ├── [ 345]  extend.js
│   │       ├── [ 100]  has-own-prop.js
│   │       ├── [ 296]  hooks.js
│   │       ├── [ 342]  index-of.js
│   │       ├── [ 164]  is-array.js
│   │       ├── [ 670]  is-calendar-spec.js
│   │       ├── [ 161]  is-date.js
│   │       ├── [ 210]  is-function.js
│   │       ├── [ 106]  is-leap-year.js
│   │       ├── [1.9K]  is-moment-input.js
│   │       ├── [ 169]  is-number.js
│   │       ├── [ 360]  is-object-empty.js
│   │       ├── [ 246]  is-object.js
│   │       ├── [ 109]  is-string.js
│   │       ├── [  76]  is-undefined.js
│   │       ├── [ 344]  keys.js
│   │       ├── [ 164]  map.js
│   │       ├── [  68]  mod.js
│   │       ├── [ 394]  some.js
│   │       ├── [ 282]  to-int.js
│   │       └── [ 352]  zero-fill.js
│   ├── [648K]  locale
│   │   ├── [2.1K]  af.js
│   │   ├── …
│   │   └── [2.9K]  zh-tw.js
│   └── [2.6K]  moment.js
├── [ 24K]  ts3.1-typings
│   └── [ 23K]  moment.d.ts
├── [ 44K]  CHANGELOG.md
├── [1.0K]  LICENSE
├── [2.4K]  README.md
├── [  39]  ender.js
├── [ 23K]  moment.d.ts
├── [170K]  moment.js
├── [ 273]  package.js
└── [4.0K]  package.json

16 directories, 533 files
5.1M  Total
```
(Done with [tree](http://mama.indstate.edu/users/ice/tree/))

**Pull request closed without merging**
