### PR TITLE
[new locale] tg: Tajik (Tajikistan) locale

### PR DESCRIPTION
**Pull request by orif-jr**
Language: Tajik (cyrillic)
ISO 639-1: [tg]
ISO 639-2: [tgk]

### CODE REVIEW

**Comment by orif-jr** [comment]
hi there,
the pull request is still open and looks like not accepted/merged yet.
will it take longer time until it accepted?

**Comment by ichernev** [comment]
@orif-jr you need to change `src/locale/tg.js` and `src/test/locale/tg.js`, `locale/tg.js` is autogenerated, so do not touch it.

**Comment by orif-jr** [comment]
@ichernev thanks for the hint, the changes are included to current pull request.

**Comment by ichernev** [comment]
There is something wrong with this PR -- a bunch of non-related changes crept in. Please force-push in your branch only the correct changes. I'm leaving this open for now.

**Comment by orif-jr** [comment]
@ichernev the changes are correct now and tests are passed.

**Comment by orif-jr** [comment]
@ichernev and @marwahaha 
is there any plans regaring merging of the pull request?
it passes all checks and builds.

p.s. it missed yesterda's release :(

**Comment by marwahaha** [comment]
@orif-jr - this is looking good. 

What's the difference between `tg` and `tgk` ?

**Comment by orif-jr** [comment]
@marwahaha it's abbreviations of Tajiklanguage according to ISO Codes. Have a look at top of the story :)

**Comment by marwahaha** [comment]
Ok. Confirming this is just tg, not tgk.

**Pull request merged**
