### PR TITLE
[locale] kn: Improve month abbreviations, fixes  #3833

### LINKED ISSUE #3833: Kannada  localization month abbreviations are not correct
**Description of the Issue and Steps to Reproduce:**

*Please include the values of all variables used.*

**Environment:**

*Examples: Chrome 49 on OSX, Internet Explorer 10 on Windows 7, Node.JS 4.4.4 on Ubuntu 16.0.4*

*Both the browser and the OS are important to us, particularly if you have an unsual environment like an IOT application.*

**Other information that may be helpful:**
* The time zone setting of the machine the code is running on
* The time and date at which the code was run
* Other libraries in use (TypeScript, Immutable.js, etc)

If you are reporting an issue, please run the following code in the environment you are using and include the output:
```js
console.log( (new Date()).toString())
console.log((new Date()).toLocaleString())
console.log( (new Date()).getTimezoneOffset())
console.log( navigator.userAgent)
console.log(moment.version)
```

*Ensure your issue is isolated to moment. Issues involving third party tools will be closed unless submitted by the tool's author/maintainer.*

### PR DESCRIPTION
**Pull request by mohan-mu**

### CODE REVIEW

**Comment by ichernev** [comment]
@mohan-mu you also need to change the tests in `src/test/locale/kn.js`.

**Comment by ichernev** [comment]
@rajeevnaikte what do you think?

**Comment by mohan-mu** [comment]
@icambron Thanks for your Help:)

**Comment by rajeevnaikte** [comment]
@ichernev sorry for very late reply. mohan-mu has made change to reduce one character in 'kn' script for few months short name. Change looks good.

**Pull request closed without merging**
