### PR TITLE
Chris/zh tw improvement

### PR DESCRIPTION
**Pull request by hehachris**
@ben-lin @ichernev 
To replace #3075

### CODE REVIEW

**Comment by Oire** [comment]
Looks good. @ben-lin?

**Comment by ben-lin** [comment]
Looks good to me.

**Comment by Oire** [comment]
Thanks! Staging for the next release.

**Comment by ichernev** [comment]
Merged in 6c65ffaf63d1dd5edb95e310fa5ea8e65fb8e930

**Pull request closed without merging**
