### PR TITLE
[misc] typings: creator arg are readonly

### PR DESCRIPTION
**Pull request by Offirmo**
Stricter typing outlining that obviously moment won't mutate the params passed to the creator. (I hope!)

Maybe a few more Readonly could be added here and there but I'm not an expert. Feel free to edit this PR.

### CODE REVIEW

**Comment by ichernev** [comment]
@Offirmo fixing typescript definitions line by line is a (maintenance) disaster. If you want this merged -- look through the API and add it in all necessary places. If you're unsure if the input is changed (most of the time it shouldn't be) look in the code.

**Comment by Offirmo** [comment]
@ichernev I'm not sure I understand, sorry. "look through the API and add it in all necessary places" Do you mean there is another file to modify which generates the typings?

**Comment by ichernev** [comment]
So you're saying in the whole of moment, the only 3 things that are read-only arguments are these? Also is this TS1.x compliant?

**Comment by Offirmo** [comment]
Ok I got it. No worries mate!

**Pull request closed without merging**
