### PR TITLE
[locale] it: Improve relative time

### PR DESCRIPTION
**Pull request by Manfre98**
Source (in Italian): http://www.accademiadellacrusca.it/it/lingua-italiana/consulenza-linguistica/domande-risposte/larticolo-date-cifre
Examples:
«Today at 00:30 AM», before changes «Oggi alle 00:30», after changes «Oggi a 00:30».
«Today at 01:30 AM», before changes «Oggi alle 01:30», after changes «Oggi all'01:30».
«Today at 02:30 AM», before changes «Oggi alle 02:30», after changes «Oggi alle 02:30».

The hour that starts with 1 needs to have «all'{time}» instead of «alle {time}», the hour that starts with 0 needs to have «a {time}» instead of «alle {time}», all the other numbers needs to have «alle {time}».

### CODE REVIEW

**Comment by marwahaha** [comment]
@Manfre98 - please revert the change to `locale/*`, that is generated.

@nostalgiaz - approval?

**Comment by nostalgiaz** [comment]
@marwahaha yep, it's correct!

**Comment by ichernev** [comment]
@Manfre98 the tests don't pass:
```
Module: locale:it Test: calendar last week
Today - 2 days beginning of day
    at Object.<anonymous> (/home/iskren/src/moment/build/umd/test/locale/it.js:464:20)
Actual value:
Lo scorso mercoledì a 00:00
Expected value:
Lo scorso mercoledì alle 00:00

Module: locale:it Test: calendar last week
Today - 3 days beginning of day
    at Object.<anonymous> (/home/iskren/src/moment/build/umd/test/locale/it.js:464:20)
Actual value:
Lo scorso martedì a 00:00
Expected value:
Lo scorso martedì alle 00:00

Module: locale:it Test: calendar last week
Today - 4 days beginning of day
    at Object.<anonymous> (/home/iskren/src/moment/build/umd/test/locale/it.js:464:20)
Actual value:
Lo scorso lunedì a 00:00
Expected value:
Lo scorso lunedì alle 00:00

Module: locale:it Test: calendar last week
Today - 5 days beginning of day
    at Object.<anonymous> (/home/iskren/src/moment/build/umd/test/locale/it.js:464:20)
Actual value:
La scorsa domenica a 00:00
Expected value:
La scorsa domenica alle 00:00

Module: locale:it Test: calendar last week
Today - 6 days beginning of day
    at Object.<anonymous> (/home/iskren/src/moment/build/umd/test/locale/it.js:464:20)
Actual value:
Lo scorso sabato a 00:00
Expected value:
Lo scorso sabato alle 00:00
```

Also you'd need to remove the `locale/it.js` change as it is autogenerated from the `src/locale/it.js` one.

**Comment by ichernev** [comment]
Merged in b162aeedabe09110d4c3ee9f10b0c7bb2fdbd985

**Comment by ichernev** [comment]
I fixed the tests, removed the `locale/*` changes. @Manfre98 thanks for contributing.

**Pull request closed without merging**
