### PR TITLE
Update ar.js

### PR DESCRIPTION
**Pull request by turkialawlqy**

### CODE REVIEW

**Comment by Oire** [comment]
@forabi, what do you think? And as I don't speak Arabic so far, what is the matter of the change itself?

**Comment by mj1856** [comment]
Wrong files modified.  See contributing guide.  Thanks.

**Comment by forabi** [comment]
@turkialawlqy Thanks! That's actually a better phrase, but as @mj1856 has mentioned, you need to modify the source files instead. You also need to remove the extra white spaces at lines 98 and 100.

**Comment by forabi** [comment]
@Oire We don't usually use any preposition with hours in Arabic, so instead of "_at_ 12:00", we just say "12:00". @turkialawlqy wants to remove the preposition. The old translation was too literal. I'm not sure why I didn't remove it when I updated the plurals.

**Comment by maggiepint** [comment]
Any progress on this?

**Comment by maggiepint** [comment]
Closing, stale.

**Pull request closed without merging**
