### PR TITLE
Setter garbage fix using isNaN

### PR DESCRIPTION
**Pull request by wi-ski**
I have issues with this approach - would like to discuss.  Primary issue is that I could not get the previous tests passing with this implementation.  Meaning, this implementation is intentionally gimped.

### CODE REVIEW

**Comment by ichernev** [comment]
Unless I' missing something you can remove isNumber impl and tests, as it is not used. Looks good, we should make the moment invalid on invalid set for v3.

**Comment by willdembinski** [comment]
@ichernev - Will remove and update PR.  Will also rebase.

**Comment by ichernev** [comment]
@wi-ski you haven't signed the CLA, so can't really merge this yet.

**Comment by westy92** [comment]
The check claims he has:
image

**Comment by wi-ski** [comment]
@ichernev - I apologize.  I signed the agreement but never acknowledged having done it.

**Pull request merged**
