### PR TITLE
[feature] Check whether input is date before checking if format is array

### PR DESCRIPTION
**Pull request by johncrisostomo**
Fixes the issue as demonstrated here: https://jsfiddle.net/r6wpn9un/

### CODE REVIEW

**Comment by maggiepint** [comment]
This code is fine, but you need to add unit tests.

**Comment by johncrisostomo** [comment]
Okay I will add some for this case. Thank you.

**Comment by maggiepint** [comment]
Your test logic is good, but you cannot pass strings other than ISO8601 Extended with Offset to the date constructor and get a reliable result. The format you are using is not a defined format, thus each browser may parse it differently. While it works on a machine with a US locale, it may be parsed as invalid in any country using DD/MM/YYYY format.

Instead, use explicit syntax when constructing your test dates:
```js
new Date(2016,10,28)
```

**Comment by mj1856** [comment]
👍 to @maggiepint's comment.  But also, make sure to recognize that months in that syntax are zero-based.

**Comment by mj1856** [comment]
Oh, and don't edit `moment.js` directly.  It will be generated as part of the build.

**Comment by johncrisostomo** [comment]
Thank you for the guidance, I am still new at this and I need all the help I can get. :) I will fix them today.

**Comment by ichernev** [comment]
Merged in 03d78315b7ead5edaa2dfe2928f4069740f04746

**Pull request closed without merging**
