### PR TITLE
bower.json: remove moot `version` field

### PR DESCRIPTION
**Pull request by cvrebert**
Per https://github.com/bower/bower.json-spec/commit/a325da3d79baab018c572d75dc1781b12322f6cd

### CODE REVIEW

**Comment by kkirsche** [comment]
Also just an FYI there are discussions to move bower to NPM anyway so I wouldn't really plan to support it for ever: bower/bower#1520

**Comment by kkirsche** [comment]
Also their maintainer says they probably won't ever use it: http://stackoverflow.com/questions/24844901/bowers-bower-json-file-version-property

**Comment by cvrebert** [comment]
@kkirsche Wow, I see you're working hard on spreading the gospel of "death to `bower.json`'s `version` property" :smile:

**Comment by kkirsche** [comment]
Yep. My plan is to get it to every single repo that uses it. I'm not a fan of extra fragmentation in the JS community :+1:

**Comment by mj1856** [comment]
I believe [tasks/bump_version.js](https://github.com/moment/moment/blob/89d76e55b5332ec7c966bc544cabebe6498daa0e/tasks/bump_version.js#L34-L44) also needs to be updated, and this can also be removed from [moment-timezone//bower.json](https://github.com/moment/moment-timezone/blob/develop/bower.json) as well.

**Comment by cvrebert** [comment]
@mj1856 Okay, I've updated `bump_version.js` too.

**Comment by mj1856** [comment]
Thanks!

**Pull request merged**
