### PR TITLE
Change months, weekdays to lowercase

### PR DESCRIPTION
**Pull request by talgautb**
@nurlan approve my changes

### CODE REVIEW

**Comment by Oire** [comment]
@talgautb, thanks! In order for this to pass our checks, you have to change `src/locale/kk.js`, not `locale/kk.js`, and also modify the tests appropriately, then rebase to make this one single commit. Would you mind to do this on your own or do you need my help? Thanks again!

**Comment by talgautb** [comment]
@Oire updated `src/locale/kk.js` and test file.

**Comment by Oire** [comment]
@talgautb, nice, thanks!

**Comment by ichernev** [comment]
Merged in adb7472cb98add3df5477980a7e2c0370f85db40

**Pull request closed without merging**
