### PR TITLE
[locale] es: Update month and week names

### PR DESCRIPTION
**Pull request by jsegra**
Update to capital letter the first letter of months and days.

### CODE REVIEW

**Comment by ichernev** [comment]
@jsegra change only `src/locale/es.js` and `src/test/locale/es.js`.

**Comment by ichernev** [comment]
@julionc any comments?

**Comment by julionc** [comment]
In Spanish we capitalize proper names for people, places and so on. The names of months and weekdays are written in lower case.

See #2497 discussion - [Spanish Source](http://www.rae.es/consultas/mayuscula-o-minuscula-en-los-meses-los-dias-de-la-semana-y-las-estaciones-del-ano)

Remember, The first word of a sentence, or of a fragment, begins with a capital letter.
In that case, take a look at the following example:

```js
var chosenLocale = 'es';

moment.locale(chosenLocale);

var __weekdays = moment.weekdays().map(function (days) {
	return days.charAt(0).toUpperCase() + days.slice(1);
});

moment.updateLocale(chosenLocale, {
	weekdays: __weekdays
 });

document.body.innerHTML = moment().format('dddd, LL'); // Martes, 24 de octubre de 2017
 ```


Want more info? Here's an [article](https://www.thoughtco.com/capitalization-in-spanish-3080293) that explains which words are capitalized in Spanish.

**Comment by ichernev** [comment]
@julionc thank you!

**Comment by anjapadu** [comment]
But what happends if a sentence starts with July. First letter of any sentence should be Upper case

**Pull request closed without merging**
