### PR TITLE
Update it.js

### PR DESCRIPTION
**Pull request by pungggi**
update weekdaysMin to 2 letters

### CODE REVIEW

**Comment by mj1856** [comment]
@aliem @nostalgiaz @Oire   Please review.

Some prior discussion in https://github.com/moment/moment/pull/262#issuecomment-5694897

Also, there should be a corresponding unit test added to [/src/test/locale/it.js](https://github.com/moment/moment/blob/develop/src/test/locale/it.js).  (There should have already been one which would have made this fail, but I don't see it.)

**Comment by ichernev** [comment]
@pungggi can you reference some official document that states how should weekdays be abbreviated in Italian?

**Comment by aliem** [comment]
The official, or most used abbreviation is three letters:

- lun
- mar
- mer
- gio
- ven
- sab
- dom

But the two or one letter versions are in use in the current language.

PS. sorry for not being very active lately.

**Comment by ichernev** [comment]
This is already merged: fa77d561d5e0ec4cb393c6426f2b95c5a76d80a9

**Pull request closed without merging**
