### PR TITLE
Update ar-sa.js

### PR DESCRIPTION
**Pull request by turkialawlqy**
Correct some of the words

### CODE REVIEW

**Comment by ichernev** [comment]
@xsoh any comments. @turkialawlqy you have to update the tests too.

**Comment by ichernev** [comment]
@turkialawlqy also change `src/locale/ar-sa.js`, `locale/ar-sa.js` is autogenerated.

**Comment by xsoh** [comment]
@icambron @turkialawlqy  Actually, it is about best description and the best description here is to be same as [ar.js](https://github.com/moment/moment/blob/develop/locale/ar.js#L95) which is used `عند` instead of `في` and `على`.

**Comment by mj1856** [comment]
@turkialawlqy - Please read the [contributing guidelines](https://github.com/moment/moment/blob/develop/CONTRIBUTING.md).  The changes need to be made in `src/locale/ar-sa.js` and `src/test/locale/ar-sa.js` instead of the autogenerated file.

@xsoh  - Please be clear for those of us that do not understand the language.  Are you suggesting that there is a better correction than the one that in this PR?  Or that the existing form should be left as-is?

Thanks.

**Comment by xsoh** [comment]
@mj1856  The better is in this PR and the best is to be like the one in [ar.js](https://github.com/moment/moment/blob/develop/locale/ar.js#L95)

**Comment by Oire** [comment]
@turkialawlqy, any update on this?

**Comment by maggiepint** [comment]
@turkialawlqy we are closing this as it has been stale for quite a while. If you make the requested changes, we would be more than happy to re-open the pull request and get your changes merged. Thanks again for contributing!

**Pull request closed without merging**
