### PR TITLE
Pass duration to relativeTime's formatting handlers

### PR DESCRIPTION
**Pull request by laurentguilbert**
This gives more flexibility to do things like "2 days and 6 hours ago" for example instead of the current "2 days ago".

Of course the parameter is completely optional and doesn't disturb anything else. 

Thank you in advance.

### CODE REVIEW

**Comment by ichernev** [comment]
You should add tests. Also dont change moment.js, its generated on release.

**Comment by ichernev** [comment]
Can you provide a usecase for this change. I fail to see how this works together.

**Comment by laurentguilbert** [comment]
Sure I'll add some tests as soon as I have some time.

As for the use case, I wanted to be able to display how many days but also hours passed since a given date. 

The actual implementation (correct me if I'm wrong) only passes the number of months, days or hours to the handler without further informations. Having the duration, we are free to display whatever time scale we want.

Does it make sense ?

**Comment by ichernev** [comment]
You basically want complete control over the `moment.from`, `moment.fromNow` and `duration.humanize` methods. In this case I'd suggest to add the option to specify `relativeTime` as a function instead of a dictionary with string/function values.

Then the relativeTime (duration_humanize__relativeTime) can be skipped if the locale provides a function. Currently it computes the right token and value, but if you're not going to use that and want more control I don't see why not skip it altogether.

Also, we're currently using es6 module transpiling, so your changes have to go in the src/lib directory, tests in `src/test`.

**Comment by ichernev** [comment]
This needs to be heavily reworked to merge. Closing. Feel free to reopen if you do it as described in the previous comment.

**Pull request closed without merging**
