### PR TITLE
[new locale] ar-dz: Arabic (Algeria) locale

### PR DESCRIPTION
**Pull request by noureddineme**

### CODE REVIEW

**Comment by mj1856** [comment]
Please be sure tests pass.  Thanks.

**Comment by noureddineme** [comment]
Hi @mj1856 , any news thanks!

**Comment by ichernev** [comment]
@noureddineme the code is good. Now you'll need to sign the CLA (a new thing) and this will go out in next release. Thanks for contributing!

**Comment by noureddineme** [comment]
Done! thank you @ichernev :smile:

**Comment by ichernev** [comment]
Merged in 0394adeff563e5deb9af3177be03d47a4fa2d950

**Pull request closed without merging**
