### PR TITLE
[misc] TS: Add missing `ss` property to RelativeTimeSpec and MomentRelativeTime

### PR DESCRIPTION
**Pull request by dar5hak**
The property `ss` was missing in `RelativeTimeSpec` and `MomentRelativeTime` interfaces, although the docs say it exists.

I have only changed the `d.ts` file; I assume it is an independent change, and should not affect anything else.

### CODE REVIEW

**Comment by dar5hak** [comment]
Okay, turns out I need to update the tests as well.

**Comment by dar5hak** [comment]
Help! I made the first commit from GitHub web itself, and second from a machine which was configured using a different email. After the CLA bot's comment, I added the other email to my account. How do I let the bot know that?

**Comment by ichernev** [comment]
@dar5hak you can just remake the commits on a single machine by copying the diffs and open a new PR.

**Comment by ichernev** [comment]
@dar5hak https://github.com/moment/moment/pull/4246/files#diff-3dd6cebe542b0e207494192c4bbf4a22R5

Don't you need this too?

**Comment by dar5hak** [comment]
Oh yes! I'll do that, thanks.

**Comment by dar5hak** [comment]
Hey, sorry for the delay. I think #4246 is a better candidate for merging, since it encompasses all changes required in the file. I'll close this. You might want to remove the label.

**Pull request closed without merging**
