### PR TITLE
Switch transpiler to babel and rollup

### PR DESCRIPTION
**Pull request by timrwood**
:exclamation: Not ready for merging :exclamation: 

This is the start of replacing esperanto with babel and rollup. This transpiles the entire `src` directory into `build/cjs` in a commonjs module format, and uses that to run unit tests. It also builds some umd artifacts currently, though I am missing quite a few still.

TODO:
- [ ] Create `locales.js`
- [ ] Create `moment-locales.js`
- [ ] Custom locales builder.
- [ ] Unit tests for browser
- [ ] Retain comment headers in built files

A potentially breaking change is that the locale files no longer `export default`. I'm not sure anyone was using them as `var es = require('moment/locale/es')` anywhere. I changed this so that rollup wouldn't complain about not declaring a module name for each of those files, I'm not sure if there is another way around this.

### CODE REVIEW

**Comment by ichernev** [comment]
The `src/locales.js` and `src/test/all.js` -- can we autogenerate those when we need to use them, I hope they won't be part of the repo when this is merged.

**Comment by mj1856** [comment]
See also #2980

**Comment by maggiepint** [comment]
@timrwood do you want help on this? Can't say it's my area of expertise, but I'd like to see it done. Tell me what to do and I'll play with it a bit.

**Comment by maggiepint** [comment]
Closing. Iskren finished in different branch.

**Pull request closed without merging**
