### PR TITLE
Updated lv locale for better phrasing

### PR DESCRIPTION
**Pull request by krauzand**
In my opinion current phrasing for from and fromNow methods was little bit awkward, therefore tried to change it.

### CODE REVIEW

**Comment by ichernev** [comment]
@skakri what do you think?

**Comment by skakri** [comment]
@ichernev yeah, some phrases are really awkward (what were I thinking in "12...). I can't check it fully right now, but I already have a good feeling. @krauzand would that be okay, if I help with `TODO: pirms 1 dienas => vakar, pēc 1 dienas = rīt.`?

**Comment by krauzand** [comment]
@skakri Sure. Would be happy if you fix rīt/vakar. 

—
A.K.

**Comment by skakri** [comment]
@ichernev should I fork @krauzand fork and send a pull rq. to him (subfork -> fork -> upstream)? Which flow do you prefer?

**Comment by ichernev** [comment]
@skakri well, just take his branch, add a few commits and make a new PR (with all commits) here:

```bash
git fetch https://github.com/krauzand/moment develop
git checkout -b lv-fix FETCH_HEAD
# change files
# git commit 
# git push (to your github)
# make a PR with lv-fix
```

**Comment by ichernev** [comment]
@skakri any progress with this?

**Comment by skakri** [comment]
@ichernev sorry, no. I've totally forgot about this PRQ. But it looks good overall. Tenses are much better. I think you should merge this PR, sorry for my busyness.

If anything, we can adjust wording – latvian is pretty weird as it is, we tend to swap words from region to region (vidzeme/latgale).

**Comment by skakri** [comment]
We can fix `TODO: pirms 1 dienas => vakar, pēc 1 dienas = rīt` later, it's not critical.

**Comment by ichernev** [comment]
This has been merged #2321

**Pull request closed without merging**
