### PR TITLE
[locale] fix month typo

### PR DESCRIPTION
**Pull request by scientist1642**

### CODE REVIEW

**Comment by scientist1642** [comment]
It's just 1 letter typo. -- Anyone? 😞

**Comment by mantinone** [comment]
Hello @scientist1642 !

When making changes to a locale file, you'll want to tag the creator of the file so they can check your work.  You'll see their user name in the comments at the top of the file.

If you're correcting the name of a month, you'll also want to make sure it stays consistent with the tests.  Run the tests with `grunt test` and make sure everything is still passing.  If the month you changed is used in any of the tests, you'll need to change the word in the test file, too.

**Comment by ichernev** [comment]
@scientist1642 you have to update the tests.

@irakli-janiashvili any comments on this?

**Comment by ichernev** [comment]
@scientist1642 it looks like the original author is no longer on github. Can you provide some proof about the fix, some authority that agrees with you?

**Comment by ichernev** [comment]
The months were already changed in 48b5ef705ab3b679b424d29762179552f336e6be
If you're not happy you can open a new PR on top (I hope not :)).

**Pull request closed without merging**
