### PR TITLE
Update tests for pull request #1904

### PR DESCRIPTION
**Pull request by zenozeng**
Update tests for #1904

### CODE REVIEW

**Comment by zenozeng** [comment]
@ichernev

**Comment by ichernev** [comment]
@zenozeng can you rebase this one too?

**Comment by zenozeng** [comment]
Done. Sorry for being late.

**Comment by ichernev** [comment]
This is a no op

**Comment by zenozeng** [comment]
@ichernev Hello? I wonder why this pull request was closed. 
This commit (https://github.com/zenozeng/moment/commit/ab51d2c4440037ae4323945503730a7ead1d1707) already includes code changes and related tests and was based on the latest develop.  The Chinese char "分" should be append to "Ah点mm".
What about reopen this pull? Or should I submit another pull request?

**Pull request closed without merging**
