### PR TITLE
Fix Bangla translation for Evening, relative time, friday

### PR DESCRIPTION
**Pull request by thehungrycoder**
A few Bangla words are fixed. 

Ref: 

* http://www.ovidhan.org/b2b/%E0%A6%AC%E0%A6%BF%E0%A6%95%E0%A6%BE%E0%A6%B2 
or https://translate.google.com/#en/bn/%E0%A6%AC%E0%A6%BF%E0%A6%95%E0%A6%BE%E0%A6%B2

* https://translate.google.com/#en/bn/Friday

### CODE REVIEW

**Comment by jisaacks** [comment]
Ping @kaushikgandhi

**Comment by thehungrycoder** [comment]
Any update regarding this PR?

**Comment by kaushikgandhi** [comment]
looks good on other parts @thehungrycoder I am not too sure about বিকাল or বিকেল . If you can confirm this is correct @jisaacks can go ahead and merge . 
Thanks

**Comment by thehungrycoder** [comment]
> looks good on other parts @thehungrycoder I am not too sure about বিকাল or বিকেল . If you can confirm this is correct @jisaacks can go ahead and merge . 

Awesome. I've provided links above. Also if you translate in google translator, it'll show বিকাল.

**Comment by kaushikgandhi** [comment]
@jisaacks Yeah commit looks good. You can go ahead and merge.

Thanks

**Comment by ichernev** [comment]
Merged in 5158c258e668d3f346900e2c78f1da471ffa5f22

**Pull request closed without merging**
