### PR TITLE
Kannada locale

### PR DESCRIPTION
**Pull request by rajeevnaikte**

### CODE REVIEW

**Comment by mj1856** [comment]
Please rebase to a single commit as well.  Thanks.

**Comment by ichernev** [comment]
@rajeevnaikte looks good. Please also sign the CLA (its a recent requirement).

**Comment by mj1856** [comment]
@rajeevnaikte - Please [sign the CLA](https://cla.js.foundation/moment/moment?pullRequest=3492), and also [rebase](https://help.github.com/articles/about-git-rebase/) this to a single commit.  Thanks.

**Comment by rajeevnaikte** [comment]
Thank you. Apologies for delay. I have signed the CLA. The squashed single commit is - SHA 65f8e1cdf62a0a44147aedbcead17a4ccbb8b689

**Comment by rajeevnaikte** [comment]
Thank you. Apologies for delay. Have signed CLA. The squashed single commit is SHA 65f8e1cdf62a0a44147aedbcead17a4ccbb8b689

**Comment by mj1856** [comment]
This PR still shows CLA pending, and CLA not signed.  Please update the branch used in this PR.  Thanks.

**Comment by rajeevnaikte** [comment]
When i was trying to do squash of all commits, it merged into single commit with committer name 'Rajeev Naik', but my username is rajeevnaikte. Can we delete this branch so that i can create new branch and raise new PR?

**Comment by ichernev** [comment]
@rajeevnaikte sure, you're free to abandon this and make a new one right.

**Pull request closed without merging**
