### PR TITLE
Drop ie8 yay 3288

### PR DESCRIPTION
**Pull request by rjgoldsborough**
This is a first crack at fixing #3288.

Thoughts or feedback appreciated :)

### CODE REVIEW

**Comment by maggiepint** [comment]
I appreciate your enthusiasm, but we can't take this pull at this time. It cannot come in a minor release, and we haven't got our game plan with v3 yet. As such, we don't know if we will need to do another 2.* release (we probably will). I'm closing this, but I would be happy to recruit you to help us with our V3 work, including the transition to an immutable API, in the next couple weeks as we get a game plan to move forward.

**Comment by rjgoldsborough** [comment]
Ah, cool. Thanks.

And sounds good. Do y'all discuss that stuff on github or irc/etc?

**Comment by rjgoldsborough** [comment]
And if anyone does have a second or two to peek at this, that would be great. 

Mostly curious if it would pass as it's my first PR to moment.

But, if not I also completely understand :)

**Comment by mj1856** [comment]
We have a public Gitter page [here](https://gitter.im/moment/moment) if you want to chat about it more.   The core team also discusses these things privately on Slack.   We do intend to remove IE8 support, but only in an upcoming v3 branch, along with a bunch of other changes.  We're still working on a roadmap with details.

The PR itself is fine.  I'd want to be a bit more thorough to make sure we aren't leaving any other quirks in, but those items you submitted would indeed be removed.  Just not in the current codebase.

Stay tuned. :)

**Comment by rjgoldsborough** [comment]
Cool. I'll check it out.

And yeah, I didn't figure it was 100% perfect but mostly curious of the deletions so far.

Thanks again, and I'll keep an eye out.

**Pull request closed without merging**
