### PR TITLE
Update ta.js

### PR DESCRIPTION
**Pull request by krishnakumar03**
Updated the number format in tamil when tamil locale is chosen

### CODE REVIEW

**Comment by mj1856** [comment]
@tk120404 can you please review?  Thanks.

@krishnakumar03 - please add some unit tests that match the changes.  Thanks.

**Comment by mj1856** [comment]
@krishnakumar03  - Also, you've edited the wrong file.  Please make changes to files under `/src` only.  Specifically, you should edit `/src/locale/ta.js` and `/src/test/locale/ta.js`.  Please apply the edits to the correct files and rebase.  See the [Contributing Guide](https://github.com/moment/moment/blob/develop/CONTRIBUTING.md) for more info.

**Comment by ichernev** [comment]
@krishnakumar03 also your change doesn't actually change any behavior. You need a preparse and postformat methods.

`ar` `bo` `hi` locales are examples.

**Comment by krishnakumar03** [comment]
Thank you and sry for the late replies

I change those and send a pull req soon

Thank you

**Comment by tk120404** [comment]
@krishnakumar03 I think it will better if we add these changes to a different file and giving the option to the end user to select between these files, as most of them will not be aware of the tamil numbers.

**Comment by krishnakumar03** [comment]
Hey arjun,
Thanks for suggestion and that looks like a good idea...
But my opinion would be like it should be only in Tamil. So that the
unknown peoples will come to know about the numeral and they will learn

Thank you
Krishnakumar S.

**Comment by ichernev** [comment]
Close in favor of #2785

**Pull request closed without merging**
