### PR TITLE
Change Malay language code to comply IOS639-2

### PR DESCRIPTION
**Pull request by wajatimur**
According to ISO 639-2 Malay language code/tag is 'ms' please refer [here](http://www.loc.gov/standards/iso639-2/php/code_list.php).

### CODE REVIEW

**Comment by cvrebert** [comment]
Typo in the commit message: "IOS" [sic] instead of "ISO"

**Comment by ichernev** [comment]
@wajatimur you have to change rename/change the source file `src/locale/ms-my.js` and the corresponding test `src/test/locale/ms-my.js`.

**Comment by wajatimur** [comment]
Changed the required files.

**Comment by ichernev** [comment]
Merged in 779eab554d6af2186496a8743729da3cf85196a3

**Pull request closed without merging**
