### PR TITLE
Update Malay translations

### PR DESCRIPTION
**Pull request by od3n**

### CODE REVIEW

**Comment by ichernev** [comment]
@weldan can you please comment on this change.

**Comment by weldan** [comment]
He is right. It should be Tengah Hari (noon) instead of Tengahari.

**Comment by ichernev** [comment]
@od3n you have to change `src/locale/ms-my.js` an `src/locale/ms.js`, also update tests in `src/test/locale/ms-my.js` and `src/test/locale/ms.js`. Also make it backwards compatible (so it supports parsing strings generated with the older version), and case insensitive, because `Tengah Hari` looks like the correct one, and you're using `tengah hari`, not to mention your parse function does not handle it (it handles it without a space).

**Comment by mj1856** [comment]
Ping @od3n

**Comment by Oire** [comment]
@od3n, any update on this?

**Comment by maggiepint** [comment]
@od3n we are closing this as it has been stale for quite a while. If you make the requested changes, we would be more than happy to re-open the pull request and get your changes merged. Thanks again for contributing!

**Pull request closed without merging**
