### PR TITLE
add locale for Yoruba, Nigeria

### PR DESCRIPTION
**Pull request by andela-batolagbe**

### CODE REVIEW

**Comment by mj1856** [comment]
We use [ISO 639](https://www.loc.gov/standards/iso639-2/php/code_list.php) language codes (primarly 639-1, unless only a 639-2 code exists).  The correct language code for Yoruba is `yo`, not `yb`.

Also, there's no need to qualify with an ISO 3166 country code unless there are multiple variations.  Since Yoruba is primarily spoken in Nigeria, and we have no other dialects of Yoruba in our data, then you can simply use `yo` instead of `yo-ng`.

**Comment by mj1856** [comment]
Please make the necessary changes and rebase.  Thanks.

**Comment by andela-batolagbe** [comment]
Thanks @mj1856, I will rebase once I made the changes.

**Comment by mj1856** [comment]
LGTM.  Please rebase to single commit, and I'll stage it for the next release.

Thanks!

**Pull request closed without merging**
