### PR TITLE
German words for today/yesterday/tomorrow should not be capitalized

### PR DESCRIPTION
**Pull request by mik01aj**
Grammar ref: http://www.duden.de/sprachwissen/rechtschreibregeln/Gro%C3%9F-%20und%20Kleinschreibung

The original authors of these (`de` and `de-at`) translation are: @lluchs @Oire @MadMG

### CODE REVIEW

**Comment by lluchs** [comment]
Right. These are capitalized for consistency with the [English default strings](https://github.com/moment/moment/blob/develop/src/lib/locale/calendar.js). Note that in English, these words aren't usually capitalized either.

As multi-language/locale applications are common, we shouldn't change this to prevent surprises.

**Comment by mik01aj** [comment]
>we shouldn't change this to prevent surprises.

On the other hand, de-capitalizing the date for using within a sentence is hard, because in German, you never know whether it's right to do so. And English doesn't have this problem.

And, btw, does anyone know *why* are the English strings capitalized in the first place?

**Comment by mj1856** [comment]
AFAIK, they're capitalized so they can be used outside of a complete sentence.  If one wants to use them within a sentence, then they can easily call `toLowerCase()` on it.

They should only be lower-cased in the language file if one would *never* capitalize it, even when standing alone.  I'm not sure if that is the rule for German or not.

**Comment by mik01aj** [comment]
I'll quote my [comment](https://github.com/moment/moment/issues/2192#issuecomment-113085510):

>Imho it is better NOT to have titlecase than to have it, because it is always safe to make the first character uppercase, and the opposite is not true.

>If the locale uses lowercase, then:
>* I can use  `calendar()` at the beginning of a sentence by making the first char uppercase. (*)
>* I can use  `calendar()` within a sentence.

>If the locale uses titlecase, then:
>* I can use  `calendar()` at the beginning of a sentence.
>* I can use  `calendar()` within a sentence by manually identifying the relevant strings (this can be hard) and making their first char lowercase. (*)

>(*) As far as I know. See https://en.wikipedia.org/wiki/Capitalization for more details.

>Possibly, it might make sense to decide about it on pre-locale basis. Each locale should document its decision then.

**Comment by ichernev** [comment]
The capitalization has always been a tricky one. You can really know whether it's inside or begining of sentence, because its just a placeholder in some translation system put there by a translator.

So these translations are a) to be used standalone b) to be used by a person knowing the language in any way he pleases.

If majority of web sites and apps use lowercase for these in stand alone applications I'd merge it. In USA people like to capitalize stuff to make it look special, so I won't base my decision on that.

**Comment by ichernev** [comment]
Merged in da969bfba78d743073895ef7b8cb83dac299395c

**Pull request closed without merging**
