### PR TITLE
Update pl.js

### PR DESCRIPTION
**Pull request by eximius313**
fixed typos
https://pl.wikipedia.org/wiki/Sobota
https://pl.wikipedia.org/wiki/Niedziela

### CODE REVIEW

**Comment by ichernev** [comment]
@evoL  what do you think.
@eximius313 you need to change `src/locale/pl.js` and update `src/test/locale/pl.js`. `locale/pl.js` should not be changed because its autogenerated.

**Comment by eximius313** [comment]
https://github.com/moment/moment/pull/3365
https://github.com/moment/moment/pull/3366

**Comment by evoL** [comment]
The change is alright, thank you!

However, I think it would make more sense if you'd just update this PR instead of creating two more that break their builds on their own.

**Comment by eximius313** [comment]
I used GitHub editor. How can I change it? or maybe you could accept 2 PRs?

**Comment by ichernev** [comment]
Closing this in favor of #3365

**Pull request closed without merging**
