### PR TITLE
[feature] Add moment().toRFC2822String() method

### PR DESCRIPTION
**Pull request by TracyGJG**
Original submission error-ed but did not fail.

### CODE REVIEW

**Comment by ovangle** [comment]
This needs typescript declarations.

**Comment by TracyGJG** [comment]
@ovangle could you please elaborate on what you think needs to be done. I know what typescript is but I am not sure what 'declarations' are and where they need to be created.

**Comment by ovangle** [comment]
In the file `moment.d.ts` at line 542 you need to add the method declaration

    toRFC2822String(): string;

so that typescript users don't get a `method not found` type error when they try to call your method.

**Comment by TracyGJG** [comment]
Thanks for the help. PR submitted.

**Comment by ovangle** [comment]
No problems :)

**Comment by ichernev** [comment]
@TracyGJG this change also changes same thing as https://github.com/moment/moment/pull/3938/files, so they should either be merged into one or made independent.

**Comment by ichernev** [comment]
@TracyGJG ok, I told you to split them :) but you left the from-string.js changes in here, which are not necessary, which is what confused me.

**Comment by TracyGJG** [comment]
Pull Request withdrawn.

**Pull request closed without merging**
