### PR TITLE
Add back missing units in UnitOfTime

### PR DESCRIPTION
**Pull request by tngan**

### CODE REVIEW

**Comment by ondrejsevcik** [comment]
Hi, i've found that there is still `isoWeek` missing
http://momentjs.com/docs/#/manipulating/start-of/

**Comment by ichernev** [comment]
Close in favor of #3490

**Comment by ichernev** [comment]
Well, actually we have a bug because of this lower case madness.

**Comment by ichernev** [comment]
Hm, its not a bug, but I hate that. Anyway -- I'm not adding all variations of upper/lower letters that somebody might want to use.

**Pull request closed without merging**
