### PR TITLE
[locale] ko: Add trailing dot to L and l

### PR DESCRIPTION
**Pull request by marwahaha**
fixes https://github.com/moment/moment/issues/4070

### CODE REVIEW

**Comment by marwahaha** [comment]
@YenalTuran - is the trailing dot ever _not_ present?

**Comment by YenalTuran** [comment]
@marwahaha  it is present only after year and month, but not day.

**Comment by marwahaha** [comment]
@YenalTuran 
* how often do you use the format `2017.12.29` ?
* how often do you use the format `2017.12.29.` ?

**Comment by YenalTuran** [comment]
@marwahaha currently we show our Korean customers their logistics' booking dates in 2017.12.29 format, but since the correct format is 2017.12.29. I would like to use moment library (without any workaround) and show the expected format :) many thanks for your support!

**Pull request merged**
