### PR TITLE
Update moment.js

### PR DESCRIPTION
**Pull request by Hypercubed**
Small change avoids minification bugs.

### CODE REVIEW

**Comment by ichernev** [comment]
Now we generate all files from ES6 modules. Should we add this to all bundles?

**Comment by ichernev** [comment]
@Hypercubed I couldn't find on the internet a reliable source of whether this is good or bad practice. It might break some old browsers : http://stackoverflow.com/a/12319804/235253

So I'm not sure we need it yet. Please provide more proof that it is a good thing, and then modify the headers we use for the bundles (all code is now transpiled from es6 modules).

**Comment by mj1856** [comment]
In particular, please provide an example of how *not* having it creates a minification bug.  Thanks.

**Comment by Hypercubed** [comment]
In some cases concatenating and minimizing will result in a bug.  For example the following:

```
var b = 7
var a = 3 + b   // another modules's code
(function(global, factory) {/* moment.js */} )
```

Will compress to:

```
var b=7,a=3+b(function(global, factory) {/* moment.js */});
```

Which would give a "b is not a function" error.

I admit this is not `moment.js`'s fault.  You can blame the other library for not using the "optional" semicolons or you can blame the minification tool.  But it does come up sometimes... as it did for me.

**Comment by ichernev** [comment]
Close in favor of #2739

**Pull request closed without merging**
