### PR TITLE
Improved Hebrew locale

### PR DESCRIPTION
**Pull request by danielgindi**

### CODE REVIEW

**Comment by icambron** [comment]
@danielgindi - Thanks for the contribution. You'll need to change the tests too, though.

@TalAter - can you comment on these changes?

**Comment by danielgindi** [comment]
I have added tests, and removed the changes to ordinals. Using ordinals in native language in Hebrew breaks "normal" format strings as the ordering of words is incorrect.

**Comment by TalAter** [comment]
@danielgindi - Not sure I love the use of אחה״צ ולפנה״צ... Leads to some weird sounding times like `11:55 אחה״צ` and `2:00 לפני הצהריים` (loosely translated: `11:55 afternoon` and `2:00 before noon`).

Problem is, I can't think of a better solution.

I'm missing context on the issue here, but would having more than two cases make sense?
Something like:
* 0-4 -> `אחר חצות` (loosely translated: 2:22 past midnight)
* 5-10 -> `בבוקר` (loosely translated: 8:22 in the morning)
* 11-12 -> `לפנה״צ`
* 13-17 -> `אחה״צ`
* 18-23 -> `בערב`

**Comment by TalAter** [comment]
@danielgindi - Not sure I love the use of אחה״צ ולפנה״צ... Leads to some weird sounding times like `11:55 אחה״צ` and `2:00 לפני הצהריים` (loosely translated: `11:55 afternoon` and `2:00 before noon`).

Problem is, I can't think of a better solution.

I'm missing context on the issue here, but would having more than two cases make sense?
Something like:
* 0-4 -> `אחר חצות` (loosely translated: 2:22 past midnight)
* 5-10 -> `בבוקר` (loosely translated: 8:22 in the morning)
* 11-12 -> `לפנה״צ`
* 13-17 -> `אחה״צ`
* 18-23 -> `בערב`

**Comment by danielgindi** [comment]
Yes, it seems like the traditional English AM/PM is not fit for Hebrew, your suggestions seem valid.

Although `אחר חצות` is a bit weird, maybe `לפנות בוקר`?

**Comment by TalAter** [comment]
Sounds good :+1:

**Comment by danielgindi** [comment]
Done, I'll just rebase and squash those commits

**Comment by icambron** [comment]
This one is ready to go, @ichernev

**Comment by ichernev** [comment]
Merged in 05775fea38fe1b6d47e1bf2ed536cc94e990236b

**Pull request closed without merging**
