### PR TITLE
Updating "ss" threshold localization to pt-br

### PR DESCRIPTION
**Pull request by rentalhost**
Following #3738.

### CODE REVIEW

**Comment by maggiepint** [comment]
Can you change this to only modify the file in the /src folder? The other one is a built file. @caio-ribeiro-pereira what do you think?

**Comment by rentalhost** [comment]
@maggiepint Done!

**Comment by ichernev** [comment]
@rentalhost can you please add a test for `ss` in `src/test/locale/pt-br.js`.

**Comment by rentalhost** [comment]
@ichernev I checked and seems that it is not tested "_for each locale_", but globally (just at `src/test/moment/relative_time.js`). Have you sure that I should add a specific test for this locale? I could do without problem, but I think that it should be done for each language too.

**Comment by rentalhost** [comment]
Anyway, I have created the tests and rebased to master (too fixed a small issue, thanks for tests hehe).

**Comment by ichernev** [comment]
Merged in 8f75a05a3606728b5f19108cfade8d163b7283b8

**Pull request closed without merging**
