### PR TITLE
Add scots gaelic (gd) support

### PR DESCRIPTION
**Pull request by jonashdown**
This PR is to add Scots Gaelic (gd) support to moment.js

- [x] modifies parser to accept Gaelic months
- [x] include Scots Gaelic Language file
- [x] includes Scots Gaelic unit tests

### CODE REVIEW

**Comment by ichernev** [comment]
@jonashdown looks good. I'll merge in next release. Can you please remove the `.gitignore` additions. You can use `.git/info/exclude` for non-commitable git exclude patterns. There are thousands of editors out there, I don't want a line for each one in the .gitignore.

**Comment by jonashdown** [comment]
@ichernev This is good news. I have removed the extra entries in the .gitignore file as requested. Will you inform me when the merge goes ahead as so my team can switch back to using the official version ?

**Comment by ichernev** [comment]
Monitor https://mobile.twitter.com/momentjs

**Comment by ichernev** [comment]
Merged in 0a01d890b471508fd4d3a7d4cccac0d254393518

**Pull request closed without merging**
