### PR TITLE
[locale] eo: corrections

### PR DESCRIPTION
**Pull request by colindean**
Unified Esperanto updates. 

Dankon, @Vivakvo!

Closes #5343
Closes #5455 
Closes #5456

### CODE REVIEW

**Comment by Vivakvo** [comment]
Dankon @colindean 

I received this message from github:
Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our Contributor License Agreement before we can accept your contribution.
1 out of 2 committers have signed the CLA.

✅ Vivakvo
❌ colindean

Are you OK about that?

**Comment by colindean** [comment]
> Are you OK about that?

Yes. This repository features an automation system that checks CLA signers and then updates the comment once everyone has signed. Editing comments doesn't generate an email. You can see the edited comment [here](https://github.com/moment/moment/pull/5457#issuecomment-618759413).

**Comment by Vivakvo** [comment]
@colindean 
There is still an unsuccessful check (continuous-integration/travis-ci/pr but I don't understand what it is about. Is it going to stop the process?

**Comment by colindean** [comment]
Hold off on merging. I need to correct (remove) the accusative on the short day name per [@Vivakvo's comment](https://github.com/moment/moment/pull/5343#issuecomment-618865879).

**Comment by colindean** [comment]
> Is it going to stop the process?

Yes. I'm not sure what that build failure is about but one of the maintainers will be able to tell us. The tests regarding the locale seem to pass…

**Comment by colindean** [comment]
This is ready now: passing all tests.

@Vivakvo, please indicate your approval by navigating to https://github.com/moment/moment/pull/5457/files and indicating your approval using the **Review Changes** feature at the green button in the upper right corner?

**Comment by ichernev** [comment]
@colindean thank you for the expedited work!

I noticed you talked about nominative/accusative. If Esperanto has both cases, then you should use standalone/format versions, like here: https://github.com/moment/moment/blob/develop/src/locale/ru.js#L36

Let me know if this is ready to merge regarding ^^

**Comment by colindean** [comment]
@ichernev It's probably sufficient to merge now. I'll look at the 🇷🇺 locale and find some others that have accusative for inspiration on an improvement.

**Comment by Vivakvo** [comment]
> @Vivakvo, please indicate your approval by navigating to https://github.com/moment/moment/pull/5457/files and indicating your approval using the **Review Changes** feature at the green button in the upper right corner?
@colindean I put my approval using this button "Review changes". I hope it's OK.
Thank you very much for your help.
How will I know when it will be operational?

**Comment by colindean** [comment]
I don't know when Moment's next release will be. That will be the next release that has these changes. 

If you made this change because you noticed a problem in software that you were using, then it may be a while before that changes effective. Moment won't have control of when that software gets the newer version.

Thanks for helping out! I learned a bit, too!

**Comment by Vivakvo** [comment]
Yes, I made this change because effectively there are some little problems about dates in the program I use in its Eo-version (I have translated it from french). 
This program is named Cesium and deals with the free money Ğ1. Have you heard about it? Ekzistas mallonga artikolo en Esperanto, kiu iom klarigas la aferon: [https://komun.org/eo/g1-libera-mono](https://komun.org/eo/g1-libera-mono). This free money is born in France 3 years ago, but it could become international.

I well know the developer of that program (also usable [here](https://g1.duniter.fr/#/app/home)) and I will tell him to use the new moment.js when it will be ready.

Bye!

**Comment by colindean** [comment]
The Cesium project appears to use the [latest version of Moment](https://git.duniter.org/clients/cesium-grp/cesium/-/blob/master/package.json#L70) so I speculate that they will keep up and get the new changes shortly after release.

I've not heard about Cesium but I am very interested in cryptocurrency. Thanks for the links. I'll look into it!

Gxis la!

**Pull request merged**
