### PR TITLE
Add localeSorted argument to weekday listers

### LINKED ISSUE #2927: Locale-aware moment.weekdays* methods
How do I get list of weekdays in proper locale-aware order?

### PR DESCRIPTION
**Pull request by ichernev**
Fixes #2927, redo #3103

### CODE REVIEW

**Comment by Changron** [comment]
what is the last parameter "setter" of function get for, btw?
I don't really get it when I implemented it.

**Comment by ichernev** [comment]
@Changron its used to set the given unit to the given value, so you have a moment whoose unit is value (weekday is 5), so you can get the name of it in the locale ...

**Comment by ichernev** [comment]
Merged in 1a460a95bc60c72cb663f295c4dbcf75c13d8862

**Comment by desfero** [comment]
@ichernev do we have such option to moment local locale?

Something like this below does not work.
```
moment().locale('pl').localeData().weekdays(true) 
```

**Pull request closed without merging**
