### PR TITLE
Korean long date fix

### PR DESCRIPTION
**Pull request by bigtone1284**
@jeeeyul , @kyungw00k, @maggiepint , @kyungw00k , please review this pull request when you can.  its to resolve the korean long date formatting issue.  I used to live in Busan, Korea, speak Korean a little bit and felt compelled to pitch in here.  Here is the issue: #3222

### CODE REVIEW

**Comment by kyungw00k** [comment]
@bigtone1284 I think it looks fine. 👍

**Comment by colus001** [comment]
I was about to make an another PR. I think `1분` represent better than`일분`. What do you guys think?

**Comment by maggiepint** [comment]
@colus001 that isn't the same as this right? Seems like this code is good to go either way.

**Comment by maggiepint** [comment]
Actually @bigtone1284 can you get rid of the change to the /locale file? We only want the files in the /src directory modified. If you don't mind rebasing it out that would be appreciated.

**Comment by colus001** [comment]
I thought it can be part of the pr since this is about korean language. I'll make another pr related to the issue. @maggiepint

**Comment by bigtone1284** [comment]
@maggiepint I removed my changes from /locale and kept only my changes within /src.

**Comment by mj1856** [comment]
Please rebase this to a single commit.  Thanks.

**Comment by bigtone1284** [comment]
Please  find the edited pull request at this pull request: #3350

**Comment by mj1856** [comment]
Thanks, but FYI - you don't need to open a new PR, you can just rebase the existing one.  See [How to Rebase a Pull Request](https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request)

**Pull request closed without merging**
