### PR TITLE
[locale] ar-sa: Change start of week from Saturday to Sunday

### PR DESCRIPTION
**Pull request by ichernev**
Redo #3261

### CODE REVIEW

**Comment by ichernev** [comment]
Well, it should be rewritten again to be Friday.

@kifcaliph Friday is the start of the week, right?

**Comment by ichernev** [comment]
@xsoh hey, can you look at #3352 
So is it Friday or Sunday? I'm so confused :)

**Comment by ichernev** [comment]
Merged in eb1db7c32e61fdcf47309fd9170e67903dc3a3d9

**Comment by xsoh** [comment]
@ichernev sorry for late, and yes the start of week is Sunday in Saudi Arabia `ar-SA`

**Pull request closed without merging**
