### PR TITLE
[new locale] (kz) Added Chinese Kazakh language

### PR DESCRIPTION
**Pull request by programmer-xiaosa**
There are two Kazakh scripts in the world. Currently, there are Kazakh language packs in Kazakhstan. This time, the Chinese Kazakh language pack is added.

### CODE REVIEW

**Comment by Musa920** [comment]
Guys, where is the problem？

**Comment by Musa920** [comment]
> [Coverage Status](https://coveralls.io/builds/31112332)
> 
> Coverage remained the same at 88.496% when pulling **[6e30e95](https://github.com/moment/moment/commit/6e30e954db0c498fb551b112964ee1cf4db044fa) on Musa920:develop** into **[82d6c1a](https://github.com/moment/moment/commit/82d6c1ac43125ec6cf5640a440d72c8b83e09f6b) on moment:develop**.
where is the problem？

**Comment by marwahaha** [comment]
Hi @Musa920 thanks for the contribution. Please edit `src/locale/kz.js`. Please do not edit `locale/kz.js`.

Thanks again.

**Comment by talgautb** [comment]
@Musa920 please don't use `kz.js` as language, use `kk-ch.js` (chinese kazakh)

**Comment by marwahaha** [comment]
@Musa920 any updates?

**Comment by ichernev** [comment]
Closing this for inactivity. Re-open if you add the code to the right place (under `src/`).

**Pull request closed without merging**
