### PR TITLE
locale/ko: update some spacing and awkward phrases

### PR DESCRIPTION
**Pull request by hibiyasleep**
There was some spacing problems like '일분' (oneminute) and little awkward pharses, so fixed them. tests included.

### CODE REVIEW

**Comment by ichernev** [comment]
@kyungw00k what do you think?
@hibiyasleep you should rebase on latest develop. Check https://github.com/moment/moment/blob/develop/CONTRIBUTING.md for more info.

**Comment by leehankyeol** [comment]
@hibiyasleep "지난주" doesn't have a problem because ["지난주"](http://dic.daum.net/word/view.do?wordid=kkw000240780&q=%EC%A7%80%EB%82%9C%EC%A3%BC) is a word itself. Also, as far as we have "n개월" as sequences I think it's better to use "1개월" not "한 달". Finally I think "방금 전에" sounds more natural than "잠시 전에".

**Comment by kyungw00k** [comment]
@leehankyeol :+1:

**Comment by hibiyasleep** [comment]
@leehankyeol '방금 전' is fine, but '방금 후' is weird.
```js
// locale/ko.js:39
        relativeTime : {
            future : '%s 후',
            past : '%s 전',
            s : '방금',
```

**Comment by ichernev** [comment]
@hibiyasleep it was a long time ago, but 1) did you fix all comments in https://github.com/moment/moment/pull/2177#issuecomment-96501182
2) you need to make the changes on top of latest develop and also properly update the tests (now it looks like you're adding a new test file). https://github.com/moment/moment/blob/develop/CONTRIBUTING.md

**Comment by ichernev** [comment]
Closing for now. Please rebase on latest develop.

**Pull request closed without merging**
