### PR TITLE
correct typo in min/max deprecation warnings

### PR DESCRIPTION
**Pull request by maggiepint**
It would be better that we suggest people use min to find the min, and max to find the max.

### CODE REVIEW

**Comment by mj1856** [comment]
Actually, it's intentional.  The order is swapped.  The docs have it correct, but we used to have the deprecation messages wrong. See #2946, which just went in with 2.12.0.

Maybe we could find a better way to phrase it.

**Comment by maggiepint** [comment]
Well, it was found while I was writing docs about deprecation warnings, so I'll certainly fit that in.

**Comment by mj1856** [comment]
The old functions, the ones we deprecated, were not intuitive.  You'd think `max` would return the later of the two moments, which it does now.  But the old function would return the earlier of them.  

The idea with the old ones was a maximum *constraint* - meaning "return me the value that is no larger than this one".

**Comment by maggiepint** [comment]
Well... I'm glad that is deprecated.

**Pull request closed without merging**
