### PR TITLE
[locale] pt: Fix capital letters in weekdays

### PR DESCRIPTION
**Pull request by horus68**
In Portuguese (Portugal) weekdays are in lowercase. So its required that working days will be like `Segunda-feira` not as the actual value `Segunda-Feira`

For those on grammar:
Even the first capital letter is only Ok when in a single word or the first word in a sentence. Regular usage (in the middle of a sentence) it would be all in lowercase.
But we can't control here when it will show one way or the other, so the initial capital letter!

Reference: https://ciberduvidas.iscte-iul.pt/consultorio/perguntas/meses-e-dias-da-semana-outra-vez/3743

### CODE REVIEW

**Comment by ichernev** [comment]
@jalex79  what do you think

@horus68 you need to update tests in `src/test/locale/pt.js`.

**Comment by horus68** [comment]
@ichernev done

**Comment by marwahaha** [comment]
@horus68 - there's a small conflict - could you resolve it?

**Comment by horus68** [comment]
@marwahaha I tried to fix the conflict but now Travis failed.
I don't have the knowledge to fix this!

**Comment by marwahaha** [comment]
I made a change @horus68 - it looked like one test got adjusted. A few thoughts:
* do we have confirmation from @jalex79 ?
* should all months be lowercase, also?

**Comment by jalex79** [comment]
In the middle of a sentence, the names of the days of the week are in lower case (domingo, segunda-feira, ..., sábado). But in bonds, and obviousness, at the beginning of sentences, is capitalized.

**Comment by marwahaha** [comment]
Ok, great. 

@horus68 / @jalex79 , last question:
* If Months and days of the week are treated similarly, should they all be lowercase?
 For example, like this. https://github.com/moment/moment/blob/develop/src/locale/lt.js#L52-L60

**Comment by marwahaha** [comment]
Ok, I will merge it as is.

**Pull request merged**
