### PR TITLE
[build] Use rollup and babel instead of esperanto for transpiling

### PR DESCRIPTION
**Pull request by ichernev**
This gets rid of the annoying deprecation warning. It also makes the build slower ... I think its a conspiracy with computer vendors ;-)

The transpiling is done slightly cleaner now. Unfortunately we still need to hack the headers for a lack of customizability on rollup's part.

### CODE REVIEW

**Comment by ichernev** [comment]
Apparently rollup.js does not work on node 0.10. Should we stop testing on it, or hack around so only the shipped version is tested (without transpiling).

**Comment by ichernev** [comment]
Lets see: https://github.com/rollup/rollup/issues/1095

**Comment by maggiepint** [comment]
Stop testing Node 0.10. It left extended support last week. It's dead.

**Comment by ichernev** [comment]
Merged in a4de1cadfa2b37144bff93a656148b6a5fab72ab

**Pull request closed without merging**
