### PR TITLE
[new locale] add en-in: English (India) locale

### LINKED ISSUE #4012: Missing locale 'en-IN'?
I installed moment@2.18.1 and was looking through the locales available. I assumed there was an en-in locale. Upon further inspection, I only saw these en locales:

en-au
en-ca
en-gb
en-ie
en-nz

Am I missing something? Just for an example for 'en-IN', 'l' date-format should give 'dd/MM/yyyy' but it's giving 'MM/dd/yyyy', may be the default one. If there was a file for 'en-in', it would have been there in longDateFormat. Please suggest.

I'am using it like this - 
var formattedDate = moment(dateInput).locale(locale).tz(timezone).format(momentFormat);
e.g. var formattedDate = moment( 1497260107000 ).locale( "en-IN" ).tz( "Asia/Calcutta" ).format( "l LT" );

Above expression gives me result in mm/dd/yyyy h:mm AM/PM format where I was expecting in dd/mm/yyyy h:mm AM/PM where it's giving correct result for 'en-gb' or 'en-au' because corresponding locale files are available.

### PR DESCRIPTION
**Pull request by kumarharsh**
Closes #4012

### CODE REVIEW

**Comment by kumarharsh** [comment]
@marwahaha ping

I also see a bunch of other languages (esp Indian) pending PR due to some extra work which needs to be done - can I clean 'em up and submit a PR?

**Comment by marwahaha** [comment]
Hi @kumarharsh - Thanks for this. If you'd like to work on other Indian languages, that sounds great.

**Comment by kumarharsh** [comment]
Updated some comments in the `en-in` file which were confusing. It's ready for merge I guess.

**Comment by kumarharsh** [comment]
@marwahaha ping?

**Comment by marwahaha** [comment]
@kumarharsh Your tests are failing:
```
Module: locale:en-in Test: format
w wo ww ---> 7 7th 07
    at Object.<anonymous> (/home/travis/build/moment/moment/build/umd/test/locale/en-in.js:305:20)
Actual value:
8 8th 08
Expected value:
7 7th 07
```

Also, what are you changing with the `pa-in` locale? Was that requested somewhere?

Please do not make other changes.

**Comment by ichernev** [comment]
en-in was merged in d9913b2640a0c2b34b191640aeaa9d40ea379cc3

To be fair it differs from this one in both the AM/PM and dow/doy values... You might submit a PR with the changes, but make sure to include some proof of these claims from official sources.

**Pull request closed without merging**
