### PR TITLE
Create ur.js

### PR DESCRIPTION
**Pull request by yethrosh**
Please add Urdu language translation which i have commited.

### CODE REVIEW

**Comment by mj1856** [comment]
Please read the [contributing guidelines](https://github.com/moment/moment/blob/develop/CONTRIBUTING.md) and create files under `/src` instead.  Don't forget unit tests please.

**Comment by ichernev** [comment]
@yethrosh any progress on this?

**Comment by narainsagar** [comment]
Hello, I want to contribute for urdu language so, can I continue with this PR and complete this?

Thanks.

**Comment by maggiepint** [comment]
@narainsagar go for it. Looks like this one isn't going to be moved ahead so we're happy to have someone else do it.

**Comment by narainsagar** [comment]
@yethrosh let me know if you're writing tests for this & update this PR? otherwise I have started on it.. 

FYI: I will be keeping your name in the authors list as well because I am (somehow) using your written ur.js code from this PR..

Thanks.

**Comment by narainsagar** [comment]
**FYI:** @maggiepint I was off for few weeks and Looks like someone had already taken this on #3641 and it looks quite good to me as well.  So I think better to continue with that..

And @maggiepint, I've opened a new PR for sindhi translation support on #3659.

Cheers,

**Comment by maggiepint** [comment]
Closing due to new PRs

**Pull request closed without merging**
