### PR TITLE
[locale] az: Improve relative time for seconds

### PR DESCRIPTION
**Pull request by javid-yagubali**
"Saniyə" sözündə orfoqrafik səhv

Orthographic error in translation of th word "second"

### CODE REVIEW

**Comment by javid-yagubali** [comment]
https://azerdict.com/orfoqrafiya/saniy%C9%99

**Comment by ichernev** [comment]
@topchiyev any comments

**Comment by ichernev** [comment]
@javid-yagubali you need to change `src/locale/az.js` and `src/test/locale/az.js`.

**Comment by marwahaha** [comment]
Thanks for your contribution @javid-yagubali - but you need to edit the files in `src/`.

@topchiyev - can you confirm this correction?

**Comment by javid-yagubali** [comment]
I'm not a regular user of github. Just noticed a small typo, decided to inform. I don't even know how to contribute. Sorry.

@topchiyev, thanks for your effort.

in file src/locale/az.js line 55 (ss : '%d saniyə',) is correct. line 54 (s : 'birneçə saniyyə',) is not, there is one extra 'y' in there. 

in file src/test/locale/az.js every word "second" has one extra 'y' in it. just search and replace "saniyyə" with "saniyə". 

Sorry for really late response. Thank you for this amazing library.

**Comment by marwahaha** [comment]
Closing in favor of #4527

**Pull request closed without merging**
