### PR TITLE
Update ko.js

### PR DESCRIPTION
**Pull request by JunhoKim01**
relativeTime 일부 맞춤법 수정  // Correct relativeTime strings based on Korean grammar checker (http://speller.cs.pusan.ac.kr/PnuSpellerISAPI_201504/) 

1. 몇초 --> 몇 초
2. 한시간 --> 한 시간 
3. 한달 --> 한 달
4. 일년 --> 일 년

@kyungw00k  Please check this

### CODE REVIEW

**Comment by mj1856** [comment]
Thanks, but please read the [contributing guidelines](https://github.com/moment/moment/blob/develop/CONTRIBUTING.md), then edit the `src/locale/ko.js` and `src/test/locale/ko.js` files instead.

The file you edited, `locale/ko.js` is autogenerated from the source files during the build process.

**Comment by mj1856** [comment]
@kyungw00k - Please review the proposed changes.  Thanks.

**Comment by JunhoKim01** [comment]
I just committed "Update ko.js #2, #3" which follows 'contributing guidelines', so review this please :) 
@kyungw00k

**Comment by kyungw00k** [comment]
@JunhoKim01 Thanks!
@mj1856 I just have reviewed the commit, it has no problem to merge.

**Comment by Oire** [comment]
@mj1856, this seems to be ready to merge but it still shows 3 changed files (including `locale/ko.js`). Should it be rebased or it is OK now?

**Comment by maggiepint** [comment]
@JunhoKim01 we need this to be rebased into one commit. In addition, please remove the changes to locale/ko.js

Thanks!

**Comment by JunhoKim01** [comment]
@maggiepint  Done! Thanks a lot :)

**Comment by ichernev** [comment]
Merged in 126c59282008fdd4c9b61fb4feaadba4a5e1d992

**Pull request closed without merging**
