### PR TITLE
en-NZ locale, values from windows locale settings

### PR DESCRIPTION
**Pull request by lukemcgregor**

### CODE REVIEW

**Comment by mj1856** [comment]
How is this different than the existing `en-AU` locale?

**Comment by mj1856** [comment]
@ichernev - Is #2551 supposed to cover identical locales as well?  In this case, `en-AU` and `en-NZ` should both be handled by the `en-AU` file.

**Comment by lukemcgregor** [comment]
Its identical to AU

**Comment by ichernev** [comment]
@mj1856 locale inheritance is intended for external use only. Today they are the same, tomorrow somebody will come with a patch to fix an obscure case. I think we supported aliases of locales some time ago, but not after the rewrite. This is fine.

**Comment by ichernev** [comment]
Merged in bca1f3df881db059e80f8571a22e7dff197b042c

**Pull request closed without merging**
