### PR TITLE
[locale] th: Adjust "L" format

### PR DESCRIPTION
**Pull request by nwhittaker**
Adjust Thai localized short date format to read day/month/year (moment/moment#3692).

@sirn, 👍 or 👎?

### CODE REVIEW

**Comment by nwhittaker** [comment]
The test failures appear to be unrelated and were previously reported in #3691.

**Comment by sirn** [comment]
:+1: Looks good to me.

**Comment by icambron** [comment]
Yeah, we need to figure out what's up with the build server. That aside, @ichernev this looks good.

**Comment by maggiepint** [comment]
Closing to re-open and start the build again. #hack

**Comment by ichernev** [comment]
@maggiepint I'm not sure if its just me, but you can go in travis and click a button to reset the build if it looks fishy. But opening and closing is the poor-mans-way that works too :)

**Comment by ichernev** [comment]
Merged in 9b738aa4aa26dd6b359c68da7686b6352db972af

**Pull request closed without merging**
