### PR TITLE
[bugfix] './locale' path not found in moment/src/lib/locale/locales.js

### PR DESCRIPTION
**Pull request by ApacheEx**
seems root of issue was introduced here: https://github.com/moment/moment/commit/9ce89e7fea881b39be23b8c0646f7ef7817985d9

So, this PR reverts it and fixes the following issues:
#4505, #5472, #5497, #5501, #5500, #5378, #5495, #5506, #5508

### CODE REVIEW

**Comment by ApacheEx** [comment]
also, as possible fix:

replace `"module": "./src/moment.js"` to `"module": "./moment.js"`
but don't know exactly if this `"module"` is really needed and what was the reason to introduce it.

**Comment by J1445** [comment]
> also, as possible fix:
> 
> replace `"module": "./src/moment.js"` to `"module": "./moment.js"`
> but don't know exactly if this `"module"` is really needed at all and what was the reason to introduce it.

Can confirm this fixes #5495 the issue and you are the MVP here.  

Also commit description is not clear  in 9ce89e7

**Comment by nicolashenry** [comment]
FYI "module" is supposed to be an ecmascript module and "./moment.js" is a commonjs module.

**Comment by BoazKG93** [comment]
Having the same problem, reverted back to 2.24 until a fix is available

**Comment by BuangHosen** [comment]
> also, as possible fix:
> 
> replace `"module": "./src/moment.js"` to `"module": "./moment.js"`
> but don't know exactly if this `"module"` is really needed at all and what was the reason to introduce it.

thanks sir, you save my day 👍

**Comment by FredrikSeidl** [comment]
Can confirm that this resolves it for us. Can this be merged and released on NPM soon?

**Comment by ApacheEx** [comment]
ok guys, I see it's fixed in 2.25.2. 

So, I'm closing this.

**Comment by ApacheEx** [comment]
"module" property was removed in 2.25.3 (https://github.com/moment/moment/commit/0c709ba7e463c12c68d7bf217fbdff4ed3b46f2c) 

So, it was the right solution.

**Pull request closed without merging**
