### PR TITLE
Updated nb.js to reflect the official versions

### PR DESCRIPTION
**Pull request by sigurdga**
Updated to reflect the approved ISO standard, and abbreviations according to official rules

### CODE REVIEW

**Comment by ichernev** [comment]
@sigurdga you have to change `src/locale/nb.js` and also update the tests in `src/test/locale/nb.js`.
@rexxars what do you think?

**Comment by rexxars** [comment]
Most of these changes look good, but I'm not sure I agree with the `forrige` => `sist` change. I personally don't think it's more or less confusing, but I find it slightly less formal.

**Comment by ichernev** [comment]
@sigurdga can you add tests, change the correct file under `src/locale` and undo the `forrige` -> `sist` change.

**Comment by sigurdga** [comment]
Yes, I will. I hope to get this done during the weekend. I'm happy you picked up the thread.

**Comment by sigurdga** [comment]
@ichernev Should be good for merge now.

**Comment by ichernev** [comment]
Merged in a16c65dd688ce2027a484caa0d2d676fbbab9ef7

**Pull request closed without merging**
