### PR TITLE
moment.duration(NaN) now throws an error (issue#3225 + #3071)

### PR DESCRIPTION
**Pull request by zenvercoder**

### CODE REVIEW

**Comment by maggiepint** [comment]
Unfortunately this can't be implemented this way. It is our rule that we don't throw errors in this code. Instead, we do something like invalidating the date. To fix this, one would need to implement a way to have an invalid duration.

**Comment by maggiepint** [comment]
@ichernev @icambron @mj1856 @butterflyhug - if we were to do this, how do we want it to look? I think that there should be a way to invalidate duration just like there is with moment. That's going to propagate all over the code though.

**Comment by butterflyhug** [comment]
Agreed.  I think a `Duration.isValid` method and corresponding API support would be the right way to fix this.  Unfortunately it'll be a bit of a pain to implement.

**Comment by zenvercoder** [comment]
Dear moment authors,

We were talking about how quickly maggiepint responded. 
It only took… a moment (lol). 
I might try to tackle this problem again at some point, but it will have to wait.

I just wanted to say thank you for taking the time to respond so kindly with detail about the pull request.

-Lisa

**Comment by maggiepint** [comment]
Slack desktop notifications for pull requests:-)

**Comment by ichernev** [comment]
Yep, we need isValid and the like ... It used to be hard to produce an invalid duration. Not any more.

**Comment by maggiepint** [comment]
Closing as this implementation isn't what we want.

**Pull request closed without merging**
