### PR TITLE
Fix locale for khmer language

### PR DESCRIPTION
**Pull request by sereysethy**

### CODE REVIEW

**Comment by mj1856** [comment]
You should only modify files under `/src`.  The ones under `/locale` and `/min` are generated by the build process.  Please rebase.  Thanks.

**Comment by ichernev** [comment]
@kruyvanna what do you think?

**Comment by kruyvanna** [comment]
@ichernev: Sorry for late reply. This is looking good! please go ahead.
thanks @sereysethy for the PR

**Comment by kruyvanna** [comment]
@ichernev any update?
For me it looks good.
Thanks in advance.

**Comment by ichernev** [comment]
@kruyvanna sorry for me being late too :) I'll merge this in next release, thank you all.

**Comment by ichernev** [comment]
Merged in a21e2aac9dd04d493e46a88c2e19a97b938120cc

**Pull request closed without merging**
