### PR TITLE
[bugfix] Invalid duration gets valid when wrapping/cloning (#4323)

### PR DESCRIPTION
**Pull request by OjasM**
Fix of [Issue 4323](https://github.com/moment/moment/issues/4323).

I first wrote a test that failed as recommended by @marwahaha. Then, I made changes that make all tests, including the new one, pass.

### CODE REVIEW

**Comment by OjasM** [comment]
I have further added the bugfix for #4301. As recommended by @icambron, I have added a 'YYY' token which parses both 2 and 4 digit year strings. I have also added a corresponding 'YYY' format token that formats year into 4-digit string. I will also update the docs on momentjs.com accordingly.

**Comment by harkue** [comment]
> I have further added the bugfix for #4301. As recommended by @icambron, I have restricted the 'YYYY' parsing token to 4 digit strings in strict mode. I have also added a 'YYY' token which parses both 2 and 4 digit year strings. I have also added a corresponding 'YYY' format token that formats year into 4-digit string. I will also update the docs on momentjs.com accordingly.

I think it would be better to create a new PR about #4301 and also add a PR of documentation about the new feature `YYY` on `momentjs.com` project.

**Comment by ichernev** [comment]
@OjasM yeah, mixing up fixes for different issues together is a recepie for disaster. About `YYY`, have you seen any other library that supports such a format? We can not simply add formats lightly because someone want's to achieve some particular goal. In this particular case parsing with an array of formats is a valid solution.

**Comment by ichernev** [comment]
Merged in 1f88f6dd7164c8c7c0e3bade527a42a322cac4fc

**Comment by ichernev** [comment]
I merged only the duration part. The `YYY` part -- needs more discussion, but if we're the only people supporting it -- I won't take it.

**Pull request closed without merging**
