### PR TITLE
[new locale] ur: Urdu locale

### PR DESCRIPTION
**Pull request by ibnesayeed**
Translations in Urdu and passing unit tests are added.

```
┌───────┬───────┬────────────┬────────┬────────┬─────────┐
│ Files │ Tests │ Assertions │ Failed │ Passed │ Runtime │
├───────┼───────┼────────────┼────────┼────────┼─────────┤
│ 1     │ 2892  │ 119091     │ 0      │ 119091 │ 9282    │
└───────┴───────┴────────────┴────────┴────────┴─────────┘
Done, without errors.
```

### CODE REVIEW

**Comment by ibnesayeed** [comment]
This PR is ready for any code reviews or to be merged for about a month now. Please let me know if anything else is to be done on my end in order to get it merged.

**Comment by maggiepint** [comment]
This code looks good at a glance. Is there a second Urdu speaker who can greenlight this and be listed in the header file for future changes?

**Comment by ibnesayeed** [comment]
As far as the Urdu language and coding skills are concerned, my credentials are high enough. I have been managing and administering one of the most remarkable Urdu forums for almost a decade and translated various software (WordPress, vBulletin, and XenForo to name a few). However, if someone wants to have a look at the translation, that's perfectly fine. When it comes to software, there is always a place for improvement.

**Comment by maggiepint** [comment]
We always want a second person to have as a future contact. If you decide you don't do open source any more, but we need someone to code review changes to this file, then we're a bit out of luck without finding a second person. Do you know anybody who could do this?

**Comment by ibnesayeed** [comment]
I will ping @ZackVision and @saadatm here. If any of them responds here, their name(s) can be added as the fallback point of contact.

**Comment by ZackVision** [comment]
Looks good to me. You can add me as 2nd contact.

**Comment by ibnesayeed** [comment]
> @maggiepint: ... be listed in the header file for future changes?

Is there something called `header file` or did you mean `header of the file`?

**Comment by ibnesayeed** [comment]
> @maggiepint: We always want a second person to have as a future contact.

Is this a new requirement? Because I don't see many locale files with more than one authors in the header. If so, should it be documented in the `CONTRIBUTING` file?

**Comment by ibnesayeed** [comment]
Ping @maggiepint

**Comment by ichernev** [comment]
@ibnesayeed this is good to go. I guess @maggiepint was a bit scared of you being that only person on github that speaks Urdu, but then again, if somebody is unhappy with it, then he clearly speaks it, so I think it's less of an issue. Also 2 is bettern than 1 ;-)

**Comment by ichernev** [comment]
Merged in 363626cd7a9cdd4da1d5b8c50beef56b1fa0b80c

**Pull request closed without merging**
