### PR TITLE
fixed typos

### PR DESCRIPTION
**Pull request by seferov**

### CODE REVIEW

**Comment by ichernev** [comment]
@topchiyev what do you think?
@seferov you should port this to the new file structure (released in 2.10). Also update the tests.

**Comment by topchiyev** [comment]
Fixes made by @seferov are correct.

**Comment by ichernev** [comment]
@mj1856 can you please, instead of merge, tag the PRs with a milestone (next release -- currently its 2.10.5, we're skipping 2.10.4), and I do merging and rebasing on my own, so the history is much nicer. Basically the master/develop branch are not touched until a release is made, also PRs stay open until I merge them and cut the release.

**Comment by mj1856** [comment]
Will do.  Would have been nice to know this earlier.  We need to communicate better! :smile: 

Also, there is a bunch of stuff assigned to 2.10.4 milestone.  And 2.10 milestone too.

**Comment by ichernev** [comment]
@mj1856 we need a mail list or sth. Yes, there are a few old ones laying around. They need work, so I decided to postpone them at the time of the release.

**Pull request merged**
