### PR TITLE
[locale] ka: Improved past relative time

### PR DESCRIPTION
**Pull request by lashad**
Hello,

Small grammar error fix.

### CODE REVIEW

**Comment by ichernev** [comment]
@lashad you also need to change the tests so they pass. And don't make another pull request for that, please :) (its a challenge)

**Comment by ichernev** [comment]
@irakli-janiashvili what do you think

**Comment by lashad** [comment]
@ichernev user @irakli-janiashvili is no longer in GitHub

**Comment by ichernev** [comment]
Merged in 7b2c12e176eca4590892f91f77f2afea3a0cefa6

**Comment by brunjick** [comment]
@lashad Sorry, but how is that grammar error fix? Can you provide any proof?

**Comment by lashad** [comment]
@brunjick I was avoiding this conversation, but, I'm sorry I can not say shorter.

**5 minutes ago vs in front of 5 minutes**

There are two similarly looking words with totally different meanings in Georgian: წინ (in front of) and წინათ (ago). I’ll give examples with both words (წინ and წინათ) to make it easier for foreigners to understand how wrong it sounds. I have used the official book of Georgian Language Standards, pp. 427, 563 (ქართული ენის განმარტებითი ლექსიკონი, გვ. 427, 563, მთავარი რედაქტორი - არნოლდ ჩიქობავა). In case someone wonders where the following comes from. Definitely, not my personal opinion.

Meanings of **წინ** (in front of, before, forward):
 1. It is, usually, used with **place**:
Look **in front of** you! (**წინ** გაიხედე)
The boy was running **in front of** others (**წინ** ბიჭი გარბოდა, უკან სხვები მისდევდნენ)
He sat **in front of** fireplace (ბუხრის **წინ** იჯდა)
The tree was planted **in front of** the house (სახლის **წინ** ხე იყო დარგული)
2. Also, it can be used to describe an event or fact that has happened before another event of fact (in the following sentences **წინ** equals **-მდე**):
He wrote the will **before** he died (სიკვდილის წინ ანდერძი დაწერა ანუ ანდერძი სიკვდილამდე დაწერა)
He cleaned the table before he left (წასვლის **წინ** მაგიდა გაასუფთავა ანუ მაგიდა წასვლა**მდე** გაასუფთავა)
3. Forward! Attack! (წინ!) – In Georgian language, usually, it is an order to join the battle, an offer to join the game, etc.
**Forward**, lads, attack them! (**წინ**, ბიჭებო, შეუტიეთ!)
He looks **forward** (წინ იყურება)
He goes **forward** (წინ მიდის)


As the examples show, **წინ** (meaning - in front of, before, forward) has never been used and it cannot be used with **time**.

Now I’ll give examples of correct word for ‘ago’. It must be said that in Georgian language there are two words for ‘ago’:  **უკან** (just a little while ago) and **წინათ** (long time ago). Having such precise meanings, it easily proves how wrong it must me to use a wrong word instead of these two. Thats why I've changed word **წინ** to **უკან**

 - A little while **ago** we have been working (ცოტა ხნის **უკან** ვმუშაობდით)
I was not home 10 minutes **ago** (10 წუთის **უკან** შინ არ ვიყავი)
2 hours **ago** I have been watching a film online (ორი საათის **უკან** ინტერნეტში ფილმს ვუყურებდი)

I hope the examples prove why we should correct the wrong word to make it sound proper in Georgian. However, I’ll translate few examples how it sounds right now:
1. In front of 7 minutes (შვიდი წუთის წინ)
2. In front of one hour (ერთი საათის წინ)
3. 3 days in front (სამი დღის წინ)

I cannot imagine a native English speaker who could ignore such texts. I hope you can understand why I could not ignore similarly damaged Georgian and asked for your assistance with this problem.

Thank you and sorry for the long comment.

**Comment by brunjick** [comment]
@lashad Thanks,

I'm lazy, so I found this [article](http://orioniblog.blogspot.com/2012/06/blog-post_6070.html) which states some points.

> 5 minutes ago vs in front of 5 minutes

This is just ridiculous


> There are two similarly looking words with totally different meanings in Georgian: წინ (in front of) and წინათ (ago)

They aren't 'similarly looking' by accident, **წინათ** and many other words (**უწინ, უწინდელი, უწინდებური, წინანდელი, წეღან (წინ-ხან) ...**) are derived from **წინ**, and they all represent past tense. I can't see how **წინ** itself is an exception to this.

> As the examples show, წინ (meaning - in front of, before, forward) has never been used and it cannot be used with time.

Doesn't events happen in time?

> A little while ago we have been working (ცოტა ხნის უკან ვმუშაობდით)
I was not home 10 minutes ago (10 წუთის უკან შინ არ ვიყავი)
2 hours ago I have been watching a film online (ორი საათის უკან ინტერნეტში ფილმს ვუყურებდი)

Aren't these examples just made up? where is the reference? In fact, **უკან** is exactly the opposite, and represents future tense, no matter how counterintuitive it seems.

- "სამ დღეს უკან ფასს მოგიტანთო" (საბა, "ყაზან-შაჰ და მისი ცოლი")
- "ამ სამის დღის საყოფს პურსაც მოგცემო და ღვინოსაცაო და მას უკან თქვენ იცითო" ("რუსუდანიანი").
- "მას უკან, რაც ლეკებმა ქეთო გაიტაცეს, კარგა ხანმა განვლო" (ი. გოგებაშვილი, "იავნანამ რა ჰქმნა").

Lastly, you should submit your findings to [Arnold Chikobava Institute of Linguistics](http://www.ice.ge), because it seems they've made a [mistake explaining basic Georgian grammar](http://www.ice.ge/web/72/__3.html)

**Comment by lashad** [comment]
@brunjick Thank you. I did not have time to respond, sorry for the delay.
 
We do not think that it is an insignificant thing to feel lazy about. I assure you that we are pretty busy to spend our time on something unimportant.

It definitely sounds ridiculous to a Georgian ear when someone uses „წინ“ instead of „წინათ“ about time. Similarly common mistake is the incorrect usage of „მანძილზე“ (for length of last month) instead of „განმავლობაში“ (during last month) when speaking about time. The fact that people use incorrect forms cannot change the standard of the language, can it?

The first [article](http://orioniblog.blogspot.com/2012/06/blog-post_6070.html)  you have provided is not a solid source and cannot be taken seriously. It belongs to a Georgian, Lela Tepnadze, who as a blogger has no obligation to prove correctness of whatever she posts. The title ‘Useful Blog’ does not mean we are obliged to take her as a solid reference of Georgian language standard. She makes it clear that she intends to help Georgian teachers and uploads material according to personal motives. Obviously, she is neither an official representative of the Ministry of Education, nor a trustworthy authority. If she were she would state so. If she had a degree in Georgian language studies, she would not hide her achievements either. The leaflet she refers to is not a solid source, compared to the dictionary we use as our reference. And even Ms. Tepnadze says herself that both forms are used in Georgian language, although it is preferable (not a must) to use „წინ“ instead of „წინათ“. Preference is individual for each person, and cannot be considered as a grammar rule.

We have never said the origin of word „წინ“ was different from the origin of the words you have listed (უწინ, უწინდელი, უწინდებური, წინანდელი, წეღან...). Also, it is not the problem of the Georgian language if someone cannot see how „წინ“ has its own meaning and usage. Is there a possibility for a native English speaker to repalce ‘ago’ by ‘before’, or by ‘in front of’, or by ‘earlier’ (one of the words „წეღან“ from your list), or by ‘previous’ (another word „წინანდელი“ from the same list)? Definitely, we agree about their origin but all those words have different meanings and are used differently. We could continue your list: წინამორბედი, წინამძღოლი, წინაგრძნობა, წინადღე, წინამძღვარი, წინამებრძოლი, წინაპარი, წინასწარმეტყველი, წინაპირობა... They all have totally different meanings and are used differently despite the similar origin. If there were no need in such versatility, there would be just one word for each situation.

Actually, we did have a reference in our previous Email. We have named the solid source for Georgian language standards (ქართული ენის განმარტებითი ლექსიკონი, გვ. 427, 563, მთავარი რედაქტორი - არნოლდ ჩიქობავა). We believed it was obvious that the book was our reference. Thank you for using the website of Arnold Chikobava Institute of Linguistics. We hope you will not feel lazy to open the link that has the complete version of the reference we have based our statement on. There, you can have a look yourself what is the difference between „წინ“ and „წინათ“ (http://www.ice.ge/liv/liv/ganmartebiti.php). For the Georgians with high education and the university degree, Arnold Chikobava and his works are main source as a reference for the Georgian language. Otherwise, why would the Institute of Linguistis be named after him? Why not, Lela Tepnadze Institute of Linguistics, or someone else’s whose name may pop up in a google search result?

We deeply respect Sulkhan-Saba Orbeliani and Iakob Gogebashvili. However, there are two important things to take into consideration in our case. Firstly, they hardly write in modern Georgian language. In fact, Iakob Gogebashvili himself asked in his will to modernise his Dedaena (Mother Tongue) according to the changes of time and new generation, and so it was done couple of times. Secondly, our main purpose is to decide whether we use „წინ“ or „წინათ“, so let’s focus on the issue.

Twisting what we said cannot help you sound correct. Yes, events happen in time (We have never said otherwise, have we?). When it is about time – When has an event happened? 2 years ago. – „წინათ“ (which has an emphasis on time) is used. And when it is about place – Where has an event occur? In front of the house – „წინ“ (which has an emphasis on place) has to be used. An even has both – time and place when it happens. The freshmen are taught to use 5 W’s and an H to describe an event thoroughly (Who? What? When? Where? Why? How?). For example, you need to say ‘Two years ago a blue car stopped in front of my house’. Which of the sentences would you rather use – „ორი წლის წინათ ლურჯი მანქანა გაჩერდა ჩემი სახლის წინ“, or – „ორი წლის წინ ლურჯი მანქანა გაჩერდა ჩემი სახლის წინ“? I do believe that you would not pick the third option – „ორი წლის წინ ლურჯი მანქანა გაჩერდა ჩემი სახლის წინათ“. Now, that would definitely sound ridiculous.

Finally, we remind you a well-known Georgian saying as an example of correct usage of „წინ“: I hardly have two Fridays left to live („წინ ორი პარასკევიც აღარ მიდევს“, აკაკი წერეთელი). The saying means that there is little time left to live, therefore, it („წინ“) cannot mean that time has passed. Literal translation of the Georgian sentence means that time is ‘in front of’, ‘before’ the speaker to live in future, but no way it is ‘ago’ since he has not lived it yet. Thus, word „წინ“ does not mean time in past but time in future. It is a bit outdated saying from 19th century but no one could argue that Akaki Tsereteli cannot be a good reference along Iakob Gogebashvili, or Sulkhan-Saba Orbeliani.

Unless someone intends to become a Noah Webster of the Georgian language, Arnold Chikobava can be considered as the most respectful reference for Georgian language.

**Pull request closed without merging**
