### PR TITLE
Changed Swedish locale.

### PR DESCRIPTION
**Pull request by eweilow**
Changed the Swedish locale for lastWeek to something more like what one
would say. As it was before with for instance "Förra söndagen" (Last
Sunday) while referring to the closest passed Sunday is not what is used
in language, last Sunday refers to the Sunday before the closest passed
one, so I changed it to that.

### CODE REVIEW

**Comment by mattgrande** [comment]
You need to update the unit tests around this as well.

**Comment by ichernev** [comment]
@nissehutt thank you for the improvement, lets just ask @ulmus what he thinks.

**Comment by ulmus** [comment]
"Förra söndagen" is actually an ambiguous statement in Swedish, I believe. If today is Sunday, it will probably mean the last Sunday (one week ago), if today is Saturday, it still might for some people, but for some it could mean the Sunday 13 days ago. It is a common source of misunderstandings.

I agree with @nissehutt that "I söndags" is more unambiguous. It always refers to a Sunday no more than one week ago and I support the pull request.

To be consistent, we might want to change the nextWeek translation as well so that it reads `'[På] dddd LT'`, "På söndag" is a similar wording to "I söndags" but forward looking. What do you think @nissehutt?

**Comment by nissehutt** [comment]
That sounds like a good idea. I've added that to the pull request.

**Comment by ulmus** [comment]
Good, I approve of the pull request!

**Comment by ichernev** [comment]
Sorry for the delay. This needs to be rebased on top of latest develop. Check https://github.com/moment/moment/blob/develop/CONTRIBUTING.md for more info.

**Comment by ichernev** [comment]
Merged in 78e5500

**Pull request closed without merging**
