### PR TITLE
added kl. to the swedish times

### PR DESCRIPTION
**Pull request by ksnabb**
@jisaacks @ichernev please check the swedish localization fix

### CODE REVIEW

**Comment by mj1856** [comment]
@ksnabb - Please rebase to one commit.
@ulmus - Please review for validity.

Thanks.

**Comment by ulmus** [comment]
Sounds reasonable, but I think the kl should be marked as optional like in the Norwegian translation (nb.js), using '[kl.]'

**Comment by ksnabb** [comment]
I'm not sure what you mean? How do I mark it as optional?

The Norwegian translation looks like this for e.g. LLL:
`LLL : 'D. MMMM YYYY [kl.] HH:mm'`

and the proposed change for Swedish is almost the same (no dot after D):
`LLL : 'D MMMM YYYY [kl.] HH:mm'`

**Comment by ulmus** [comment]
Oops, bad reading skills on my part. Then I say go!

**Comment by ichernev** [comment]
Merged in e4856c9aebb17d528dc1f2034f74d5ace13c1b3f

**Pull request closed without merging**
