### PR TITLE
[locale] (ar-ma) adjust dow, doy to match fr

### PR DESCRIPTION
**Pull request by kafiln**

### CODE REVIEW

**Comment by marwahaha** [comment]
approval @ElFadiliY ?

**Review by ElFadiliY — APPROVED** [review]
Monday is the first day of the week.

**Comment by marwahaha** [comment]
@ElFadiliY - Thank you. Can you now review the code change?

@kafiln can you sign the CLA?

**Comment by kafiln** [comment]
@marwahaha done

**Comment by marwahaha** [comment]
@kafiln  - you also post that the first week is the week that contains jan 4. do you have a source for this?

**Comment by kafiln** [comment]
I did not find an official source for this but I live in Morocco and this is was I see.
Also, we mainly follow countries like France in this kind on situations, I guess this file was based on another Arabic locale, but we are very different from other Arabic countries. Finally, I never found a source where the 12th of January indicates the first week.
Cheers

**Comment by marwahaha** [comment]
Thanks for your comment. 

The code comment was in fact wrong, it should say the first week must include Jan 1.
https://momentjs.com/docs/#/customization/dow-doy/

@ElFadiliY - do you know whether the first week should include Jan 1 or Jan 4?

**Comment by marwahaha** [comment]
@ElFadiliY - does the first week include Jan 1 (could start in december) or Jan 4 (could start after jan 1)?

**Comment by marwahaha** [comment]
Thanks @kafiln

**Pull request merged**
