### PR TITLE
[bugfix] Fix locale autoload, revert #3344

### PR DESCRIPTION
**Pull request by ichernev**
This is a redo of #3344 that doesn't (hopefully) break karma + phantomjs -- #3431.
@ljharb @yiminghe let me know if that works for both of you.

### CODE REVIEW

**Comment by ljharb** [comment]
I'm afraid not - with 2.15 + this diff, i'm now getting "SyntaxError: import declarations may only appear at top level of a module". I think this approach is defeating babel-node or webpack, because it's not a static `require()` call.

**Comment by ichernev** [comment]
How about now?

**Comment by ljharb** [comment]
That seems to do it for me, thanks! Looking forward to the patch release :-D

**Comment by Aanal** [comment]
@ichernev thanks for fixing. Do you know when is the next patch release?

**Comment by ichernev** [comment]
I'll only revert #3344 for now, and release 2.15.1

**Comment by ichernev** [comment]
Merged in 0d67e7eaa50beed095b93dfd66593c9cd86f9712

**Comment by gfviegas** [comment]
```
import moment from 'moment';
import 'moment/locale/pt-br';

moment.locale('pt-br');
console.log(moment.locale()); // en
console.log(moment.locale('pt-br')); // en
console.log(moment.locale('pt-BR')); // en
```

Locale still doesnt work for me..
Using moment 2.15.1 in Ionic 2 RC0

**Comment by ichernev** [comment]
@gfviegas can you print output of `moment.locales()`. You can put a few prints in the code to figure out is the thing loading or not. Also, if you're loading the locale yourself (and you are) this change is not relevant for you.

**Comment by gfviegas** [comment]
@ichernev the output is:

["en"]

Am I doing something wrong to import the locale? It stopped working when I upgraded my Ionic to RC 0

**Comment by gfviegas** [comment]
Any thoughts on my issue?

**Comment by ichernev** [comment]
@gfviegas your locale is not getting loaded. Put a console.log in it. Or it is, but it can't load moment, so it can't attach itself properly. This is not the most complicated system, and so far you're the only one complaining, so I'm expecting to be something in your setup (that is simple to debug), rather than a bug in moment.

**Comment by gfviegas** [comment]
@ichernev thing is I don't know where I'm wrong on importing it. I'm following exactly the same example of the docs. Is my import code right?

**Comment by ichernev** [comment]
I said you need to debug it, I didn't say who is wrong or right, just where I'd expect to see the issue. You need to specify a reproducible environment if you want any external help. Most likely if you try to reproduce it cleanly you'll find the issue. Anyway, you can start by putting a few prints and seeing whether the locale file is downloaded and executed to start with.

**Comment by gfviegas** [comment]
@ichernev  I had to 
`import 'moment/src/locale/pt-br';`

instead of 

`import 'moment/locale/pt-br';`

to make it work. I have no idea why.

**Pull request closed without merging**
