### PR TITLE
[bugfix] Fixed moment.months() for PL locale

### PR DESCRIPTION
**Pull request by szwacz**
Fixes https://github.com/moment/moment/issues/5369

I've replaced hack with a bit nicer hack :)

### CODE REVIEW

**Comment by szwacz** [comment]
Just so everyone is aware.

Actually this bugfix changes behaviour of public API, so this might be breaking change for some projects.

Before fix `moment.monts()` returned `["(stycznia|styczeń)", "(lutego|luty)", "(marca|marzec)", "(kwietnia|kwiecień)", "(maja|maj)", "(czerwca|czerwiec)", "(lipca|lipiec)", "(sierpnia|sierpień)", "(września|wrzesień)", "(października|październik)", "(listopada|listopad)", "(grudnia|grudzień)"]` if someone to mitigate the bug was processing each string and extracting from it only one word, code of that person has high possibility of failing after the bugfix was applied to moment.js.

**Comment by marwahaha** [comment]
@szwacz i think you can remove the hack.

If you add a variable
```
    monthsParse = [
        /^sty/i,
        /^lut/i,
        /^mar/i,
        /^kwi/i,
        /^maj/i,
        /^cze/i,
        /^lip/i,
        /^sie/i,
        /^wrz/i,
        /^paź/i,
        /^lis/i,
        /^gru/i,
    ];
```

and add monthsParse:, longMonthsParse:, shortMonthsParse: , then removing the hack in src/locale/pl.js passes the test!
You can see cs.js as an example.


Perhaps that wasn't available in 2015 when you made your previous hack.

**Review by marwahaha — CHANGES_REQUESTED** [review]
use monthsParse:

**Comment by szwacz** [comment]
Thak you @marwahaha for pointing me into that direction. PR has been updated.

**Review by marwahaha — APPROVED** [review]

**Comment by marwahaha** [comment]
Thanks!

**Comment by dtokarczyk** [comment]
@szwacz hello! How can I get subjective all months in array (eg. ['stycznia', 'lutego', ...])?

**Comment by szwacz** [comment]
@dtokarczyk I'm afraid my changes in this PR didn't make it possible. I'm not aware if there is an API in moment that allows for implementing feature you're mentioning.

**Pull request merged**
