### PR TITLE
[locale] fa: Improve relative time for seconds

### PR DESCRIPTION
**Pull request by nasserghiasi**
add .idea (intellijIdea workspace settings) folder to .gitignore + fix context in Farsi locale

### CODE REVIEW

**Comment by ichernev** [comment]
@ebraminio

@nasserghiasi you need to change `src/locale/fa.js` and update `src/test/locale/fa.js`. Also remove the `.gitignore` change.

**Comment by ebraminio** [comment]
lgtm, thanks

**Comment by nasserghiasi** [comment]
@ebraminio it's done

**Comment by ichernev** [comment]
Merged in 14b29f6dbe1fb190f39c582167f77fb12f0401be

**Pull request closed without merging**
