### PR TITLE
[feature] Prevent toISOString converting to UTC (issue #1751)

### PR DESCRIPTION
**Pull request by ashsearle**
A minimal effort to allow users to opt-out of UTC conversion when calling `toISOString()`:

```js
moment().toISOString();
moment().toISOString({ utc: false });
```

Example while running in Europe/London timezone:
```js
moment('2017-07-01').toISOString(); // 2017-06-30T23:00:00.000Z
moment('2017-07-01').toISOString({ utc: false }); // 2017-07-01T00:00:00.000+01:00
```

The PR preserves existing behaviour of converting to UTC by default.

### CODE REVIEW

**Comment by icambron** [comment]
I love the option object pattern, but it's not how Moment works stylistically. Maybe just a boolean arg?

**Comment by ashsearle** [comment]
Sure, I'm happy to change.  Which way round do you want it: should `toISOString()` be the same as `toISOString(true)` or `toISOString(false)`?

I guess a single argument is also easy enough to expand in future too: e.g. by passing in `60` or `+01:00` to get an ISO string in the specified offset...?

**Comment by icambron** [comment]
Right, something like that. Honestly, the object is better, but when in Rome...

On defaults, I think it's more intuitive to default to `false`.

**Comment by ashsearle** [comment]
Updated...

Is the function parameter name OK?

**Comment by icambron** [comment]
The name seems fine

**Pull request merged**
