### PR TITLE
Add the unit of time for minute in locale(zh-tw). 

### PR DESCRIPTION
**Pull request by wtsai**
I add the unit of time for minute in traditional chinese (zh-tw), and the unit test is pass now.

Testing zh-tw.js........................OK

### CODE REVIEW

**Comment by ichernev** [comment]
OK, so should zh-cn be also changed or just Taiwan.

**Comment by ichernev** [comment]
I'll merge this in next release.

**Comment by wtsai** [comment]
It would be great if this modification can merge to zh-cn too. Should I commit another modification for zh-cn too?

**Comment by hemp** [comment]
@wtsai Do you want to update this PR for both zh-tw and zh-cn?  My project is currently going through zh-cn translation and they would like the minute unit added for zh-cn.  My guess is if we do zh-tw translation next, they would want it there too.  

I can make the change for both zh-tw and zh-cn in a new PR if that would help?  Either way works for me :smile:

**Comment by ichernev** [comment]
This is merged.

**Pull request closed without merging**
