### PR TITLE
[locale] correct translation of locale for Vietnam

### PR DESCRIPTION
**Pull request by chienkira**

### CODE REVIEW

**Comment by marwahaha** [comment]
@bangnk approval?

Please edit `src/locale/vi.js`.

**Comment by chienkira** [comment]
@marwahaha Thank you for checking my PR. The check "Generated files — Don't edit moment.js, min/*, locale/*, build/*." didn't get passed. What else i need to do?

**Comment by marwahaha** [comment]
1. Please undo your change to `locale/vi.js`.
2. Please make the change in `src/locale/vi.js`.
3. Please change the tests in `src/test/locale/vi.js`.

Hope this helps!

**Comment by chienkira** [comment]
@marwahaha Thank you very much for the details. I have updated PR.

**Comment by marwahaha** [comment]
@chienkira can you re-do the last git commit with the same email address? You can set the email address like `git config --global user.email marwahaha@berkeley.edu` 

@bangnk approval?

**Comment by chienkira** [comment]
@marwahaha sorry my bad! I have re-done the commit with github email address. Thank you very much.

**Comment by HTL-chien** [comment]
@marwahaha Sorry, any update? Is there any reviewer else?
@bangnk Hi, Are you still active on github?

**Comment by chienkira** [comment]
@marwahaha Sorry, any update? Is there any reviewer else?
@bangnk Hi, Are you still active on github?

**Comment by kylekatarnls** [comment]
Google Translate:
`rồi` = already
`trước` = before
`tuần rồi lúc` = last week
`tuần trước lúc` = the week before
Reverting translation:
last week = `tuần trước`

https://glosbe.com/en/vi/last%20week
trước: 24 occurences in articles
rồi: 4 occurences in articles

Both seems right but `trước` seems more common.

`rồi` seems to be the contrary of `tới` when `trước` would be the contrary of `sau`, But for this one, `tới` is more common:
https://glosbe.com/en/vi/next%20week

I was thinking of changing this for Carbon too. But I'm hesitating because of that.

@chienkira Are you a native Vietnamese speaker? Are you sure `rồi` can be changed to `trước` while keeping `tới` unchanged? (They can appear in the same sentence).

**Comment by chienkira** [comment]
@kylekatarnls Thank you for checking. Actually I'm a Vietnamese.
> Are you a native Vietnamese speaker? Are you sure `rồi` can be changed to `trước` while keeping `tới` unchanged?

Yes I'm sure. We say `tuần trước` for `last week`, not say `tuần rồi` in common.  There is nothing likes `tuần rồi` in our language - Vietnamese.
About `next week`, we say both `tuần sau` and `tuần tới`, so IMP it's not necessary to make a change with `tới`.

**Comment by chienkira** [comment]
@kylekatarnls Google translate is doing well. You can check it here.
https://translate.google.com/#view=home&op=translate&sl=en&tl=vi&text=last%20week

**Comment by kylekatarnls** [comment]
Seems also coherent with the current `past : '%s trước',`

As for what is worth, I'm convinced.

**Comment by chienkira** [comment]
@marwahaha Is there any update? pls

**Comment by marwahaha** [comment]
@chienkira This is fine. Would you like to be another locale author? If so, please add your name in the same format underneath @bangnk .

**Comment by chienkira** [comment]
@marwahaha Thank you for checking my PR. Yes I'm very glad to be a locale author. 
> If so, please add your name in the same format underneath @bangnk

Sorry but I don't know what should I do exactly?

**Comment by marwahaha** [comment]
Please add this line underneath line 3 of `src/locale/vi.js`:
```
//! author : Chien Kira : https://github.com/chienkira	
```

**Comment by chienkira** [comment]
Thank you. I have edited that line.

**Pull request merged**
