### PR TITLE
[bugfix] Fix circular dependency issue

### LINKED ISSUE #4756: [IE11] [Polyserve] circular dependency issue throwing 'Object expected' in IE
I have an issue with moment when using Polymer's CLI to serve the files in IE11. When `src/lib/units/year.js` is compiled it becomes broken, with certain objects being undefined.

Looking through the code it seems `src/lib/units/year.js` (YEAR) imports a function from `src/lib/moment/get-set.js` (GET-SET) and GET-SET imports a function from YEAR. This is fine, however, one of the exports from YEAR is returning a function reference from GET-SET which seems to be the issue.

This is the line in question:

https://github.com/moment/moment/blob/2e2a5b35439665d4b0200143d808a7c26d6cd30f/src/lib/units/year.js#L71

Returning its own function fixes the issue. For example:
```js
export var getSetYear = function () {
    return makeGetSet('FullYear', true).apply(this, arguments);
}
```

### PR DESCRIPTION
**Pull request by TremayneChrist**
This fix improves upon #4763 by splitting out `isLeapYear` into a separate module so that it can be shared across `year.js` and `get-set.js` removing the circular dependency.

fixes #4756

### CODE REVIEW

**Comment by TremayneChrist** [comment]
@ichernev would you be able to review this? I am unable to upgrade the library until #4756 is fixed.

CC: @marwahaha

**Comment by jpike88** [comment]
@marwahaha please give this attention, this is causing issues across a range of bundlers and loaders, and requires urgent attention. Circular dependencies are serious design flaws and should be addressed asap.

**Comment by cnjap** [comment]
Hi guys, any update  about this PR?

**Comment by lyind** [comment]
I am using moment 2.24.0 and this issue is affecting my build.

The fix is right here, please review and merge!

**Comment by TremayneChrist** [comment]
Once again, @ichernev @marwahaha @timrwood @icambron please could you review this?!

**Pull request merged**
