### PR TITLE
[new locale] (ig) Added Igbo language

### PR DESCRIPTION
**Pull request by bukkysos**

### CODE REVIEW

**Comment by ichernev** [comment]
@bukkysos you should add you file under `src/locale/xx.js`, don't modify `locale/**`. Also use the correct locale designation (2 letters + 2 letter country in most cases).

**Comment by ichernev** [comment]
The correct code is `ig` https://en.wikipedia.org/wiki/Igbo_language ISO 639-1

**Comment by ichernev** [comment]
I just noticed you haven't added a test file. All locales have one -- have a look under `src/test/locale/*.js`

**Comment by marwahaha** [comment]
@bukkysos any update?

**Review by anandfresh — APPROVED** [review]

**Comment by ichernev** [comment]
You need to name the locale file `ig.js` and place it under `src/locale/ig.js`. Also tests go under `src/test/locale/ig.js`. You have copied the locale code for the test file... this is not how it works. Examine another locale test file for inspiration.

Closing for now, feel free to re-open if you fix the above

**Pull request closed without merging**
