### PR TITLE
Fix date format for Czech

### PR DESCRIPTION
**Pull request by enumag**
See #2016.

### CODE REVIEW

**Comment by enumag** [comment]
Hmm I don't understand why the tests passed if I did not fix them. Any ideas?

**Comment by Oire** [comment]
@petrbela, your thoughts, please?

**Comment by petrbela** [comment]
It seems `l` is not an option in `longDateFormat`. From looking at other parts of the code, there isn't any `shortDateFormat`; maybe the short versions are generated dynamically from the long?

So far, this change doesn't change the behavior (as confirmed by the test), as the `l` most likely is getting ignored.

**Comment by enumag** [comment]
Yeah, I was thinking the same thing. I did see an `l` option in some other language file though (don't remember which).

**Comment by Oire** [comment]
@mj1856, can we change `l` separately?

**Comment by mj1856** [comment]
I *thought* you could, but I can't find it... @ichernev ?

**Comment by maggiepint** [comment]
You should be able to change ``l`` by itself. It's in the following function:

```js
    function longDateFormat (key) {
        var format = this._longDateFormat[key],
            formatUpper = this._longDateFormat[key.toUpperCase()];

        if (format || !formatUpper) {
            return format;
        }

        this._longDateFormat[key] = formatUpper.replace(/MMMM|MM|DD|dddd/g, function (val) {
            return val.slice(1);
        });

        return this._longDateFormat[key];
    }
```
None of the locales do it that I can tell, but it doesn't mean you couldn't.

In fact, the following code works just fine:

```js
//change the 'l' format to be month abbreviation, just to make it obvious that we aren't falling back to default
moment.updateLocale('en', {longDateFormat: {l:'MMM'}})
//format something with `l`
moment().format('l')
"Apr"
```

If you were going to introduce this to this locale, I would definitely explicitly test it.

**Comment by ichernev** [comment]
@maggiepint is right, just using `l` should work. Just make sure to modify `src/locale/cs.js` and `src/test/locale/cs.js`

**Comment by maggiepint** [comment]
Any progress on this. The modifications need to be made to different files. The change is fine, but needs a unit test.

**Comment by petrbela** [comment]
@enumag Are you working on this?

**Comment by enumag** [comment]
@petrbela No.

**Comment by ichernev** [comment]
Close in favor of #3237.

**Pull request closed without merging**
