### PR TITLE
[locale] sl: Fix date format

### PR DESCRIPTION
**Pull request by brgrz**
[locale] corrected to official Slovenian date format for short dates

### CODE REVIEW

**Comment by brgrz** [comment]
@marwahaha Why is the travis build failing?

**Comment by ichernev** [comment]
@sedovsek what do you think?

@brgrz you also need to update the tests.

**Comment by sedovsek** [comment]
@ichernev Makes sense!
Thanks, @brgrz.

**Comment by ichernev** [comment]
Merged in ed6fd040527d0a81b86695f898ac0b6e6f479295

**Pull request closed without merging**
