### PR TITLE
Fix errors in `npm run prettier-check` and` npm run prettier-check`

### PR DESCRIPTION
**Pull request by Alanscut**
## Changes
* Fix errors in `npm run prettier-check` and` npm run prettier-check`
* Fix issue for #5466

### CODE REVIEW

**Comment by ichernev** [comment]
These are not errors, these are features. I added those quotes for a reason. Is it not working for you? The docs says that it accepts globs, and this is just that, a glob handled by prettier. Otherwise you depend on your shell, which might be fancy (and handle them) or might not be fancy (CI) and not handle it ...

**Comment by Alanscut** [comment]
@icambron Yes, When `cmd` is executed,` npm run prettier-check` and `npm run prettier-fmt` error.

moment_prettierfmt_bug

moment_eslint_bug

**Comment by ichernev** [comment]
@Alanscut works for me and works for the CI... what is your environment? OS, shell, version of prettier?

**Comment by Alanscut** [comment]
@ichernev My environment is as follows.
 - OS: Windows Server 2008 R2 Standard
 - editor: Visual  Studio Code 1.43.2
 - prettier: @latest

**Comment by ichernev** [comment]
@Alanscut check latest develop: f9e42d2cf88b41087d8bf9e6cebc43f48a2ed7f8

**Pull request closed without merging**
