### PR TITLE
Talossan (tzl) translation

### PR DESCRIPTION
**Pull request by robin0van0der0v**
Hello, together with Iustì Canun I created a Talossan (tzl) translation of Moment.js.
It is almost finished, but there is one problem.
The relative time sentences don't fit in the variables, they differ per time (future/past).
Could somebody explain to me how I can implement the time sentences?

The missing future sentences:
in a few seconds => osprei viensas secunds
in a minute => osprei 'n míut
in % minutes => osprei % míuts
in an hour => osprei 'n þora
in % hours => osprei % þoras
in a day => osprei 'n ziua
in % days => osprei % ziuas
in a month => osprei 'n mes
in % months => osprei % mesen
in a year => osprei 'n ar
in % years => osprei % ars

The missing past sentences:
a few seconds ago => ja'iensas secunds
a minute ago => ja'iens míut
% minutes ago => ja % míuts
an hour ago => ja'iensa þora
% hours ago => ja % þoras
a day ago => ja'iensa ziua
% days ago => ja % ziuas
a month ago => ja'iens mes
% months ago => ja % mesen
a year ago => ja'iens ar
% years ago => ja % ars

### CODE REVIEW

**Comment by ichernev** [comment]
Lets not argue about politics.

@robin0van0der0v what you want to achieve is relatively simple, using the advanced (function API). Check the russian language for reference. The arguments are `value`, `withoutSuffix`, `unit`, `isFuture`.

**Comment by robin0van0der0v** [comment]
@ichernev I already checked the documentation and just checked the Russian locale, but I couldn't find my answer.

I will try to explain it more clearly.
If a year is shown, it should add the suffix "/"+(years since December 26 in Roman numerals).

Examples:
Thursday, Decemer 25, 2014 = Xhúadi, li 25. Zecemvar dallas 2014/XXXV
Friday, December 26, 2014 = Viénerçi, li 26. Zecemvar dallas 2014/XXXVI

**Comment by ichernev** [comment]
Ah, well this is not supported at the moment, you can add a postformat that
detects the year and replaces it with this year plus roman thing.

**Comment by ichernev** [comment]
@robin0van0der0v we changed the directory / locale structure a bit, can you please rebase. I'll merge it afterwards. Also, you can really do the year correctly, as long as you "mark" it in a way, then detect it in postformat and replace it. Something like `##YYYY##`, then search for `##\d+##` and replace it with roman numerals.

**Comment by ichernev** [comment]
Close in favor of #2508

**Pull request closed without merging**
