### PR TITLE
Fix th locales months short to correctly in thai language

### PR DESCRIPTION
**Pull request by nonmadden**
ref: http://www.xn--12c0ecxsex2q.com/%E0%B8%95%E0%B8%B1%E0%B8%A7%E0%B8%A2%E0%B9%88%E0%B8%AD%E0%B9%80%E0%B8%94%E0%B8%B7%E0%B8%AD%E0%B8%99/

### CODE REVIEW

**Comment by icambron** [comment]
This changes needs to go in src/locale/th.js, not locale/th.js

**Comment by Oire** [comment]
@nonmadden, any update on this? The tests are still failing. @sirn, your opinion, please?

**Comment by sirn** [comment]
@Orie the change looks OK to me. (I can't quite recall why I used the informal form in the first place, and the formal one in this PR definitely a better one.)

**Comment by Oire** [comment]
@nonmadden, please fix `format month` tests and we'll stage this for the next release.

**Comment by nonmadden** [comment]
Yes

**Comment by maggiepint** [comment]
@nonmadden we are closing this pull request as we haven't heard back from you. If you make the changes that we requested, we are more than happy to re-open it and get it merged. Thanks again for contributing!

**Pull request closed without merging**
