### PR TITLE
[locale] pl: Improve calendar for next week

### PR DESCRIPTION
**Pull request by waclawjacek**
The names of days of next week aren't declended in the Polish translation. This PR adds the declension.

@evoL, could you please provide an opinion on this PR?

### CODE REVIEW

**Comment by waclawjacek** [comment]
The build failure is caused by a bug fixed in #4060

**Comment by evoL** [comment]
This looks very good; thank you very much!

**Comment by waclawjacek** [comment]
Restarting the build

**Comment by ichernev** [comment]
So next week and prev week had different code? Lovely

**Comment by waclawjacek** [comment]
@ichernev, hmm, not quite! It's just that the declension rules for days of next week weren't in place. And they are slightly different than the ones for last week. :)

**Comment by ichernev** [comment]
@waclawjacek I mean, one had code and the other didn't, which is pretty **different** :D

**Comment by ichernev** [comment]
Merged in e2fcca2fb2628d5f0199c218b325d3733baa49f2

**Pull request closed without merging**
