### PR TITLE
Patch for pull 2051

### PR DESCRIPTION
**Pull request by zenozeng**
remove unnecessary space and update tests for #2051

### CODE REVIEW

**Comment by zenozeng** [comment]
@ichernev

**Comment by ichernev** [comment]
@zenozeng sorry for being late :)

Can you please rebase on top of latest develop, we changed the code structure (`src/locale`).

**Comment by zenozeng** [comment]
Done. Sorry for my late response, I was too busy these days :laughing: .

**Comment by ichernev** [comment]
Merged in b79fce9

**Pull request closed without merging**
