### PR TITLE
Add convenience methods for date comparisons

### PR DESCRIPTION
**Pull request by nscornia**
*   isSameOrAfter

*   isSameOrBefore

### CODE REVIEW

**Comment by Soulcyber** [comment]
+1

**Comment by ichernev** [comment]
@nscornia you need to add tests.

**Comment by nscornia** [comment]
Sure I can write some up. I just wasn't sure since there wasn't any new logic added.

**Comment by ichernev** [comment]
There is new API added... logic an implementation detail.

**Comment by nscornia** [comment]
Ok, I've added the tests, but it looks like the Travis build is failing on a completely unrelated test. Any advice?

**Comment by nscornia** [comment]
Nevermind, I got it fixed.

**Comment by ichernev** [comment]
Merged in 3ab9469e313cbec219a020b91a4b2704cf788057

**Pull request closed without merging**
