### PR TITLE
Adding locale for Algeria

### PR DESCRIPTION
**Pull request by noureddineme**

### CODE REVIEW

**Comment by mj1856** [comment]
Hello,

You're editing the wrong file.  Please read the [contributing guidelines](https://github.com/moment/moment/blob/develop/CONTRIBUTING.md), under the "Code organization" heading.

Please provide unit tests as well.  Thanks.

**Comment by noureddineme** [comment]
Thank you @mj1856, I think now it is good to go.

**Comment by mj1856** [comment]
Could you please rebase this to a single commit?  Thanks.

**Comment by noureddineme** [comment]
in new PR ?

**Comment by mj1856** [comment]
For future reference, you don't need to create a new PR when making changes.  If the PR is unmerged, you simply update the source of the PR (the branch in your fork where the PR originated) and push.  The PR will be updated automatically.

**Comment by noureddineme** [comment]
OK, Thank you @mj1856

**Pull request closed without merging**
