### PR TITLE
[locale] Correct swedish ordinals

### PR DESCRIPTION
**Pull request by perenstrom**
Moment is currently formatting Swedish ordinals incorrectly. Added colon between number and ordinal character.

Ping @ulmus as original author.

Sources:
* https://learningswedish.se/courses/1/pages/ordinal-numbers
* http://swedishbitz.com/ordinal-numbers/

### CODE REVIEW

**Comment by perenstrom** [comment]
I can't really decipher the travis error, but it doesn't seem to be related to my PR?

**Comment by brgrz** [comment]
Would someone please reply about what's going on with Travis error, there's dozens of PRs waiting due to obscure Travis CI errors, including mine

@marwahaha @ichernev

**Comment by ichernev** [comment]
Don't worry about the travis issue for now.

@perenstrom Can you point to some official documents describing the datetime rules for this locale? Also, if the existing format is also used in practice it makes sense to at least let parsing work for both the old and new format.

**Comment by perenstrom** [comment]
@ichernev 
I have attached some screenshots from "Svenska Skrivregler" (Swedish Rules for Writing) published by "Institutet för språk och folkminnen" (Institute for Language and Folklore). They are "a Swedish government agency with a focus on dialects, language policy, language planning,  names and folklore."

https://www.isof.se/om-oss/verksamhet/about-the-institute.html
The book: https://www.isof.se/om-oss/publikationer/institutets-publikationer/sprakvard/2017-07-06-svenska-skrivregler-2017.html

## Ordinals
The screenshots says:
> Ordinals.
> Ordinals are written with numbers followed by a colon and the ordinal's last letter.

Screenshot 2020-04-24 09 37 17

## Ordinals and date
The sreenshot says: 
>In dates with day followed by month, the day is always written with only numbers (>11.6.2). This also applies to regency numbers, which are always expressed with roman numerals (>11.12).
>Ludvika the 6th of June, Carl XVI Gustaf

Screenshot 2020-04-24 09 42 37

## Dates
The screenshot says:
> Dates
> a) dates with names of month
> Dates kan be written multiple ways. The most clear and suitable way is to write the month's name with letters. This way of dating can always be used in body text as well as in numerous other contexts.
>
> _(den) 20 maj 2009_ (the 20th of May 2009)
>
> The word _den_ (the) is usually written, but can be left out, especially when the date is not in body text. When the month is not given, _den_ (the) has to be written for clarity. Ordinals are normally not marked with colon and ending letter in dates.
>
> _Payment is made den 15 (the 15th) of each month._
>
> If it isn't clear that the text is regarding a date you can for clarity use colon and ending letter.
>
> _It was something mystical with den 15:e (the 15th)_

Screenshot 2020-04-24 09 54 03

**Pull request merged**
