### PR TITLE
[bugfix] date is invalid and inBetween (inclusive) returns always true

### PR DESCRIPTION
**Pull request by lucenera75**
when date is invalid the method inBetween with inclusivity != '()' returns always true.

### CODE REVIEW

**Comment by lucenera75** [comment]
I'm not sure the travis build is related with this pr...

**Comment by marwahaha** [comment]
@lucenera75  - you need to sign the  CLA. You can instead squash your commits - I think that will fix the problem.

**Comment by lucenera75** [comment]
@marwahaha I think I've done what is needed, but the cla is still yellow :(

**Comment by ichernev** [comment]
This is was fixed in 40b52a0333f2620f1c3fc3bdad7dc71b5941c13f

**Pull request closed without merging**
