### PR TITLE
Fix months parsing for stranger locales

### LINKED ISSUE #2841: parsing bug for MMM
```
> moment('1-jan-2016', 'D-MMM-Y', true).isValid()
    true
> moment('1-jan-2016', 'D-MMM-Y', true).year()
    2015
> moment.version
    "2.10.6"
```

### PR DESCRIPTION
**Pull request by ichernev**
This fixes #2841

TODO:
- [ ] add weekdays in the mix
- [ ] test with months ending in dot and enable it there too
- [x] sort regex parts by reverse length
- [ ] add tests specific to this feature
- [ ] fix polish monthsParse hack

### CODE REVIEW

**Comment by ichernev** [comment]
This got out of hand. I'll merge it because it does fix `gd` locale without breaking everything else. But a proper fix is still to come.

**Comment by xiphiaz** [comment]
@ichernev will this merge allow 2.11.1 to be tagged?

**Comment by ichernev** [comment]
@xiphiaz I'll merge, tag and everything very soon.

**Comment by ichernev** [comment]
Merged in cd03daeac9273fae3419494f9885c374a0c1489f

**Comment by mj1856** [comment]
@ichernev - Are all 5 of the checkboxes at the top of this completed, or just the one?

**Comment by ichernev** [comment]
@mj1856 only one. I completely forgot about this one. I'm re-doing https://github.com/moment/moment/pull/2782 using this code (completing the TODO list :)).

**Pull request closed without merging**
