### PR TITLE
Fixed short thai months

### PR DESCRIPTION
**Pull request by aijo**
I found that momentjs is using invalid short month abbreviation for thai language.
Reference from the following source : 
- [http://www.thai-language.com/ref/months](http://www.thai-language.com/ref/months)
- [https://th.wikipedia.org/wiki/](https://th.wikipedia.org/wiki/%E0%B9%81%E0%B8%A1%E0%B9%88%E0%B9%81%E0%B8%9A%E0%B8%9A:%E0%B8%8A%E0%B8%B7%E0%B9%88%E0%B8%AD%E0%B8%A2%E0%B9%88%E0%B8%AD%E0%B9%80%E0%B8%94%E0%B8%B7%E0%B8%AD%E0%B8%99)

Please review my pull request :)

### CODE REVIEW

**Comment by frankind** [comment]
Thank you. This is a correct Thai short month.

**Comment by Oire** [comment]
Maybe is it worth to add some tests for the change? @mj1856, @maggiepint?

**Comment by maggiepint** [comment]
This is wrong file modified. Modifications need to be made to /src/locale/th.js and /src/test/locale/th.js

**Comment by aijo** [comment]
Hi @maggiepint, I modified both of your suggestion files. Please check my new commit :)

**Comment by ichernev** [comment]
This will be released in next version.

**Comment by ichernev** [comment]
Merged in 204bf43b7c0534771d3a774b68263a0b83539c9f

**Pull request closed without merging**
