### PR TITLE
[new locale] kab: Create kab.js

### PR DESCRIPTION
**Pull request by mozillakab**
Create kabyle moment js

### CODE REVIEW

**Comment by marwahaha** [comment]
Hi @belkacem77  - I think some tests are failing. Can you look into it?

**Comment by marwahaha** [comment]
@belkacem77 - can you look at the tests?

**Comment by marwahaha** [comment]
@mozillakab - any update?

**Comment by ichernev** [comment]
Closing this because 115 tests fail.

**Pull request closed without merging**
