### PR TITLE
wrong abbreviation fix for month Maart

### PR DESCRIPTION
**Pull request by jmaleonard**

### CODE REVIEW

**Comment by jmaleonard** [comment]
Please accept this change. Right now I have to do this `.replace('Mrt', 'Mar')`

**Comment by ichernev** [comment]
@wernerm can you comment on this, please.

**Comment by ichernev** [comment]
@jmaleonard please follow https://github.com/moment/moment/blob/develop/CONTRIBUTING.md#changing-locale-files
You need to update src/locale/af.js and ser/test/locale/af.js

**Comment by ichernev** [comment]
@jmaleonard ok, CLDR agrees with you

**Comment by ichernev** [comment]
Close in favor of #3272

**Pull request closed without merging**
