### PR TITLE
[misc] Add coveralls testing to travis build

### LINKED ISSUE #2509: Coveralls.io reporting doesn't work
I think it is caused by running coverage on temporary (out-of-repo) files.

Initial coveralls integration written in #2387.

### PR DESCRIPTION
**Pull request by marwahaha**
I think this will just work. Check out my own Travis Builds and Coveralls here:
https://travis-ci.org/marwahaha/moment/builds
[Coverage Status](https://coveralls.io/github/marwahaha/moment?branch=add-coveralls)

Builds are significantly longer (takes ~4 minutes instead of ~3), but the coverage is probably worth it. I sort of prefer long builds to flaky/less-useful builds. (This is why I decided to test twice --- once with `default` and once with coveralls)

this is moment develop's, but it might be out of date
[Coverage Status](https://coveralls.io/github/moment/moment?branch=develop)

fixes #2509

### CODE REVIEW

**Comment by marwahaha** [comment]
@ichernev

**Comment by ichernev** [comment]
Looks good to me. If its only on travis I'm fine.

**Comment by ichernev** [comment]
Merged in 7c3d1ea50174826ecbbfed652b93ba534a9ec03b

**Comment by ichernev** [comment]
I had to revert this 619d0d27, the build was very flaky, especially on older node versions. We can put this back in after we figure out what is causing it, in the mean time I want travis builds to be green (while I'm preparing the next release).

**Comment by ichernev** [comment]
@marwahaha can you please investigate?

**Comment by icambron** [comment]
One option is to eliminate older Node versions from the CI

**Comment by marwahaha** [comment]
@ichernev I think increasing the wait time for qunit (changed from 2min to 10min) has fixed the circle builds:
https://travis-ci.org/moment/moment/builds/304282118

I restarted it and it succeeded again.

**Pull request merged**
