### PR TITLE
[locale] Fix 4189: Updated time separator for German-Swiss locale

### LINKED ISSUE #4189: Swiss times formatted wrongly
FYI: Just noticed when checking out the project that our time (German, Swiss) is misformatted. For 2pm, it shows `14.00` (single dot as separator) instead of `14:00` .

### PR DESCRIPTION
**Pull request by joelmheim**
Should be a straight forward update. 

fixes #4189

### CODE REVIEW

**Comment by joelmheim** [comment]
Think it is related to another issue [https://github.com/moment/moment/issues/2895](#2895). This contains a table of all the locales, but the swiss one is not listed. I'd be happy to have a look through all the other locals and check that the LT/LTS formats match the CLDR. I'm not able to update the table in issue 2895, but I could make a new one in a comment and update that.

**Comment by joelmheim** [comment]
Issue #4189

**Comment by ichernev** [comment]
@sschueller any comments?

**Comment by sschueller** [comment]
@ichernev ok with us. Thank you.

**Pull request merged**
