### PR TITLE
small changes in locale pt-Br translation

### PR DESCRIPTION
**Pull request by Italo-J-A-Fernandes**
Small changes but that leaves Moment.js much more pleasant and consistent with the one used in that country

### CODE REVIEW

**Comment by Italo-J-A-Fernandes** [comment]
I apologize for the failure but now the Contributor License Agreement is signed

**Comment by marwahaha** [comment]
@Italo-J-A-Fernandes  please edit `src/locale/pt-br.js`. There have been other discussions about this locale file. I recommend you search the Github issues in this repository for other discussions. 

@caio-ribeiro-pereira approval ?

**Comment by caio-ribeiro-pereira** [comment]
@Italo-J-A-Fernandes @marwahaha everything is fine, except that I do not agree with the line:

`weekdaysMin : 'Do_Se_Te_Qa_Qi_Se_Sá'.split('_')`

maybe it should be better in the previous way:

`weekdaysMin : 'Do_2ª_3ª_4ª_5ª_6ª_Sá'.split('_'),`

**Comment by caio-ribeiro-pereira** [comment]
another question why change from lowercase to capitalize? I think for a lib this kind of information should not be formmated, because I lot of system are using in this way.

What do you think guys?

**Comment by marwahaha** [comment]
For now, we will not take this change.
Please re-open if you come to an agreement on the proper locale file. 
I have merged the other change from #4557 and #4558 .

**Pull request closed without merging**
