### PR TITLE
Attempt to add support for ordinal format for quarters. Fixes issue #2559

### PR DESCRIPTION
**Pull request by joelmheim**
Have some problems removing historical commits from the PR. Please ignore the two initial commits listed. No source code is included with them.

I have added ordinal support for quarters and tests for that according to my understanding of issue #2559. If you also want me to add parsing support, please let me know. Of course also open to any comments you may have to my code.

### CODE REVIEW

**Comment by mj1856** [comment]
Please [rebase](https://help.github.com/articles/about-git-rebase/) and squash or fixup the changes.

**Comment by joelmheim** [comment]
Better now?

Sorry about not getting it right initially.

// Jørn

2015-10-13 18:41 GMT+02:00 Matt Johnson <notifications@github.com>:

**Comment by mj1856** [comment]
LGTM.  Thanks!

**Comment by ichernev** [comment]
Merged in c8d8095e2fc7b9f0d8eb5ffc338b10266e4a4b56

**Pull request closed without merging**
