### PR TITLE
[feature] Add era support for en,ja (closes #4591)

### LINKED ISSUE #4591: [Feature request] Support Era names
### Description
In Japan, government agency and some company use traditional Japanese Imperial Calendar. But it seems moment.js is currently not supporting era names ~~~other than Christian Era~~~. So I want to write some patch to improve this. But I'm not familiar with this code-base. And I'm not sure whether if this can be done with unicode date format standard.

This feature is implemented as `Era` in Single Unix Specification (SU).
Please refer to the following link.
http://man7.org/linux/man-pages/man3/strftime.3.html

And java has same feature implemented in `java.util.JapaneseImperialCalendar` class though i don't like this implementation.

Regards.

**Other information that may be helpful:**
* http://www.i18nguy.com/l10n/emperor-date.html

### Related Issue
* #3553 How to convert Gregorian year to the Japanese calendar year ?

### PR DESCRIPTION
**Pull request by eternalharvest**
### Abstract
This PR implements new feature which is proposed in #4591.
I intended to implement this feature to format or parse Japanese date with era name, but this feature is carefully designed so that can be used in any other country.

Historically, there are more than 200 eras in Japan.
But before 6th Meiji era, our ancestors had been using Chinese lunar calendar.
And I think it is inappropriate to represent these historical dates in Gregorian solar calendar dates.
So I define only 4 eras and 2 Christian eras in Japanese locale.

**Note:** Japanese Meiji government had decided to use Gregorian solar calendar system since Jan 1st, Meiji 6 (Jan 1st 1873).

Currently there is only few country which is using era names, but I think this feature also can be used in Taiwan or some Buddhism country which is using Gregorian calendar.

Thanks and regards.

### Related Issue
* #3553 How to convert Gregorian year to the Japanese calendar year ?
* #2586 To support the Taiwan year format
* #3262 Add BE Year (BB, BBBB)
* #874 Buddist Calendar / Thai solar Calendar support with format code BB, BBBB

### Format
|                           | Abbr	       | Era Name  | Narrow Name | Ordinal Year  | Year of Era              |
|---------------------------|--------------|-----------|-------------|---------------|--------------------------|
| **MOMENT**                | N, NN, NNN   | NNNN      | NNNNN       | yo            | y, yy, yyy, yyyy         |
| LDML                      | G, GG, GGG   | GGGG      | GGGGG       | ?             | y, yy, yyy, yyyy         |
| Single Unix Specification	| n/a          | %EC       | n/a         | %EY           | %Ey, %02Ey, %03Ey, %04Ey |
| Java                      | G, GG, GGG   | GGGG      | GGGGG       | yyyy          | y, yy, yyy               |
| Excel                     | g            | ggg, gggg | gg          | n/a           | e, ee                    |
| LibreOffice               | G            | GGG       | GG          | n/a           | e, ee                    |

#### Locale (en)
```javascript
> var moment = require('moment');
> 
> moment.loale('en');
> moment('1989-01-08').format('y N');
'1989 AC'
> moment([-468, 1, 1]).format('y N');
'469 BC'
```

#### Locale (ja)
```javascript
> var moment = require('moment');
> 
> moment.loale('ja');
> moment('1989-01-07').format('NNNNyoM月D日');
'昭和64年1月7日'
> moment('1989-01-08').format('NNNNyoM月D日');
'平成元年1月8日'
> moment('1989-01-07').format('Nyy.MM.DD');
'S64.01.07'
> moment('1989-01-08').format('Nyy.MM.DD');
'H01.01.08'
```

### CODE REVIEW

**Comment by ichernev** [comment]
@eternalharvest the code looks decent. I think it can go in in next release.

In the definition of the eras, why is BC ending on 31 Dec. Does it automatically round the day to the end? Shouldn't it be 1st Jan 0000 the end date for one era (BC) and the begining of the new era (AC). 

Also its not `AC` and `BC`. But `AD` and `BC` ;-)

**Comment by guisehn** [comment]
Any news on this one?

**Comment by guisehn** [comment]
@eternalharvest if I may ask, what is the workaround you use in your project?

I'm thinking in maybe creating a plugin so that I can avoid maintaining a fork just for my project while there's no decision about the pull request, but I'm wondering if there is another an existing plugin or workaround I could use.

**Comment by guisehn** [comment]
@eternalharvest if I may ask, what is the workaround you use in your project for now?

I'm thinking in maybe creating a plugin so that I can avoid maintaining a fork just for my project while there's no decision about the pull request, but I'm wondering if there is already an existing plugin (I couldn't find) or workaround I could use.

**Comment by giapnhdev** [comment]
How is it going? I hope this feature is supported on moment asap.

**Comment by ichernev** [comment]
Merged in 4b615b9d4b00808c16c06c69cfcaa4ecdaedd7b4

**Pull request closed without merging**
