### PR TITLE
[misc] Fix typo in CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by connection-reset**

### CODE REVIEW

**Comment by maggiepint** [comment]
Want to fix the spelling of attend while you're at it?

**Comment by connection-reset** [comment]
Yes, fixed that.

**Comment by ichernev** [comment]
Great, 2 mistakes in one line, and we're not even doing the meetings :D

**Comment by ichernev** [comment]
Merged in e76d3612bf9035cbd845262f96d5d4f266978d3f

**Pull request closed without merging**
