### PR TITLE
[bugfix] moment.weekdays accept string parameter as value

### PR DESCRIPTION
**Pull request by guimap**
bug Adding an OR condition when moment.weekdays receive a string value as parameters

### CODE REVIEW

**Comment by guimap** [comment]
There's 200 changes because i had to run `linter-formatter` to fix all linter into localefolder for then travis accept my commit

**Comment by guimap** [comment]
I could sign the CLA, how can i do that? Anyone can help me ?

**Comment by ichernev** [comment]
@guimap can you provide an example where the bug manifests? Also I'd rather just merge the 2 lines that fix the bug, don't worry about Travis, I hate when you have to make code "worse" to make it "better".

**Comment by guimap** [comment]
Hi @ichernev, sorry for the late 
I mentioned here in this issue an example 
https://github.com/moment/moment/issues/5933

Basically, the value changes depending of type props
example

**Comment by ichernev** [comment]
This is the typing spec of the function

```
  export function weekdays(): string[];
  export function weekdays(index: number): string;
  export function weekdays(format: string): string[];
  export function weekdays(format: string, index: number): string;
  export function weekdays(localeSorted: boolean): string[];
  export function weekdays(localeSorted: boolean, index: number): string;
  export function weekdays(localeSorted: boolean, format: string): string[];
  export function weekdays(localeSorted: boolean, format: string, index: number): string;
```

You're not supposed to pass a number as string (it treats it as format?).

**Pull request closed without merging**
