### PR TITLE
Bugfix: locale: Updated tamil archaic numerals to the one currently used

### PR DESCRIPTION
**Pull request by naveen-bharathi**
@ichernev @marwahaha @icambron 

The symbol map used for Tamil language are archaic numerals and are currently not used by the Tamil speaking people. 99.99% of the Tamil speaking people don't even know what these symbols mean. I am a Tamil speaking person and I could help moment in the Tamil locale. English numerals have been adapted for all kind of uses by the Government of Tamil Nadu and the Tamil people for all their purposes. Only English numerals are been used for almost 60 years now. The symbol map data from wikipedia will not help in this case.

I have updated the archaic Tamil numerals used for Tamil language to English numerals.

### CODE REVIEW

**Comment by naveen-bharathi** [comment]
@coveralls I think you are talking about some other locale

**Comment by marwahaha** [comment]
Thanks for this request.

* please do not edit `locale/ta.js`, it is generated
* please edit `src/locale/ta.js`
* please update tests at `src/test/locale/ta.js`

Since the locale author disagrees, can you find some sources online that support your change?

**Comment by naveen-bharathi** [comment]
https://en.wikipedia.org/wiki/Tamil_numerals image

From this wikipedia page, it can be easily understood that these numerals are out of date and unused.

**Comment by marwahaha** [comment]
@naveen-bharathi please edit `src/locale/ta.js`

**Comment by naveen-bharathi** [comment]
@marwahaha updated src/locale/ta.js and created a pull request. Ref: #5616

**Comment by naveen-bharathi** [comment]
@marwahaha  Since this pull request was created for the edit that was wrongly made in locale/ta.js, this pull request can be closed.

**Pull request closed without merging**
