### PR TITLE
[locale] gu: Improve past relativeTime

### PR DESCRIPTION
**Pull request by kartikm**
પેહલા-> પહેલા.

### CODE REVIEW

**Comment by kartikm** [comment]
Anything else to do from my side here?

**Comment by kartikm** [comment]
Bump. What's missing in this pull request?

**Comment by marwahaha** [comment]
@kartikm your tests are failing.
Thanks for opening this request.

Please only edit `src/locale/gu.js` and the tests in `src/test/locale/gu.js`.

Thoughts @Kaushik1987 ?

**Comment by ichernev** [comment]
@kartikm it's kind of hard for me to manage this patch when I don't even see the characters ... can you provide some source for this change (CLDR for example)? Also you need to change the right files as @marwahaha mentioned.

**Comment by marwahaha** [comment]
Thoughts @Kaushik1987

**Comment by Kaushik1987** [comment]
@marwahaha What can i help ? Sorry for late reply.

**Comment by marwahaha** [comment]
@Kaushik1987 - is this the correct change? Can you please review it.

**Comment by marwahaha** [comment]
Confirmed on Google Translate and the below website that it's probably a typo.
https://www.gujaratilexicon.com/dictionary/gujarati-to-english-translation/%E0%AA%AA%E0%AB%87%E0%AA%B9%E0%AA%B2%E0%AA%BE*/

https://www.gujaratilexicon.com/dictionary/gujarati-to-english-translation/%E0%AA%AA%E0%AA%B9%E0%AB%87%E0%AA%B2%E0%AA%BE*/

**Pull request merged**
