### PR TITLE
[locale] bs: Improve relative minute

### PR DESCRIPTION
**Pull request by rasidre**
This PR is a possible fix for Issue #5512 

FYI @frontyard @marwahaha
If this PR is fixing the issue, you can close PR #5713

### CODE REVIEW

**Comment by rasidre** [comment]
@frontyard your definition was almost right. It should be like this:

second
past: prije par sekundi <- correct
future: za par sekundi <- correct

minute:
past: prije jedne minute <- correct
future: za jedne minute <- NOT CORRECT, correct is "za jednu minutu"

hour
past: prije jednog sata <- NOT CORRECT, correct is "prije jedan sat"
future: za jednog sata <- NOT CORRECT, correct is "za jedan sat"

**Comment by marwahaha** [comment]
@frontyard approval?

**Comment by marwahaha** [comment]
@frontyard ?

**Comment by rasidre** [comment]
@marwahaha how long will we wait for a locale approvement?

**Comment by marwahaha** [comment]
I'll give it a few more days. @frontyard 

@rasidre Would you like to be a reviewer? You can add your name to the `src/locale` file.

**Comment by rasidre** [comment]
> @rasidre Would you like to be a reviewer? You can add your name to the `src/locale` file.
Of course 🙂  https://github.com/moment/moment/pull/5772

**Comment by ichernev** [comment]
Merged in 443d5de6116f9e3555d050b87612f873e44c6b6b

**Pull request closed without merging**
