### PR TITLE
[locale] ka: Improvements to relativeTime

### PR DESCRIPTION
**Pull request by jayarjo**
@iJaniashvili @torniker

### CODE REVIEW

**Comment by marwahaha** [comment]
@jayarjo - i think you have to update the tests too. (src/test/locale/ka.js)

**Comment by marwahaha** [comment]
@jayarjo it looks like there is a code style error:
https://travis-ci.org/moment/moment/jobs/370623982

**Comment by marwahaha** [comment]
@jayarjo - could you add a test that shows what this code does? You can add a test case in `src/test/locale/ka.js`.

**Comment by marwahaha** [comment]
@jayarjo any updates?

@iJaniashvili - approval?

**Comment by jayarjo** [comment]
@jayarjo sorry, was a bit loaded these days. Will unit test this. I stumbled on some additional things as well, not sure how to resolve them in generic way though.

**Comment by ichernev** [comment]
Merged in 647dbd2e991c1ee9d7e0a5c961edc6099050985c

**Pull request closed without merging**
