### PR TITLE
[locale] Update bo locale

### PR DESCRIPTION
**Pull request by JLHwung**
The monthsShort and weekdaysMin of bo locale is aligned with Unicode CLDR v32, see http://www.unicode.org/repos/cldr/tags/release-32-0-1/common/main/bo.xml.

cc @vajradog

### CODE REVIEW

**Comment by JLHwung** [comment]
The test failure is fixed on #4371. Will rebase after #4371 is merged.

**Comment by marwahaha** [comment]
Why is this test failing? Did it just start failing @JLHwung  ?

**Comment by JLHwung** [comment]
@marwahaha I ve updated the reason of test failure on #4371 and we can focus on locale revision on this PR.

**Comment by marwahaha** [comment]
@vajradog do you have any thoughts here?

**Comment by marwahaha** [comment]
@vajradog is this change correct?

**Pull request merged**
