### PR TITLE
[misc] Remove comments in minified code

### PR DESCRIPTION
**Pull request by skfd**
Fixes bug #3283: moment.min.js download contains comments .

### CODE REVIEW

**Comment by maggiepint** [comment]
Heads up. Because we came under JS Foundation management, we need a CLA signed for this to be merged. Should be just a couple clicks.

**Comment by ichernev** [comment]
@skfd can you please sign the CLA. I can not proceed otherwise.

**Comment by maggiepint** [comment]
closing as stale

**Comment by skfd** [comment]
That might have been fixed upstream. Can be fixed by updating `uglify` package.

**Comment by westy92** [comment]
Can we get this merged?  https://github.com/moment/moment/issues/3461 has been closed but should be reopened.

**Comment by ichernev** [comment]
Merged in d28a819dc668f107566f306f827df07d43e30287

**Pull request closed without merging**
