### PR TITLE
ku.js

### PR DESCRIPTION
**Pull request by CYAXXX**
This is the for Kurmanji Kurdish, can we add it please?

### CODE REVIEW

**Comment by Shpankov** [comment]
Hi all!
Actually, will be better to keep the language codes correctly in case of a file names. Thus, the new file for Kurdish Northern should be renamed to ku.js, but old one, that include Kurdish Central language, should be renamed to ckb.js.

**Review by CYAXXX — COMMENTED** [review]
//! moment.js locale configuration
//! locale : Kurmanji Kurdish [Ku]
//! author : Cyax : https://github.com/CYAXXX



   export default moment.defineLocale('ku-northern', {
    months: 'Çile_Reşemî_Adar_Avrêl_Gulan_Pûşber_Tîrmeh_Tebax_Îlon_Cotmeh_Mijdar_Berfanbar'.split(
        '_'
    ),
    monthsShort: 'Çil_Reş_Adr_Avr_Gul_Pûş_Tîr_Teb_Îlo_Cot_Mij_Ber'.split('_'),
    weekdays: 'Yekşem_Duşem_Sêşem_Çarşem_Pêncşem_În_Şemî'.split(
        '_'
    ),
    weekdaysShort: 'Yek_Duş_Sêş_Çarş_Pênc_În_Şem'.split('_'),
    weekdaysMin: 'Ye_Du_Sê_Ça_Pê_În_Şe'.split('_'),
    longDateFormat: {
        LT: 'HH:mm',
        LTS: 'HH:mm:ss',
        L: 'DD/MM/YYYY',
        LL: 'D MMMM YYYY',
        LLL: 'D MMMM YYYY HH:mm',
        LLLL: 'dddd, D MMMM YYYY HH:mm',
    },
    calendar: {
        sameDay: '[Îro di demjimêr] LT',
        nextDay: '[Sibehe di demjimêr] LT',
        nextWeek: 'dddd [di demjimêr] LT',
        lastDay: '[Duh di demjimêr] LT',
        lastWeek: '[Hefteya Dawî] dddd [di demjimêr] LT',
        sameElse: 'L',
    },
    relativeTime: {
        future: 'di %s',
        past: '%s borî',
        s: 'çirke',
        ss: '%d çirke',
        m: 'yek xulek',
        mm: '%d xulek',
        h: 'demjimêr',
        hh: '%d demjimêr',
        d: ' roj',
        dd: '%d roj',
        M: ' meh',
        MM: '%d meh',
        y: 'sal',
        yy: '%d sal',
    },
      },
    meridiem: function (hours, minutes, isLower) {
        if (hours < 12) {
            return isLower ? 'bn' : 'BN';
        } else {
            return isLower ? 'pn' : 'PN';
        }
    },
    meridiemParse: /bn|BN|pn|PN/,
    isPM: function (input) {
        return input === 'pn' || input === 'PN';
    },
    dayOfMonthOrdinalParse: /\d{1,2,3,4}(yemîn|yemîn|yemîn|emîn)/,
    ordinal: function (number) {
        var b = number % 10,
            output =
                ~~((number % 100) / 10) === 1
                    ? 'emîn'
                    : b === 1
                    ? 'yemîn'
                    : b === 2
                    ? 'yemîn'
                    : b === 3
                    ? 'yemîn'
                    : 'emîn';
        return number + output;
    },
    week: {
        dow: 1, // Monday is the first day of the week.
        doy: 4, // The week that contains Jan 4th is the first week of the year.
    },
});

**Review by CYAXXX — COMMENTED** [review]
.

**Comment by roj1512** [comment]
@Shpankov please see https://github.com/moment/moment/pull/6006.

**Comment by CYAXXX** [comment]
@roj1512 xwezî te ev ji devla central bikira sorani, dizanim nehatiye pejirandin, belkî qet neyê erêkirin jî lê herî kêm bila bê kêmasî be

**Comment by roj1512** [comment]
wan bi xwe dest ji projeyê berdane

**Pull request closed without merging**
