### PR TITLE
Correction of german localization (#2649)

### PR DESCRIPTION
**Pull request by lothargrieb**

### CODE REVIEW

**Comment by mj1856** [comment]
Per the [Contributing Guidelines](https://github.com/moment/moment/blob/develop/CONTRIBUTING.md), please only update the files under `/src`.  The others are auto generated.  You need to update both `/src/locale/de.js` and `/src/test/locale/de.js`.  Thanks.

**Comment by ichernev** [comment]
@lothargrieb any progress?

**Comment by ichernev** [comment]
@lluchs any comments on this?

According to CLDR nominative and accusative shortened cases are different (one has dots, the other doesn't).

**Comment by ichernev** [comment]
@lothargrieb can you please provide a regex to distinguish between standalone weekdays vs ones used in conjunciton with other stuff, like here:

https://github.com/moment/moment/pull/2741/files#diff-a03fc1ced8170ad648ebb9efeb2611a8R65

As I said in my earlier post, it looks like we need two variants (accusative / nominative or standalone / format, depending on how you want to call them).

**Comment by ichernev** [comment]
Closing for inactivity.

**Pull request closed without merging**
